# Experiment Runner with Automatic Data Loading

This notebook demonstrates the ExperimentRunner which:
1. **Loads experiment configuration from YAML** - including data loading config
2. **Automatically loads and parses data** - using configured loader and parser
3. **Runs multiple RAG configs** - either sequentially or in parallel
4. **Generates detailed reports** - per-query and aggregate metrics
5. **Compares results** - across different configurations

The experiment configuration in YAML specifies:
- Data source (HuggingFace dataset)
- Data parser (e.g., title_passage)
- RAG config directory
- Number of queries to evaluate
- Parallel execution settings

## 1. Setup & Dependencies

In [1]:
get_ipython().system('pip3 install datasets faiss-cpu sentence-transformers torch groq python-dotenv nltk pandas -q')

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

## 2. Imports

In [2]:
import os
from dotenv import load_dotenv

from experiment.experiment_config import ExperimentConfig
from experiment.experiment_runner import ExperimentRunner

load_dotenv(override=True)
print("HuggingFace token loaded:", bool(os.getenv("HF_TOKEN")))
print("Groq API key loaded:", bool(os.getenv("GROQ_API_KEY")))

/Users/adityanarayan/git/rag-foundry/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

HuggingFace token loaded: True
Groq API key loaded: True

## 3. Load Experiment Configuration

The experiment configuration file specifies:
- **data_loader**: How to load data (HuggingFace with dataset_name, subset, split)
- **data_parser**: How to parse documents (title_passage)
- **config_dir**: Directory containing RAG pipeline configs
- **num_queries**: Number of queries to evaluate
- **parallel**: Whether to run configs in parallel

In [3]:
# Load experiment configuration from YAML
EXPERIMENT_CONFIG_PATH = "experiment_configs/covidqa_experiment.yaml"
experiment_config = ExperimentConfig.load(EXPERIMENT_CONFIG_PATH)

print("Experiment Configuration:")
print(f"  Config Dir:  {experiment_config.config_dir}")
print(f"  Report Dir:  {experiment_config.report_dir}")
print(f"  Cache Dir:   {experiment_config.cache_dir}")
print(f"  Num Queries: {experiment_config.end_index}")
print(f"  Parallel:    {experiment_config.parallel}")
print(f"  Max Workers: {experiment_config.max_workers}")
print(f"\nData Loader:")
print(f"  Type: {experiment_config.data_loader['type']}")
print(f"  Config: {experiment_config.data_loader['config']}")
print(f"\nData Parser:")
print(f"  Type: {experiment_config.data_parser}")

Experiment Configuration:
  Config Dir:  config
  Report Dir:  reports
  Cache Dir:   cache
  Num Queries: 246
  Parallel:    False
  Max Workers: 1

Data Loader:
  Type: huggingface
  Config: {'dataset_name': 'galileo-ai/ragbench', 'subset': 'covidqa', 'split': 'test', 'limit': 246}

Data Parser:
  Type: title_passage

## 4. Initialize Experiment Runner

The ExperimentRunner will:
- Create report directory if it doesn't exist
- Load RAG configs from the specified directory
- Load and parse data automatically based on YAML config

In [4]:
# Initialize experiment runner
runner = ExperimentRunner(experiment_config)
print("ExperimentRunner initialized")

ExperimentRunner initialized

import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")
    
    # Display per-query results
    print("\nPer-Query Results:")
    display(report.sections[0].per_query)
    
    # Display aggregate statistics
    print("\nAggregate Statistics:")
    display(report.sections[0].summary)

In [5]:
# Load data automatically based on YAML configuration
print("Loading data based on experiment configuration...")
documents, raw_data = runner.load_data()

print(f"\n✅ Data loaded successfully!")
print(f"  Documents: {len(documents)} parsed documents")
print(f"  Raw Data:  {len(raw_data)} samples")

# Inspect first sample
first_sample = raw_data[0]
print(f"\nFirst Sample:")
print(f"  Question: {first_sample['question'][:100]}...")
print(f"  Documents: {len(first_sample['documents'])}")

Loading data based on experiment configuration...
Loading HuggingFace dataset: galileo-ai/ragbench/covidqa (test)...
Loaded 246 samples

✅ Data loaded successfully!
  Documents: 984 parsed documents
  Raw Data:  246 samples

First Sample:
  Question: Which viruses may not cause prolonged inflammation due to strong induction of antiviral clearance?...
  Documents: 4

## 6. Load RAG Pipeline Configs

Load all RAG pipeline configurations from the config directory specified in the experiment config.

In [6]:
# Load RAG pipeline configs
configs = runner.load_configs()

print(f"Loaded {len(configs)} RAG pipeline configurations:")
for cfg in configs:
    print(f"  - {cfg.name}")
    print(f"    Chunking: {cfg.chunking.type.value}")
    print(f"    Retrieval Pipeline: ")
    for search in cfg.retrieval.search.searches:
        print(f"      - {search.type.value}")
    print(f"    Reranker: {cfg.retrieval.rerank.type.value}")
    print(f"    Generation: {cfg.generation.config['model']}")

Loaded 3 RAG pipeline configurations:
  - covidqa_biomedical_multiquery_v1
    Chunking: token
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: qwen/qwen3-32b
  - covidqa_multiquery_hybrid
    Chunking: semantic
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.1-8b-instant
  - covidqa_multiquery_hybrid_v2
    Chunking: semantic
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile

## 7. Run Experiments

Run all RAG configurations on the loaded data. Each config will:
1. Build a vector index from the documents
2. Run queries against the index
3. Generate responses
4. Evaluate using TRACe metrics

Results are returned as PipelineRunResult objects.

In [7]:
# Run experiments

print(f"Running {len(configs)} configurations from {experiment_config.start_index} to {experiment_config.end_index} queries...")
print(f"Parallel mode: {experiment_config.parallel}")

runs = runner.run(documents, raw_data)

print(f"\n✅ Experiments completed!")
print(f"  Ran {len(runs)} configurations")

for run in runs:
    print(f"  - {run['config'].name}: {run['total_written']} queries")

Running 3 configurations from 0 to 246 queries...
Parallel mode: False
Loading embedding model: pritamdeka/S-PubMedBert-MS-MARCO

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 57983.08it/s]

Loading reranker model: BAAI/bge-reranker-v2-gemma

Loading weights: 100%|██████████| 164/164 [00:00<00:00, 4125.38it/s]

Progress: 246/246 (100.0%) | QPS: 231.31 | ETA: 0s | Elapsed: 1s0s
Loading embedding model: BAAI/bge-large-en-v1.5

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 6896.79it/s]

Loading reranker model: BAAI/bge-reranker-v2-m3

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 1708.30it/s]

Progress: 246/246 (100.0%) | QPS: 241.88 | ETA: 0s | Elapsed: 1s 0s
Progress: 246/246 (100.0%) | QPS: 244.55 | ETA: 0s | Elapsed: 1s: 0s

✅ Experiments completed!
  Ran 3 configurations
  - covidqa_biomedical_multiquery_v1: 246 queries
  - covidqa_multiquery_hybrid: 246 queries
  - covidqa_multiquery_hybrid_v2: 246 queries

## 7b. Evaluate Existing JSONL Files

Run offline evaluation on already-generated JSONL files.
Uses experiment-level evaluation config — all configs are scored with the same judge model.

- `parallel_runs=True` — evaluate multiple configs simultaneously
- `parallel_config_run=True` — evaluate records within each config in parallel

In [8]:
# Discover all configs and build run dicts from existing JSONL files
configs = runner.load_configs()
runs = []
for cfg in configs:
    jsonl_path = experiment_config.temp_dir / f"{cfg.name}.jsonl"
    if jsonl_path.exists():
        runs.append({"config_name": cfg.name, "config": cfg, "jsonl_path": jsonl_path})
    else:
        print(f"  Skipping {cfg.name} — no JSONL found")

print(f"Found {len(runs)} configs with JSONL files")

# Evaluate all configs: parallel across configs + parallel within each config
eval_runs = runner.evaluate_runs(
    runs,
    parallel_runs=True,
    parallel_config_run=True,
)

# Use eval_runs for report generation downstream
runs = eval_runs
print(f"\n✅ Evaluation complete: {len(eval_runs)} configs")

Found 3 configs with JSONL files
Using key #0: ****fyaJ
Using key #0: ****fyaJ

Record 30 evaluation failed: Expecting ',' delimiter: line 237 column 6 (char 6635)

Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
================================================================================
429 on ****fyaJ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11901, Requested 3337. Please try again in 16.189999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:53:00 GMT
  content-type: application/json
  content-length: 391
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 17
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 995
  x-ratelimit-remaining-tokens: 99
  x-ratelimit-reset-requests: 7m12s
  x-ratelimit-reset-tokens: 59.505s
  x-request-id: req_01kx7rb3e0e7tvrm23v216vwex
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a19533b5dfed4543-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11901, Requested 3337. Please try again in 16.189999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 17
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'fyaJ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 16, 484288), 'requests': 6, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
================================================================================
429 on ****Cf0x
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10445, Requested 3131. Please try again in 7.88s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:53:28 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 8
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 996
  x-ratelimit-remaining-tokens: 1555
  x-ratelimit-reset-requests: 5m45.6s
  x-ratelimit-reset-tokens: 52.224s
  x-request-id: req_01kx7rbyx8ff2tvdy9rpyevrd5
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953465caa0d5f0-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10445, Requested 3131. Please try again in 7.88s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 8
{'provider': 'groq', 'current_index': 1, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 16, 484288), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 35, 620682), 'requests': 6, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
================================================================================
429 on ****zgga
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11732, Requested 1733. Please try again in 7.325s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:53:53 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 8
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 995
  x-ratelimit-remaining-tokens: 268
  x-ratelimit-reset-requests: 7m12s
  x-ratelimit-reset-tokens: 58.66s
  x-request-id: req_01kx7rcqgae0ysxa54105v79j6
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a19535032eb74901-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11732, Requested 1733. Please try again in 7.325s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 8
{'provider': 'groq', 'current_index': 2, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 16, 484288), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 35, 620682), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 0, 805791), 'requests': 7, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
================================================================================
429 on ****7dyb
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9461, Requested 3411. Please try again in 4.36s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:54:24 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 5
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 996
  x-ratelimit-remaining-tokens: 2539
  x-ratelimit-reset-requests: 5m45.6s
  x-ratelimit-reset-tokens: 47.305s
  x-request-id: req_01kx7rdnekefyrcwzc8732j5pd
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a19535c2cac03b40-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9461, Requested 3411. Please try again in 4.36s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 5
{'provider': 'groq', 'current_index': 3, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 16, 484288), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 35, 620682), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 0, 805791), 'requests': 7, 'successes': 6, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 28, 469824), 'requests': 6, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
================================================================================
429 on ****tmVo
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9487, Requested 2813. Please try again in 1.5s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:55:01 GMT
  content-type: application/json
  content-length: 381
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 2
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 996
  x-ratelimit-remaining-tokens: 2513
  x-ratelimit-reset-requests: 5m45.6s
  x-ratelimit-reset-tokens: 47.434s
  x-request-id: req_01kx7reshjec2r97vtva00y65d
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a19536a9dadedeba-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9487, Requested 2813. Please try again in 1.5s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 2
{'provider': 'groq', 'current_index': 4, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 16, 484288), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 35, 620682), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 0, 805791), 'requests': 7, 'successes': 6, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 28, 469824), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 25, 2, 429518), 'requests': 6, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
================================================================================
429 on ****Z8Yy
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10071, Requested 3420. Please try again in 7.455s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:55:27 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 8
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 996
  x-ratelimit-remaining-tokens: 1929
  x-ratelimit-reset-requests: 5m45.6s
  x-ratelimit-reset-tokens: 50.355s
  x-request-id: req_01kx7rfjzgfvhs12avmc75trqd
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a195374c9d11518f-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10071, Requested 3420. Please try again in 7.455s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 8
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 16, 484288), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 35, 620682), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 0, 805791), 'requests': 7, 'successes': 6, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 28, 469824), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 25, 2, 429518), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'Z8Yy', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 25, 34, 472954), 'requests': 5, 'successes': 3, 'failures': 1, '429s': 1}]}
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
================================================================================
429 on ****fyaJ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11113, Requested 3514. Please try again in 13.135s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:55:44 GMT
  content-type: application/json
  content-length: 385
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 14
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 991
  x-ratelimit-remaining-tokens: 887
  x-ratelimit-reset-requests: 12m57.599s
  x-ratelimit-reset-tokens: 55.565s
  x-request-id: req_01kx7rg3t0egwsmgg4pmc2pegc
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a19537b8498c3f47-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11113, Requested 3514. Please try again in 13.135s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 14
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'fyaJ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 25, 57, 705919), 'requests': 12, 'successes': 9, 'failures': 2, '429s': 2}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 23, 35, 620682), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 0, 805791), 'requests': 7, 'successes': 6, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 24, 28, 469824), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 25, 2, 429518), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 25, 34, 472954), 'requests': 5, 'successes': 4, 'failures': 1, '429s': 1}]}
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
================================================================================
429 on ****Cf0x
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11630, Requested 3193. Please try again in 14.114999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:56:08 GMT
  content-type: application/json
  content-length: 391
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 15
  server: cloudflare
  vary: Origin

Record 183 evaluation failed: Expecting ',' delimiter: line 232 column 6 (char 7266)

Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
================================================================================
429 on ****Z8Yy
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11445, Requested 3037. Please try again in 12.41s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:57:43 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 13
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 992
  x-ratelimit-remaining-tokens: 555
  x-ratelimit-reset-requests: 11m31.2s
  x-ratelimit-reset-tokens: 57.225s
  x-request-id: req_01kx7rkr6jezj89sg05t75wh8b
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953aa12a096efb-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11445, Requested 3037. Please try again in 12.41s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 13
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 25, 57, 705919), 'requests': 12, 'successes': 10, 'failures': 2, '429s': 2}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 22, 541694), 'requests': 13, 'successes': 11, 'failures': 2, '429s': 2}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 24, 359198), 'requests': 14, 'successes': 12, 'failures': 2, '429s': 2}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 43, 560586), 'requests': 13, 'successes': 11, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 23, 932599), 'requests': 14, 'successes': 12, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 55, 595002), 'requests': 11, 'successes': 8, 'failures': 2, '429s': 2}]}
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ

Record 189 evaluation failed: Expecting ',' delimiter: line 144 column 6 (char 7532)

Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
================================================================================
429 on ****fyaJ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10744, Requested 3509. Please try again in 11.265s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:58:12 GMT
  content-type: application/json
  content-length: 385
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 12
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 986
  x-ratelimit-remaining-tokens: 1256
  x-ratelimit-reset-requests: 20m9.6s
  x-ratelimit-reset-tokens: 53.72s
  x-request-id: req_01kx7rmky6f638617e8re7ytp5
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953b52bb9e3f60-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10744, Requested 3509. Please try again in 11.265s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 12
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'fyaJ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 22, 996436), 'requests': 20, 'successes': 16, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 22, 541694), 'requests': 13, 'successes': 11, 'failures': 2, '429s': 2}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 24, 359198), 'requests': 14, 'successes': 12, 'failures': 2, '429s': 2}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 43, 560586), 'requests': 13, 'successes': 11, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 23, 932599), 'requests': 14, 'successes': 12, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 55, 595002), 'requests': 11, 'successes': 9, 'failures': 2, '429s': 2}]}
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
================================================================================
429 on ****Cf0x
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11839, Requested 3084. Please try again in 14.615s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:58:31 GMT
  content-type: application/json
  content-length: 385
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 15
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 985
  x-ratelimit-remaining-tokens: 161
  x-ratelimit-reset-requests: 21m36s
  x-ratelimit-reset-tokens: 59.195s
  x-request-id: req_01kx7rn6hkf68b0b8gv3747709
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953bc9cfd93b13-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11839, Requested 3084. Please try again in 14.615s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 15
{'provider': 'groq', 'current_index': 1, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 22, 996436), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 45, 47782), 'requests': 20, 'successes': 16, 'failures': 3, '429s': 3}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 24, 359198), 'requests': 14, 'successes': 12, 'failures': 2, '429s': 2}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 43, 560586), 'requests': 13, 'successes': 11, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 23, 932599), 'requests': 14, 'successes': 12, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 55, 595002), 'requests': 11, 'successes': 9, 'failures': 2, '429s': 2}]}
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
================================================================================
429 on ****zgga
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11926, Requested 2222. Please try again in 10.74s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:58:45 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 11
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 984
  x-ratelimit-remaining-tokens: 74
  x-ratelimit-reset-requests: 23m2.4s
  x-ratelimit-reset-tokens: 59.63s
  x-request-id: req_01kx7rnkyrfa7a09wncnbz8est
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953c1f9bb83b37-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11926, Requested 2222. Please try again in 10.74s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 11
{'provider': 'groq', 'current_index': 2, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 22, 996436), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 45, 47782), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'zgga', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 54, 781849), 'requests': 21, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 26, 43, 560586), 'requests': 13, 'successes': 11, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 23, 932599), 'requests': 14, 'successes': 12, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 55, 595002), 'requests': 11, 'successes': 9, 'failures': 2, '429s': 2}]}
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
================================================================================
429 on ****7dyb
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10960, Requested 2969. Please try again in 9.645s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:59:12 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 10
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 985
  x-ratelimit-remaining-tokens: 1040
  x-ratelimit-reset-requests: 21m36s
  x-ratelimit-reset-tokens: 54.8s
  x-request-id: req_01kx7rpenvem78bpexjzqpsqeq
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953ccaad5477fc-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10960, Requested 2969. Please try again in 9.645s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 10
{'provider': 'groq', 'current_index': 3, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 22, 996436), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 45, 47782), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 54, 781849), 'requests': 21, 'successes': 18, 'failures': 3, '429s': 3}, {'key_suffix': '7dyb', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 29, 21, 143111), 'requests': 21, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 23, 932599), 'requests': 14, 'successes': 12, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 55, 595002), 'requests': 11, 'successes': 9, 'failures': 2, '429s': 2}]}
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
================================================================================
429 on ****tmVo
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10301, Requested 3280. Please try again in 7.905s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 04:59:42 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 8
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 983
  x-ratelimit-remaining-tokens: 1699
  x-ratelimit-reset-requests: 24m28.8s
  x-ratelimit-reset-tokens: 51.505s
  x-request-id: req_01kx7rqc7peph8f1rkf667p89g
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953d87dc08ff7b-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10301, Requested 3280. Please try again in 7.905s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 8
{'provider': 'groq', 'current_index': 4, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 22, 996436), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 45, 47782), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 54, 781849), 'requests': 21, 'successes': 18, 'failures': 3, '429s': 3}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 29, 21, 143111), 'requests': 21, 'successes': 18, 'failures': 3, '429s': 3}, {'key_suffix': 'tmVo', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 29, 49, 409117), 'requests': 23, 'successes': 19, 'failures': 3, '429s': 3}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 27, 55, 595002), 'requests': 11, 'successes': 9, 'failures': 2, '429s': 2}]}
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
================================================================================
429 on ****Z8Yy
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9034, Requested 3354. Please try again in 1.94s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 05:00:00 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 2
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 988
  x-ratelimit-remaining-tokens: 2966
  x-ratelimit-reset-requests: 17m16.8s
  x-ratelimit-reset-tokens: 45.17s
  x-request-id: req_01kx7rqxxgeqra16w3djadcz3j
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953df8fdc12e7d-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9034, Requested 3354. Please try again in 1.94s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 2
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 22, 996436), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 45, 47782), 'requests': 20, 'successes': 17, 'failures': 3, '429s': 3}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 28, 54, 781849), 'requests': 21, 'successes': 18, 'failures': 3, '429s': 3}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 29, 21, 143111), 'requests': 21, 'successes': 18, 'failures': 3, '429s': 3}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 29, 49, 409117), 'requests': 23, 'successes': 20, 'failures': 3, '429s': 3}, {'key_suffix': 'Z8Yy', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 30, 1, 513982), 'requests': 18, 'successes': 14, 'failures': 3, '429s': 3}]}
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
================================================================================
429 on ****fyaJ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9553, Requested 3331. Please try again in 4.42s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 05:00:44 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 5
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 978
  x-ratelimit-remaining-tokens: 2447
  x-ratelimit-reset-requests: 31m40.8s
  x-ratelimit-reset-tokens: 47.765s
  x-request-id: req_01kx7rs8vffr3s5fp3yp175kzs
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a1953f0bce613fe7-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9553, Requested 3331. Please try again in 4.42s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 5

Record 14 evaluation failed: All Groq API keys are currently rate limited.
Record 21 evaluation failed: All Groq API keys are currently rate limited.
Record 22 evaluation failed: All Groq API keys are currently rate limited.
Record 23 evaluation failed: All Groq API keys are currently rate limited.
Record 24 evaluation failed: All Groq API keys are currently rate limited.
Record 25 evaluation failed: All Groq API keys are currently rate limited.
Record 26 evaluation failed: All Groq API keys are currently rate limited.
Record 27 evaluation failed: All Groq API keys are currently rate limited.
Record 28 evaluation failed: All Groq API keys are currently rate limited.
Record 29 evaluation failed: All Groq API keys are currently rate limited.
Record 30 evaluation failed: All Groq API keys are currently rate limited.
Record 31 evaluation failed: All Groq API keys are currently rate limited.
Record 32 evaluation failed: All Groq API keys are currently rate limited.
Record 33 evaluation failed: All Groq API keys are currently rate limited.
Record 34 evaluation failed: All Groq API keys are currently rate limited.
Record 35 evaluation failed: All Groq API keys are currently rate limited.
Record 36 evaluation failed: All Groq API keys are currently rate limited.
Record 37 evaluation failed: All Groq API keys are currently rate limited.
Record 38 evaluation failed: All Groq API keys are currently rate limited.
Record 39 evaluation failed: All Groq API keys are currently rate limited.
Record 40 evaluation failed: All Groq API keys are currently rate limited.
Record 41 evaluation failed: All Groq API keys are currently rate limited.
Record 42 evaluation failed: All Groq API keys are currently rate limited.
Record 43 evaluation failed: All Groq API keys are currently rate limited.
Record 44 evaluation failed: All Groq API keys are currently rate limited.
Record 45 evaluation failed: All Groq API keys are currently rate limited.
Record 46 evaluation failed: All Groq API keys are currently rate limited.
Record 47 evaluation failed: All Groq API keys are currently rate limited.
Record 48 evaluation failed: All Groq API keys are currently rate limited.
Record 49 evaluation failed: All Groq API keys are currently rate limited.
Record 50 evaluation failed: All Groq API keys are currently rate limited.
Record 51 evaluation failed: All Groq API keys are currently rate limited.
Record 52 evaluation failed: All Groq API keys are currently rate limited.
Record 53 evaluation failed: All Groq API keys are currently rate limited.
Record 54 evaluation failed: All Groq API keys are currently rate limited.
Record 55 evaluation failed: All Groq API keys are currently rate limited.
Record 56 evaluation failed: All Groq API keys are currently rate limited.
Record 57 evaluation failed: All Groq API keys are currently rate limited.
Record 58 evaluation failed: All Groq API keys are currently rate limited.
Record 59 evaluation failed: All Groq API keys are currently rate limited.
Record 60 evaluation failed: All Groq API keys are currently rate limited.
Record 61 evaluation failed: All Groq API keys are currently rate limited.
Record 62 evaluation failed: All Groq API keys are currently rate limited.
Record 63 evaluation failed: All Groq API keys are currently rate limited.
Record 64 evaluation failed: All Groq API keys are currently rate limited.
Record 65 evaluation failed: All Groq API keys are currently rate limited.
Record 66 evaluation failed: All Groq API keys are currently rate limited.
Record 67 evaluation failed: All Groq API keys are currently rate limited.
Record 68 evaluation failed: All Groq API keys are currently rate limited.
Record 69 evaluation failed: All Groq API keys are currently rate limited.
Record 70 evaluation failed: All Groq API keys are currently rate limited.
Record 71 evaluation failed: All Groq API keys are currently rate limited.
Record 72 evaluation failed: All Groq API keys are currently rate limited.
Record 73 evaluation failed: All Groq API keys are currently rate limited.
Record 74 evaluation failed: All Groq API keys are currently rate limited.
Record 75 evaluation failed: All Groq API keys are currently rate limited.
Record 76 evaluation failed: All Groq API keys are currently rate limited.
Record 77 evaluation failed: All Groq API keys are currently rate limited.
Record 78 evaluation failed: All Groq API keys are currently rate limited.
Record 79 evaluation failed: All Groq API keys are currently rate limited.
Record 80 evaluation failed: All Groq API keys are currently rate limited.
Record 81 evaluation failed: All Groq API keys are currently rate limited.
Record 82 evaluation failed: All Groq API keys are currently rate limited.
Record 83 evaluation failed: All Groq API keys are currently rate limited.
Record 84 evaluation failed: All Groq API keys are currently rate limited.
Record 85 evaluation failed: All Groq API keys are currently rate limited.
Record 86 evaluation failed: All Groq API keys are currently rate limited.
Record 87 evaluation failed: All Groq API keys are currently rate limited.
Record 88 evaluation failed: All Groq API keys are currently rate limited.
Record 89 evaluation failed: All Groq API keys are currently rate limited.
Record 90 evaluation failed: All Groq API keys are currently rate limited.
Record 91 evaluation failed: All Groq API keys are currently rate limited.
Record 92 evaluation failed: All Groq API keys are currently rate limited.
Record 93 evaluation failed: All Groq API keys are currently rate limited.
Record 94 evaluation failed: All Groq API keys are currently rate limited.
Record 95 evaluation failed: All Groq API keys are currently rate limited.
Record 96 evaluation failed: All Groq API keys are currently rate limited.
Record 97 evaluation failed: All Groq API keys are currently rate limited.
Record 98 evaluation failed: All Groq API keys are currently rate limited.
Record 99 evaluation failed: All Groq API keys are currently rate limited.
Record 100 evaluation failed: All Groq API keys are currently rate limited.
Record 101 evaluation failed: All Groq API keys are currently rate limited.
Record 102 evaluation failed: All Groq API keys are currently rate limited.
Record 103 evaluation failed: All Groq API keys are currently rate limited.
Record 104 evaluation failed: All Groq API keys are currently rate limited.
Record 105 evaluation failed: All Groq API keys are currently rate limited.
Record 106 evaluation failed: All Groq API keys are currently rate limited.
Record 107 evaluation failed: All Groq API keys are currently rate limited.
Record 108 evaluation failed: All Groq API keys are currently rate limited.
Record 109 evaluation failed: All Groq API keys are currently rate limited.
Record 110 evaluation failed: All Groq API keys are currently rate limited.
Record 111 evaluation failed: All Groq API keys are currently rate limited.
Record 112 evaluation failed: All Groq API keys are currently rate limited.
Record 113 evaluation failed: All Groq API keys are currently rate limited.
Record 114 evaluation failed: All Groq API keys are currently rate limited.
Record 115 evaluation failed: All Groq API keys are currently rate limited.
Record 116 evaluation failed: All Groq API keys are currently rate limited.
Record 117 evaluation failed: All Groq API keys are currently rate limited.
Record 118 evaluation failed: All Groq API keys are currently rate limited.
Record 119 evaluation failed: All Groq API keys are currently rate limited.
Record 120 evaluation failed: All Groq API keys are currently rate limited.
Record 121 evaluation failed: All Groq API keys are currently rate limited.
Record 122 evaluation failed: All Groq API keys are currently rate limited.
Record 123 evaluation failed: All Groq API keys are currently rate limited.
Record 124 evaluation failed: All Groq API keys are currently rate limited.
Record 125 evaluation failed: All Groq API keys are currently rate limited.
Record 126 evaluation failed: All Groq API keys are currently rate limited.
Record 127 evaluation failed: All Groq API keys are currently rate limited.
Record 128 evaluation failed: All Groq API keys are currently rate limited.
Record 129 evaluation failed: All Groq API keys are currently rate limited.
Record 130 evaluation failed: All Groq API keys are currently rate limited.
Record 131 evaluation failed: All Groq API keys are currently rate limited.
Record 132 evaluation failed: All Groq API keys are currently rate limited.
Record 133 evaluation failed: All Groq API keys are currently rate limited.
Record 134 evaluation failed: All Groq API keys are currently rate limited.
Record 135 evaluation failed: All Groq API keys are currently rate limited.
Record 136 evaluation failed: All Groq API keys are currently rate limited.
Record 137 evaluation failed: All Groq API keys are currently rate limited.
Record 138 evaluation failed: All Groq API keys are currently rate limited.
Record 139 evaluation failed: All Groq API keys are currently rate limited.
Record 140 evaluation failed: All Groq API keys are currently rate limited.
Record 141 evaluation failed: All Groq API keys are currently rate limited.
Record 142 evaluation failed: All Groq API keys are currently rate limited.
Record 143 evaluation failed: All Groq API keys are currently rate limited.
Record 144 evaluation failed: All Groq API keys are currently rate limited.
Record 145 evaluation failed: All Groq API keys are currently rate limited.
Record 146 evaluation failed: All Groq API keys are currently rate limited.
Record 147 evaluation failed: All Groq API keys are currently rate limited.
Record 148 evaluation failed: All Groq API keys are currently rate limited.
Record 149 evaluation failed: All Groq API keys are currently rate limited.
Record 150 evaluation failed: All Groq API keys are currently rate limited.
Record 151 evaluation failed: All Groq API keys are currently rate limited.
Record 152 evaluation failed: All Groq API keys are currently rate limited.
Record 153 evaluation failed: All Groq API keys are currently rate limited.
Record 154 evaluation failed: All Groq API keys are currently rate limited.
Record 155 evaluation failed: All Groq API keys are currently rate limited.
Record 156 evaluation failed: All Groq API keys are currently rate limited.
Record 157 evaluation failed: All Groq API keys are currently rate limited.
Record 158 evaluation failed: All Groq API keys are currently rate limited.
Record 159 evaluation failed: All Groq API keys are currently rate limited.
Record 160 evaluation failed: All Groq API keys are currently rate limited.
Record 161 evaluation failed: All Groq API keys are currently rate limited.
Record 162 evaluation failed: All Groq API keys are currently rate limited.
Record 163 evaluation failed: All Groq API keys are currently rate limited.
Record 164 evaluation failed: All Groq API keys are currently rate limited.
Record 165 evaluation failed: All Groq API keys are currently rate limited.
Record 166 evaluation failed: All Groq API keys are currently rate limited.
Record 167 evaluation failed: All Groq API keys are currently rate limited.
Record 168 evaluation failed: All Groq API keys are currently rate limited.
Record 169 evaluation failed: All Groq API keys are currently rate limited.
Record 170 evaluation failed: All Groq API keys are currently rate limited.
Record 171 evaluation failed: All Groq API keys are currently rate limited.
Record 172 evaluation failed: All Groq API keys are currently rate limited.
Record 173 evaluation failed: All Groq API keys are currently rate limited.
Record 174 evaluation failed: All Groq API keys are currently rate limited.
Record 175 evaluation failed: All Groq API keys are currently rate limited.
Record 176 evaluation failed: All Groq API keys are currently rate limited.
Record 177 evaluation failed: All Groq API keys are currently rate limited.
Record 178 evaluation failed: All Groq API keys are currently rate limited.
Record 179 evaluation failed: All Groq API keys are currently rate limited.
Record 180 evaluation failed: All Groq API keys are currently rate limited.
Record 181 evaluation failed: All Groq API keys are currently rate limited.
Record 182 evaluation failed: All Groq API keys are currently rate limited.
Record 183 evaluation failed: All Groq API keys are currently rate limited.
Record 184 evaluation failed: All Groq API keys are currently rate limited.
Record 185 evaluation failed: All Groq API keys are currently rate limited.
Record 186 evaluation failed: All Groq API keys are currently rate limited.
Record 187 evaluation failed: All Groq API keys are currently rate limited.
Record 188 evaluation failed: All Groq API keys are currently rate limited.
Record 189 evaluation failed: All Groq API keys are currently rate limited.
Record 190 evaluation failed: All Groq API keys are currently rate limited.
Record 191 evaluation failed: All Groq API keys are currently rate limited.
Record 192 evaluation failed: All Groq API keys are currently rate limited.
Record 193 evaluation failed: All Groq API keys are currently rate limited.
Record 194 evaluation failed: All Groq API keys are currently rate limited.
Record 195 evaluation failed: All Groq API keys are currently rate limited.
Record 196 evaluation failed: All Groq API keys are currently rate limited.
Record 197 evaluation failed: All Groq API keys are currently rate limited.
Record 198 evaluation failed: All Groq API keys are currently rate limited.
Record 199 evaluation failed: All Groq API keys are currently rate limited.
Record 200 evaluation failed: All Groq API keys are currently rate limited.
Record 201 evaluation failed: All Groq API keys are currently rate limited.
Record 202 evaluation failed: All Groq API keys are currently rate limited.
Record 203 evaluation failed: All Groq API keys are currently rate limited.
Record 204 evaluation failed: All Groq API keys are currently rate limited.
Record 205 evaluation failed: All Groq API keys are currently rate limited.
Record 206 evaluation failed: All Groq API keys are currently rate limited.
Record 207 evaluation failed: All Groq API keys are currently rate limited.
Record 208 evaluation failed: All Groq API keys are currently rate limited.
Record 209 evaluation failed: All Groq API keys are currently rate limited.
Record 210 evaluation failed: All Groq API keys are currently rate limited.
Record 211 evaluation failed: All Groq API keys are currently rate limited.
Record 212 evaluation failed: All Groq API keys are currently rate limited.
Record 213 evaluation failed: All Groq API keys are currently rate limited.
Record 214 evaluation failed: All Groq API keys are currently rate limited.
Record 215 evaluation failed: All Groq API keys are currently rate limited.
Record 216 evaluation failed: All Groq API keys are currently rate limited.
Record 217 evaluation failed: All Groq API keys are currently rate limited.
Record 218 evaluation failed: All Groq API keys are currently rate limited.
Record 219 evaluation failed: All Groq API keys are currently rate limited.
Record 220 evaluation failed: All Groq API keys are currently rate limited.
Record 221 evaluation failed: All Groq API keys are currently rate limited.
Record 222 evaluation failed: All Groq API keys are currently rate limited.
Record 223 evaluation failed: All Groq API keys are currently rate limited.
Record 224 evaluation failed: All Groq API keys are currently rate limited.
Record 225 evaluation failed: All Groq API keys are currently rate limited.
Record 226 evaluation failed: All Groq API keys are currently rate limited.
Record 227 evaluation failed: All Groq API keys are currently rate limited.
Record 228 evaluation failed: All Groq API keys are currently rate limited.
Record 229 evaluation failed: All Groq API keys are currently rate limited.
Record 230 evaluation failed: All Groq API keys are currently rate limited.
Record 231 evaluation failed: All Groq API keys are currently rate limited.
Record 232 evaluation failed: All Groq API keys are currently rate limited.
Record 233 evaluation failed: All Groq API keys are currently rate limited.
Record 234 evaluation failed: All Groq API keys are currently rate limited.
Record 235 evaluation failed: All Groq API keys are currently rate limited.
Record 236 evaluation failed: All Groq API keys are currently rate limited.
Record 237 evaluation failed: All Groq API keys are currently rate limited.
Record 238 evaluation failed: All Groq API keys are currently rate limited.
Record 239 evaluation failed: All Groq API keys are currently rate limited.
Record 240 evaluation failed: All Groq API keys are currently rate limited.
Record 241 evaluation failed: All Groq API keys are currently rate limited.
Record 242 evaluation failed: All Groq API keys are currently rate limited.
Record 243 evaluation failed: All Groq API keys are currently rate limited.
Record 244 evaluation failed: All Groq API keys are currently rate limited.
Record 245 evaluation failed: All Groq API keys are currently rate limited.
Record 246 evaluation failed: All Groq API keys are currently rate limited.

================================================================================
429 on ****Z8Yy
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10134, Requested 2297. Please try again in 2.155s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sat, 11 Jul 2026 05:06:26 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 3
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 955
  x-ratelimit-remaining-tokens: 1866
  x-ratelimit-reset-requests: 1h4m48s
  x-ratelimit-reset-tokens: 50.67s
  x-request-id: req_01kx7s3p83fe6awyara0mgn3qr
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a19547618be5b13b-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10134, Requested 2297. Please try again in 2.155s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 3
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'fyaJ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 58, 47, 46367), 'requests': 48, 'successes': 42, 'failures': 6, '429s': 6}, {'key_suffix': 'Cf0x', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 54, 56, 946010), 'requests': 53, 'successes': 46, 'failures': 7, '429s': 7}, {'key_suffix': 'zgga', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 53, 50, 640409), 'requests': 58, 'successes': 51, 'failures': 7, '429s': 7}, {'key_suffix': '7dyb', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 40, 48, 648221), 'requests': 57, 'successes': 50, 'failures': 7, '429s': 7}, {'key_suffix': 'tmVo', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 43, 59, 919801), 'requests': 52, 'successes': 46, 'failures': 6, '429s': 6}, {'key_suffix': 'Z8Yy', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 11, 10, 36, 27, 867521), 'requests': 57, 'successes': 49, 'failures': 7, '429s': 7}]}
[covidqa_multiquery_hybrid_v2] Evaluation complete → temp/covidqa_multiquery_hybrid_v2.jsonl

✅ Evaluation complete: 3 configs

## 8. Generate Reports

Generate detailed reports for each configuration including:
- Per-query table with all TRACe scores
- Aggregate statistics (mean, std, MAE)
- Comparison with ground truth

In [9]:
# Generate reports
print("Generating reports...")
reports = runner.generate_reports(runs)

print(f"\n✅ Reports generated!")
print(f"  Saved to: {experiment_config.report_dir}")

Generating reports...

✅ Reports generated!
  Saved to: reports

## 9. Display Reports

Display the generated reports with per-query and aggregate metrics.

In [10]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")
    
    # Display per-query results
    print("\nPer-Query Results:")
    display(report.display())

================================================================================
Configuration: covidqa_biomedical_multiquery_v1
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `covidqa_biomedical_multiquery_v1`

**name**: covidqa_biomedical_multiquery_v1  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'token', 'config': {'max_tokens': 120, 'overlap_tokens': 20}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'pritamdeka/S-PubMedBert-MS-MARCO', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 80}}, {'type': 'sparse', 'config': {'top_k': 80}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'model': 'qwen/qwen3-32b', 'num_queries': 3, 'temperature': 0.0, 'max_tokens': 192}}, 'fusion': {'type': 'rrf', 'config': {'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-gemma', 'top_k': 15}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'qwen/qwen3-32b', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an expert biomedical question answering assistant.\n\nAnswer ONLY using the retrieved context.\n\nDo not use prior knowledge.\n\nIf the answer cannot be determined from the retrieved context,\nreply exactly:\n\n"Insufficient evidence in retrieved context."\n\nKeep answers concise, factual and evidence-based.\n', 'user_prompt': 'Retrieved Context\n-----------------\n{context}\n-----------------\n\nQuestion:\n{query}\n\nAnswer using only the retrieved context.'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': 'cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Which viruses may not cause prolonged inflammation due to strong induction o...,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking which viruses may not cause pro...",0.24,0.4118,-0.1718,0.36,0.1765,0.1835,0.8333,0.4286,0.4047,0.0,0.0,0.0
1,When was the first case of COVID-19 identified?,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking when the first case of COVID-19...",0.04,0.2692,-0.2292,0.04,0.0769,-0.0369,1.0000,0.2857,0.7143,0.0,1.0,-1.0
2,How many antigens could be detected by Liew's multiplex ELISA test?,"[{'text': '', 'title': '', 'content': 'Hantaan virus antigens in the superna...","<think>\nOkay, let's see. The user is asking about how many antigens could b...",0.28,0.1250,0.1550,0.28,0.0625,0.2175,0.4286,0.5000,-0.0714,0.0,1.0,-1.0
3,What is the structure of Hantaan virus?,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking about the structure of the Hant...",0.28,0.3000,-0.0200,1.00,0.3000,0.7000,1.0000,1.0000,0.0000,0.0,1.0,-1.0
4,How many people did SARS-CoV infect?,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking how many people SARS-CoV infect...",0.00,0.0667,-0.0667,0.24,0.0667,0.1733,0.0000,1.0000,-1.0000,0.0,1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,What is a conclusion of this report?,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking for a conclusion of ""this repor...",0.00,0.1250,-0.1250,0.20,0.1250,0.0750,0.0000,1.0000,-1.0000,0.0,1.0,-1.0
242,What are the results of filamentous phage immunizations in mice?,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking about the results of filamentou...",0.44,0.2222,0.2178,0.76,0.2222,0.5378,1.0000,0.7500,0.2500,0.0,1.0,-1.0
243,What is marked in green?,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking ""What is marked in green?"" I ne...",0.40,0.1053,0.2947,0.16,0.1053,0.0547,0.4000,1.0000,-0.6000,0.0,1.0,-1.0
244,How can CCR5's effect in HIV-1 transmission be reduced?,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking how to reduce CCR5's effect in ...",0.00,0.2105,-0.2105,0.00,0.1053,-0.1053,0.0000,0.5000,-0.5000,0.0,0.0,0.0
245,What followed the reverse transcription step in the analysis?,"[{'text': '', 'title': '', 'content': 'but close and lengthy exposure appear...","<think>\nOkay, let's see. The user is asking what followed the reverse trans...",0.00,0.1905,-0.1905,1.00,0.1429,0.8571,0.0000,0.7500,-0.7500,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.1197,0.2887,0.2227,0.1684,0.2639
1,utilization_score,0.3524,0.1811,0.3850,0.1288,0.3295
2,completeness_score,0.3069,0.6631,0.3986,0.2940,0.5097
3,adherence_score,0.1358,0.8415,0.3426,0.3652,0.7325

None

================================================================================
Configuration: covidqa_multiquery_hybrid
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `covidqa_multiquery_hybrid`

**name**: covidqa_multiquery_hybrid  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'semantic', 'config': {'max_words': 100, 'overlap_sentences': 2, 'similarity_threshold': 0.75, 'embedding': {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5'}}}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5', 'dimension': 1024}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 1024}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 30}}, {'type': 'sparse', 'config': {'top_k': 30}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'model': 'llama-3.1-8b-instant', 'num_queries': 4, 'temperature': 0.5, 'max_tokens': 256}}, 'fusion': {'type': 'rrf', 'config': {'k': 30}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 10}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.1-8b-instant', 'temperature': 0.2, 'max_tokens': 1024, 'system_prompt': 'You are an expert biomedical question answering assistant.\n\nUse only the supplied context.\nCombine relevant evidence from multiple passages when appropriate.\nIf the answer is unsupported by the retrieved context, clearly state that.\nDo not speculate.\n', 'user_prompt': 'Retrieved Context:\n--------------------\n{context}\n--------------------\n\nQuestion:\n{query}\n\nProduce the most accurate answer supported only by the retrieved context.\n\nAnswer:\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': 'cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Which viruses may not cause prolonged inflammation due to strong induction o...,"[{'text': '', 'title': '', 'content': 'Alveolar macrophages contribute to th...","Based on the retrieved context, it is not explicitly stated which viruses ma...",0.3333,0.4118,-0.0785,0.2667,0.1765,0.0902,0.8000,0.4286,0.3714,0.0,0.0,0.0
1,When was the first case of COVID-19 identified?,"[{'text': '', 'title': '', 'content': 'The first case indicating community t...",The retrieved context does not mention the first case of COVID-19. It discus...,0.0000,0.2692,-0.2692,0.0000,0.0769,-0.0769,0.0000,0.2857,-0.2857,1.0,1.0,0.0
2,How many antigens could be detected by Liew's multiplex ELISA test?,"[{'text': '', 'title': '', 'content': 'Blood spots from 63 participants with...",The retrieved context does not explicitly mention the number of antigens tha...,0.0833,0.1250,-0.0417,0.0833,0.0625,0.0208,1.0000,0.5000,0.5000,0.0,1.0,-1.0
3,What is the structure of Hantaan virus?,"[{'text': '', 'title': '', 'content': 'The clinical presentations may vary a...",The retrieved context does not provide information about the structure of Ha...,0.5000,0.3000,0.2000,0.3571,0.3000,0.0571,0.7143,1.0000,-0.2857,0.0,1.0,-1.0
4,How many people did SARS-CoV infect?,"[{'text': '', 'title': '', 'content': 'This outbreak is estimated to have st...",The retrieved context does not provide information about the number of peopl...,0.4615,0.0667,0.3948,0.0769,0.0667,0.0102,0.1667,1.0000,-0.8333,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,What is a conclusion of this report?,"[{'text': '', 'title': '', 'content': 'There were four potential limitations...","Based on the retrieved context, it appears that there is no single conclusio...",0.5714,0.1250,0.4464,0.7143,0.1250,0.5893,1.0000,1.0000,0.0000,0.0,1.0,-1.0
242,What are the results of filamentous phage immunizations in mice?,"[{'text': '', 'title': '', 'content': 'In our present study, we demonstrated...",There is no information in the retrieved context about the results of filame...,0.4615,0.2222,0.2393,0.1538,0.2222,-0.0684,0.3333,0.7500,-0.4167,1.0,1.0,0.0
243,What is marked in green?,"[{'text': '', 'title': '', 'content': 'DCs are the most potent antigen-prese...",MHC II positive cells are marked in green.,0.1818,0.1053,0.0765,0.0909,0.1053,-0.0144,0.5000,1.0000,-0.5000,1.0,1.0,0.0
244,How can CCR5's effect in HIV-1 transmission be reduced?,"[{'text': '', 'title': '', 'content': 'dpi, as previously observed . Labelin...",The retrieved context does not provide any information about CCR5's effect i...,0.0000,0.2105,-0.2105,0.0000,0.1053,-0.1053,0.0000,0.5000,-0.5000,1.0,0.0,1.0
245,What followed the reverse transcription step in the analysis?,"[{'text': '', 'title': '', 'content': 'Currently, RT-PCR is the most widely ...","Based on the retrieved context, specifically from Document 1 and Document 2,...",0.4444,0.1905,0.2539,0.4444,0.1429,0.3015,1.0000,0.7500,0.2500,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3594,0.2887,0.3022,0.1684,0.2523
1,utilization_score,0.2323,0.1811,0.2194,0.1288,0.1751
2,completeness_score,0.4899,0.6631,0.3712,0.2940,0.3946
3,adherence_score,0.3699,0.8415,0.4828,0.3652,0.5691

None

================================================================================
Configuration: covidqa_multiquery_hybrid_v2
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `covidqa_multiquery_hybrid_v2`

**name**: covidqa_multiquery_hybrid_v2  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'semantic', 'config': {'max_words': 90, 'overlap_sentences': 3, 'similarity_threshold': 0.7, 'embedding': {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5'}}}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5', 'dimension': 1024}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 1024}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 60}}, {'type': 'sparse', 'config': {'top_k': 60}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'model': 'llama-3.1-8b-instant', 'num_queries': 3, 'temperature': 0.0, 'max_tokens': 192}}, 'fusion': {'type': 'rrf', 'config': {'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 15}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an expert biomedical question answering assistant.\n\nAnswer ONLY using the retrieved context.\n\nIf the answer cannot be determined from the retrieved passages,\nreply exactly:\n\n"Insufficient evidence in retrieved context."\n\nDo not use outside medical knowledge.\nPrefer precise, evidence-based answers.\nKeep answers concise.\n', 'user_prompt': 'Retrieved Context\n-----------------\n{context}\n-----------------\n\nQuestion:\n{query}\n\nAnswer using only the retrieved context.'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': 'cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Which viruses may not cause prolonged inflammation due to strong induction o...,"[{'text': '', 'title': '', 'content': 'are also activated directly by patter...",Insufficient evidence in retrieved context.,0.6667,0.4118,0.2549,0.0,0.1765,-0.1765,0.0,0.4286,-0.4286,0.0,0.0,0.0
1,When was the first case of COVID-19 identified?,"[{'text': '', 'title': '', 'content': 'Any declarative claim that is inconsi...",Insufficient evidence in retrieved context.,0.2857,0.2692,0.0165,0.0,0.0769,-0.0769,0.0,0.2857,-0.2857,1.0,1.0,0.0
2,How many antigens could be detected by Liew's multiplex ELISA test?,"[{'text': '', 'title': '', 'content': 'LAIV is administered as a nasal spray...",Insufficient evidence in retrieved context.,0.0000,0.1250,-0.1250,0.0,0.0625,-0.0625,0.0,0.5000,-0.5000,1.0,1.0,0.0
3,What is the structure of Hantaan virus?,"[{'text': '', 'title': '', 'content': 'In recent years, the infection rate o...",Insufficient evidence in retrieved context.,0.3000,0.3000,0.0000,0.0,0.3000,-0.3000,0.0,1.0000,-1.0000,1.0,1.0,0.0
4,How many people did SARS-CoV infect?,"[{'text': '', 'title': '', 'content': 'We detail the first European cases. A...",Insufficient evidence in retrieved context.,0.0556,0.0667,-0.0111,0.0,0.0667,-0.0667,0.0,1.0000,-1.0000,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,What is a conclusion of this report?,"[{'text': '', 'title': '', 'content': 'results.', 'metadata': {'doc_id': 'sa...",Insufficient evidence in retrieved context.,NaN,0.1250,NaN,NaN,0.1250,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
242,What are the results of filamentous phage immunizations in mice?,"[{'text': '', 'title': '', 'content': 'intraperitoneal infections, between 2...",Insufficient evidence in retrieved context.,NaN,0.2222,NaN,NaN,0.2222,NaN,NaN,0.7500,NaN,NaN,1.0,NaN
243,What is marked in green?,"[{'text': '', 'title': '', 'content': 'the trachea, lung, brain, heart, live...",Insufficient evidence in retrieved context.,NaN,0.1053,NaN,NaN,0.1053,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
244,How can CCR5's effect in HIV-1 transmission be reduced?,"[{'text': '', 'title': '', 'content': 'virus . Like NDV, PIV5 has a 3'-to 5'...",Insufficient evidence in retrieved context.,NaN,0.2105,NaN,NaN,0.1053,NaN,NaN,0.5000,NaN,NaN,0.0,NaN
245,What followed the reverse transcription step in the analysis?,"[{'text': '', 'title': '', 'content': 'In the only study to examine the effe...",Insufficient evidence in retrieved context.,NaN,0.1905,NaN,NaN,0.1429,NaN,NaN,0.7500,NaN,NaN,1.0,NaN

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.2874,0.2887,0.2741,0.1684,0.2477
1,utilization_score,0.0000,0.1811,0.0000,0.1288,0.1269
2,completeness_score,0.0000,0.6631,0.0000,0.2940,0.6283
3,adherence_score,0.6842,0.8415,0.4648,0.3652,0.2632

None

## 10. Compare Configurations

Generate a comparison report across all configurations to see which performs best.

In [11]:
# Generate comparison report
print("Generating comparison report...")
comparison = runner.compare()

print(f"\n✅ Comparison report generated!")
print(f"  Saved to: {experiment_config.report_dir}/comparison.csv")

Generating comparison report...

✅ Comparison report generated!
  Saved to: reports/comparison.csv

In [12]:
# Display comparison
print("\nConfiguration Comparison:")
display(comparison.to_dataframe())

Configuration Comparison:

,config_name,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,covidqa_high_recall_hybrid_v2,relevance_score,0.2687,0.2887,0.2600,0.1684,0.2288
1,covidqa_hyde_hybrid,relevance_score,0.2273,0.2887,0.2582,0.1684,0.2374
2,covidqa_multiquery_hybrid,relevance_score,0.3594,0.2887,0.3022,0.1684,0.2523
3,covidqa_multiquery_hybrid_v2,relevance_score,0.2874,0.2887,0.2741,0.1684,0.2477
4,covidqa_biomedical_multiquery_v1,relevance_score,0.1197,0.2887,0.2227,0.1684,0.2639

In [ ]:
from reporting.base import Report


report = Report.from_jsonl(
    "temp/covidqa_high_recall_hybrid_v2.jsonl",
    config_name="covidqa_high_recall_hybrid_v2",
)

report.display()

report.save_json("reports/covidqa_high_recall_hybrid_v2.json")

AttributeError: type object 'Report' has no attribute 'from_jsonl'

Progress: 102/246 (41.5%) | QPS: 0.13 | ETA: 19.2m | Elapsed: 13.6m

## 11. Summary

The ExperimentRunner provides a complete workflow for:

1. **Configuration-driven data loading** - Specify data source in YAML
2. **Automatic parsing** - Documents parsed using configured parser
3. **Multi-config evaluation** - Test multiple RAG configurations
4. **Parallel execution** - Speed up evaluation with parallel runs
5. **Comprehensive reporting** - Per-query and aggregate metrics
6. **Cross-config comparison** - Identify best performing config

### Key Benefits:

- **Reproducible** - Everything configured in YAML
- **Flexible** - Easy to change data source or parser
- **Scalable** - Parallel execution for faster evaluation
- **Comprehensive** - Detailed metrics and comparisons