# Experiment Runner with Automatic Data Loading

This notebook demonstrates the ExperimentRunner which:
1. **Loads experiment configuration from YAML** - including data loading config
2. **Automatically loads and parses data** - using configured loader and parser
3. **Runs multiple RAG configs** - either sequentially or in parallel
4. **Generates detailed reports** - per-query and aggregate metrics
5. **Compares results** - across different configurations

The experiment configuration in YAML specifies:
- Data source (HuggingFace dataset)
- Data parser (e.g., title_passage)
- RAG config directory
- Number of queries to evaluate
- Parallel execution settings

## 1. Setup & Dependencies

In [1]:
get_ipython().system('pip install datasets faiss-cpu sentence-transformers torch groq python-dotenv nltk pandas -q')

zsh:1: /Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/bin/pip: bad interpreter: /Users/adityanarayan/aiml-talentsprint/rag-capstone-project/real-world-rag-system/venv/bin/python: no such file or directory

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python3.11 -m pip install --upgrade pip

## 2. Imports

In [2]:
import os
from dotenv import load_dotenv

from experiment.experiment_config import ExperimentConfig
from experiment.experiment_runner import ExperimentRunner

load_dotenv(override=True)
print("HuggingFace token loaded:", bool(os.getenv("HF_TOKEN")))
print("Groq API key loaded:", bool(os.getenv("GROQ_API_KEY")))

/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

HuggingFace token loaded: True
Groq API key loaded: True

## 3. Load Experiment Configuration

The experiment configuration file specifies:
- **data_loader**: How to load data (HuggingFace with dataset_name, subset, split)
- **data_parser**: How to parse documents (title_passage)
- **config_dir**: Directory containing RAG pipeline configs
- **num_queries**: Number of queries to evaluate
- **parallel**: Whether to run configs in parallel

In [3]:
# Load experiment configuration from YAML
EXPERIMENT_CONFIG_PATH = "experiment_configs/covidqa_experiment.yaml"
experiment_config = ExperimentConfig.load(EXPERIMENT_CONFIG_PATH)

print("Experiment Configuration:")
print(f"  Config Dir:  {experiment_config.config_dir}")
print(f"  Report Dir:  {experiment_config.report_dir}")
print(f"  Cache Dir:   {experiment_config.cache_dir}")
print(f"  Num Queries: {experiment_config.end_index}")
print(f"  Parallel:    {experiment_config.parallel}")
print(f"  Max Workers: {experiment_config.max_workers}")
print(f"\nData Loader:")
print(f"  Type: {experiment_config.data_loader['type']}")
print(f"  Config: {experiment_config.data_loader['config']}")
print(f"\nData Parser:")
print(f"  Type: {experiment_config.data_parser}")

Experiment Configuration:
  Config Dir:  config
  Report Dir:  reports
  Cache Dir:   cache
  Num Queries: 246
  Parallel:    False
  Max Workers: 4

Data Loader:
  Type: huggingface
  Config: {'dataset_name': 'galileo-ai/ragbench', 'subset': 'covidqa', 'split': 'test', 'limit': 246}

Data Parser:
  Type: title_passage

## 4. Initialize Experiment Runner

The ExperimentRunner will:
- Create report directory if it doesn't exist
- Load RAG configs from the specified directory
- Load and parse data automatically based on YAML config

In [4]:
# Initialize experiment runner
runner = ExperimentRunner(experiment_config)
print("ExperimentRunner initialized")

ExperimentRunner initialized

import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")
    
    # Display per-query results
    print("\nPer-Query Results:")
    display(report.sections[0].per_query)
    
    # Display aggregate statistics
    print("\nAggregate Statistics:")
    display(report.sections[0].summary)

In [5]:
# Load data automatically based on YAML configuration
print("Loading data based on experiment configuration...")
documents, raw_data = runner.load_data()

print(f"\n✅ Data loaded successfully!")
print(f"  Documents: {len(documents)} parsed documents")
print(f"  Raw Data:  {len(raw_data)} samples")

# Inspect first sample
first_sample = raw_data[0]
print(f"\nFirst Sample:")
print(f"  Question: {first_sample['question'][:100]}...")
print(f"  Documents: {len(first_sample['documents'])}")

Loading data based on experiment configuration...
Loading HuggingFace dataset: galileo-ai/ragbench/covidqa (test)...
Loaded 246 samples

✅ Data loaded successfully!
  Documents: 984 parsed documents
  Raw Data:  246 samples

First Sample:
  Question: Which viruses may not cause prolonged inflammation due to strong induction of antiviral clearance?...
  Documents: 4

## 6. Load RAG Pipeline Configs

Load all RAG pipeline configurations from the config directory specified in the experiment config.

In [6]:
# Load RAG pipeline configs
configs = runner.load_configs()

print(f"Loaded {len(configs)} RAG pipeline configurations:")
for cfg in configs:
    print(f"  - {cfg.name}")
    print(f"    Chunking: {cfg.chunking.type.value}")
    print(f"    Retrieval Pipeline: ")
    for search in cfg.retrieval.search.searches:
        print(f"      - {search.type.value}")
    print(f"    Reranker: {cfg.retrieval.rerank.type.value}")
    print(f"    Generation: {cfg.generation.config.model}")

Loaded 3 RAG pipeline configurations:
  - covidqa_high_recall_hybrid_v2
    Chunking: semantic
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.1-8b-instant
  - covidqa_hyde_hybrid
    Chunking: semantic
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.1-8b-instant
  - covidqa_multiquery_hybrid
    Chunking: semantic
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.1-8b-instant

## 7. Run Experiments

Run all RAG configurations on the loaded data. Each config will:
1. Build a vector index from the documents
2. Run queries against the index
3. Generate responses
4. Evaluate using TRACe metrics

Results are returned as PipelineRunResult objects.

In [ ]:
# Run experiments

print(f"Running {len(configs)} configurations from {experiment_config.start_index} to {experiment_config.end_index} queries...")
print(f"Parallel mode: {experiment_config.parallel}")

runs = runner.run(documents, raw_data)

print(f"\n✅ Experiments completed!")
print(f"  Ran {len(runs)} configurations")

for run in runs:
    print(f"  - {run.config.name}: {len(run.records)} queries")

Running 3 configurations from 0 to 246 queries...
Parallel mode: False
Loading embedding model: BAAI/bge-large-en-v1.5

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 8074.98it/s]

Loading reranker model: BAAI/bge-reranker-v2-m3

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 7282.49it/s]

Progress: 71/246 (28.9%) | QPS: 0.53 | ETA: 5.5m | Elapsed: 2.2m

2026-06-28 21:10:53,918 ERROR rag.pipeline.rag_pipeline: Query failed: No available Groq API keys.

Progress: 124/246 (50.4%) | QPS: 0.54 | ETA: 3.8m | Elapsed: 3.8m

2026-06-28 21:12:31,309 ERROR rag.pipeline.rag_pipeline: Query failed: No available Groq API keys.

Progress: 136/246 (55.3%) | QPS: 0.54 | ETA: 3.4m | Elapsed: 4.2m

2026-06-28 21:12:53,569 ERROR rag.pipeline.rag_pipeline: Query failed: No available Groq API keys.

Progress: 163/246 (66.3%) | QPS: 0.55 | ETA: 2.5m | Elapsed: 5.0m

2026-06-28 21:13:38,872 ERROR rag.pipeline.rag_pipeline: Query failed: No available Groq API keys.

Progress: 246/246 (100.0%) | QPS: 0.55 | ETA: 0s | Elapsed: 7.5mm
Progress: 8/246 (3.3%) | QPS: 0.36 | ETA: 11.0m | Elapsed: 22ss

2026-06-28 21:19:54,344 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 11/246 (4.5%) | QPS: 0.44 | ETA: 8.9m | Elapsed: 25s

2026-06-28 21:19:56,508 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 12/246 (4.9%) | QPS: 0.43 | ETA: 9.1m | Elapsed: 28s

2026-06-28 21:20:00,020 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:00,025 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 14/246 (5.7%) | QPS: 0.48 | ETA: 8.1m | Elapsed: 29s

2026-06-28 21:20:01,283 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 15/246 (6.1%) | QPS: 0.47 | ETA: 8.3m | Elapsed: 32s

2026-06-28 21:20:04,356 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 16/246 (6.5%) | QPS: 0.48 | ETA: 7.9m | Elapsed: 33s

2026-06-28 21:20:04,453 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 17/246 (6.9%) | QPS: 0.50 | ETA: 7.7m | Elapsed: 34s

2026-06-28 21:20:06,178 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 18/246 (7.3%) | QPS: 0.48 | ETA: 7.9m | Elapsed: 37s

2026-06-28 21:20:09,179 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:09,319 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 20/246 (8.1%) | QPS: 0.51 | ETA: 7.4m | Elapsed: 39s

2026-06-28 21:20:10,953 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 21/246 (8.5%) | QPS: 0.50 | ETA: 7.5m | Elapsed: 42s

2026-06-28 21:20:13,789 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:13,799 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 23/246 (9.3%) | QPS: 0.53 | ETA: 7.0m | Elapsed: 43s

2026-06-28 21:20:15,080 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 24/246 (9.8%) | QPS: 0.51 | ETA: 7.3m | Elapsed: 47s

2026-06-28 21:20:18,504 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:18,510 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 26/246 (10.6%) | QPS: 0.54 | ETA: 6.8m | Elapsed: 48s

2026-06-28 21:20:19,740 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 27/246 (11.0%) | QPS: 0.53 | ETA: 6.9m | Elapsed: 51s

2026-06-28 21:20:23,053 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:23,083 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 29/246 (11.8%) | QPS: 0.56 | ETA: 6.5m | Elapsed: 52s

2026-06-28 21:20:24,158 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 30/246 (12.2%) | QPS: 0.54 | ETA: 6.6m | Elapsed: 55s

2026-06-28 21:20:26,681 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 31/246 (12.6%) | QPS: 0.53 | ETA: 6.7m | Elapsed: 58s

2026-06-28 21:20:29,930 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 33/246 (13.4%) | QPS: 0.56 | ETA: 6.4m | Elapsed: 59s

2026-06-28 21:20:31,107 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 34/246 (13.8%) | QPS: 0.55 | ETA: 6.5m | Elapsed: 1.0m

2026-06-28 21:20:33,680 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:34,099 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 36/246 (14.6%) | QPS: 0.54 | ETA: 6.4m | Elapsed: 1.1m

2026-06-28 21:20:37,706 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:37,861 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 38/246 (15.4%) | QPS: 0.55 | ETA: 6.3m | Elapsed: 1.2m

2026-06-28 21:20:41,060 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:41,073 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 40/246 (16.3%) | QPS: 0.55 | ETA: 6.2m | Elapsed: 1.2m

2026-06-28 21:20:44,386 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:44,389 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 42/246 (17.1%) | QPS: 0.55 | ETA: 6.2m | Elapsed: 1.3m

2026-06-28 21:20:47,756 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:47,765 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 44/246 (17.9%) | QPS: 0.56 | ETA: 6.0m | Elapsed: 1.3m

2026-06-28 21:20:50,363 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:50,450 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 46/246 (18.7%) | QPS: 0.56 | ETA: 6.0m | Elapsed: 1.4m

2026-06-28 21:20:53,968 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:53,979 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 48/246 (19.5%) | QPS: 0.56 | ETA: 5.9m | Elapsed: 1.4m

2026-06-28 21:20:57,005 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:20:57,059 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 50/246 (20.3%) | QPS: 0.57 | ETA: 5.8m | Elapsed: 1.5m

2026-06-28 21:21:00,046 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:00,048 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 52/246 (21.1%) | QPS: 0.57 | ETA: 5.7m | Elapsed: 1.5m

2026-06-28 21:21:02,815 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:02,858 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 54/246 (22.0%) | QPS: 0.57 | ETA: 5.6m | Elapsed: 1.6m

2026-06-28 21:21:05,825 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:05,835 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 56/246 (22.8%) | QPS: 0.58 | ETA: 5.5m | Elapsed: 1.6m

2026-06-28 21:21:08,715 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:08,716 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 58/246 (23.6%) | QPS: 0.58 | ETA: 5.4m | Elapsed: 1.7m

2026-06-28 21:21:11,332 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:11,340 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 60/246 (24.4%) | QPS: 0.59 | ETA: 5.3m | Elapsed: 1.7m

2026-06-28 21:21:14,043 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:14,069 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 62/246 (25.2%) | QPS: 0.60 | ETA: 5.1m | Elapsed: 1.7m

2026-06-28 21:21:15,742 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 63/246 (25.6%) | QPS: 0.60 | ETA: 5.1m | Elapsed: 1.8m

2026-06-28 21:21:17,308 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 64/246 (26.0%) | QPS: 0.58 | ETA: 5.2m | Elapsed: 1.8m

2026-06-28 21:21:20,963 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:21,759 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 66/246 (26.8%) | QPS: 0.59 | ETA: 5.1m | Elapsed: 1.9m

2026-06-28 21:21:22,837 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 67/246 (27.2%) | QPS: 0.59 | ETA: 5.1m | Elapsed: 1.9m

2026-06-28 21:21:25,403 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 68/246 (27.6%) | QPS: 0.58 | ETA: 5.1m | Elapsed: 2.0m

2026-06-28 21:21:29,767 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:29,773 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 70/246 (28.5%) | QPS: 0.59 | ETA: 5.0m | Elapsed: 2.0m

2026-06-28 21:21:29,839 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 71/246 (28.9%) | QPS: 0.59 | ETA: 4.9m | Elapsed: 2.0m

2026-06-28 21:21:31,469 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 72/246 (29.3%) | QPS: 0.58 | ETA: 5.0m | Elapsed: 2.1m

2026-06-28 21:21:35,823 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 73/246 (29.7%) | QPS: 0.59 | ETA: 4.9m | Elapsed: 2.1m

2026-06-28 21:21:36,083 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:36,098 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 75/246 (30.5%) | QPS: 0.60 | ETA: 4.8m | Elapsed: 2.1m

2026-06-28 21:21:37,541 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 76/246 (30.9%) | QPS: 0.59 | ETA: 4.8m | Elapsed: 2.2m

2026-06-28 21:21:41,746 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:41,805 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:41,806 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 79/246 (32.1%) | QPS: 0.60 | ETA: 4.6m | Elapsed: 2.2m

2026-06-28 21:21:43,166 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 80/246 (32.5%) | QPS: 0.59 | ETA: 4.7m | Elapsed: 2.3m

2026-06-28 21:21:47,220 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:47,232 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:47,241 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 83/246 (33.7%) | QPS: 0.61 | ETA: 4.5m | Elapsed: 2.3m

2026-06-28 21:21:48,774 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 84/246 (34.1%) | QPS: 0.59 | ETA: 4.6m | Elapsed: 2.4m

2026-06-28 21:21:53,130 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:53,132 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:53,354 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 87/246 (35.4%) | QPS: 0.61 | ETA: 4.4m | Elapsed: 2.4m

2026-06-28 21:21:54,975 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 88/246 (35.8%) | QPS: 0.60 | ETA: 4.4m | Elapsed: 2.5m

2026-06-28 21:21:59,474 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:59,478 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:21:59,483 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 91/246 (37.0%) | QPS: 0.61 | ETA: 4.2m | Elapsed: 2.5m

2026-06-28 21:22:00,794 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 92/246 (37.4%) | QPS: 0.61 | ETA: 4.2m | Elapsed: 2.5m

2026-06-28 21:22:03,767 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:03,815 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 94/246 (38.2%) | QPS: 0.61 | ETA: 4.1m | Elapsed: 2.6m

2026-06-28 21:22:05,219 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 95/246 (38.6%) | QPS: 0.61 | ETA: 4.1m | Elapsed: 2.6m

2026-06-28 21:22:07,556 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 96/246 (39.0%) | QPS: 0.61 | ETA: 4.1m | Elapsed: 2.6m

2026-06-28 21:22:08,576 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 97/246 (39.4%) | QPS: 0.61 | ETA: 4.1m | Elapsed: 2.6m

2026-06-28 21:22:10,588 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 98/246 (39.8%) | QPS: 0.60 | ETA: 4.1m | Elapsed: 2.7m

2026-06-28 21:22:14,981 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 99/246 (40.2%) | QPS: 0.60 | ETA: 4.1m | Elapsed: 2.7m

2026-06-28 21:22:15,424 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:15,510 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 101/246 (41.1%) | QPS: 0.61 | ETA: 3.9m | Elapsed: 2.7m

2026-06-28 21:22:16,705 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.60 | ETA: 4.0m | Elapsed: 2.8m

2026-06-28 21:22:21,370 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:21,394 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:21,400 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.60 | ETA: 4.0m | Elapsed: 2.8m

2026-06-28 21:22:22,436 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.58 | ETA: 4.1m | Elapsed: 2.9m

2026-06-28 21:22:27,977 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:27,983 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:27,988 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.57 | ETA: 4.2m | Elapsed: 3.0m

2026-06-28 21:22:29,696 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.56 | ETA: 4.3m | Elapsed: 3.0m

2026-06-28 21:22:33,753 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:33,942 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:33,946 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.55 | ETA: 4.3m | Elapsed: 3.1m

2026-06-28 21:22:35,140 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.55 | ETA: 4.3m | Elapsed: 3.1m

KeyboardInterrupt:

Progress: 102/246 (41.5%) | QPS: 0.54 | ETA: 4.4m | Elapsed: 3.1m

2026-06-28 21:22:39,857 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:39,893 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.54 | ETA: 4.4m | Elapsed: 3.1m

2026-06-28 21:22:40,151 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.54 | ETA: 4.5m | Elapsed: 3.2m

2026-06-28 21:22:41,558 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.53 | ETA: 4.6m | Elapsed: 3.2m

2026-06-28 21:22:46,103 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.52 | ETA: 4.6m | Elapsed: 3.2m

2026-06-28 21:22:46,104 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:22:46,174 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.52 | ETA: 4.6m | Elapsed: 3.3m

2026-06-28 21:22:47,468 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.51 | ETA: 4.7m | Elapsed: 3.3m

2026-06-28 21:22:50,584 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:22:50,585 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.51 | ETA: 4.7m | Elapsed: 3.3m

2026-06-28 21:22:52,101 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.51 | ETA: 4.8m | Elapsed: 3.4m

2026-06-28 21:22:53,535 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.50 | ETA: 4.8m | Elapsed: 3.4m

2026-06-28 21:22:56,567 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.49 | ETA: 4.9m | Elapsed: 3.4m

2026-06-28 21:22:57,529 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:22:58,928 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.48 | ETA: 5.0m | Elapsed: 3.5m

2026-06-28 21:23:02,654 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:23:02,779 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.48 | ETA: 5.0m | Elapsed: 3.5m

2026-06-28 21:23:04,840 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.47 | ETA: 5.1m | Elapsed: 3.6m

2026-06-28 21:23:06,666 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.47 | ETA: 5.1m | Elapsed: 3.6m

2026-06-28 21:23:08,852 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:23:08,917 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.47 | ETA: 5.1m | Elapsed: 3.6m

2026-06-28 21:23:10,225 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.46 | ETA: 5.2m | Elapsed: 3.7m

2026-06-28 21:23:11,842 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.46 | ETA: 5.2m | Elapsed: 3.7m

2026-06-28 21:23:14,546 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:23:14,549 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.46 | ETA: 5.3m | Elapsed: 3.7m

2026-06-28 21:23:15,719 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.45 | ETA: 5.3m | Elapsed: 3.8m

2026-06-28 21:23:17,633 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.45 | ETA: 5.4m | Elapsed: 3.8m

2026-06-28 21:23:20,197 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:23:20,272 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.44 | ETA: 5.4m | Elapsed: 3.8m

2026-06-28 21:23:21,527 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.44 | ETA: 5.4m | Elapsed: 3.9m

2026-06-28 21:23:23,310 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.44 | ETA: 5.5m | Elapsed: 3.9m

2026-06-28 21:23:25,810 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:23:25,821 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.43 | ETA: 5.6m | Elapsed: 3.9m

2026-06-28 21:23:27,389 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.43 | ETA: 5.6m | Elapsed: 4.0m

2026-06-28 21:23:28,919 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.42 | ETA: 5.7m | Elapsed: 4.0m

2026-06-28 21:23:32,260 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:23:33,226 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.42 | ETA: 5.7m | Elapsed: 4.1m

2026-06-28 21:23:34,420 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.41 | ETA: 5.8m | Elapsed: 4.1m

2026-06-28 21:23:37,915 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:23:38,097 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.41 | ETA: 5.8m | Elapsed: 4.1m

2026-06-28 21:23:39,717 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.41 | ETA: 5.9m | Elapsed: 4.2m

2026-06-28 21:23:40,894 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.40 | ETA: 5.9m | Elapsed: 4.2m

2026-06-28 21:23:43,979 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:23:43,982 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.40 | ETA: 6.0m | Elapsed: 4.2m

2026-06-28 21:23:45,287 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.40 | ETA: 6.0m | Elapsed: 4.3m

2026-06-28 21:23:47,332 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.40 | ETA: 6.1m | Elapsed: 4.3m

2026-06-28 21:23:49,931 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:23:49,932 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.39 | ETA: 6.1m | Elapsed: 4.3m

2026-06-28 21:23:52,085 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.39 | ETA: 6.2m | Elapsed: 4.4m

2026-06-28 21:23:53,493 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.39 | ETA: 6.2m | Elapsed: 4.4m

2026-06-28 21:23:56,357 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:23:56,461 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.38 | ETA: 6.3m | Elapsed: 4.5m

2026-06-28 21:23:58,509 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.38 | ETA: 6.4m | Elapsed: 4.5m

2026-06-28 21:24:00,714 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.38 | ETA: 6.4m | Elapsed: 4.5m

2026-06-28 21:24:03,270 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:03,381 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.37 | ETA: 6.4m | Elapsed: 4.6m

2026-06-28 21:24:04,837 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.37 | ETA: 6.5m | Elapsed: 4.6m

2026-06-28 21:24:06,536 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:24:08,049 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.37 | ETA: 6.5m | Elapsed: 4.6m

2026-06-28 21:24:09,519 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.36 | ETA: 6.6m | Elapsed: 4.7m

2026-06-28 21:24:11,250 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.36 | ETA: 6.6m | Elapsed: 4.7m

2026-06-28 21:24:13,577 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.36 | ETA: 6.7m | Elapsed: 4.8m

2026-06-28 21:24:17,150 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:24:17,154 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.35 | ETA: 6.8m | Elapsed: 4.8m

2026-06-28 21:24:20,560 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:20,562 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.35 | ETA: 6.9m | Elapsed: 4.9m

2026-06-28 21:24:24,197 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:24:24,283 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.35 | ETA: 7.0m | Elapsed: 4.9m

2026-06-28 21:24:27,622 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:27,625 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.34 | ETA: 7.1m | Elapsed: 5.0m

2026-06-28 21:24:32,034 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:24:32,141 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.34 | ETA: 7.1m | Elapsed: 5.0m

2026-06-28 21:24:34,748 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:34,757 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.33 | ETA: 7.2m | Elapsed: 5.1m

2026-06-28 21:24:37,894 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.33 | ETA: 7.2m | Elapsed: 5.1m

2026-06-28 21:24:37,898 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.33 | ETA: 7.3m | Elapsed: 5.2m

2026-06-28 21:24:41,372 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:41,459 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.33 | ETA: 7.4m | Elapsed: 5.2m

2026-06-28 21:24:44,665 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:24:44,711 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.32 | ETA: 7.4m | Elapsed: 5.3m

2026-06-28 21:24:47,869 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:47,874 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.32 | ETA: 7.5m | Elapsed: 5.3m

2026-06-28 21:24:51,295 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:51,299 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.32 | ETA: 7.6m | Elapsed: 5.4m

2026-06-28 21:24:55,237 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:55,359 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.31 | ETA: 7.7m | Elapsed: 5.5m

2026-06-28 21:24:59,341 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:24:59,343 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.31 | ETA: 7.8m | Elapsed: 5.5m

2026-06-28 21:25:04,172 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:25:04,242 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.30 | ETA: 7.9m | Elapsed: 5.6m

2026-06-28 21:25:06,390 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:25:06,396 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.30 | ETA: 7.9m | Elapsed: 5.6m

2026-06-28 21:25:09,684 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:25:09,687 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.30 | ETA: 8.0m | Elapsed: 5.6m

2026-06-28 21:25:11,098 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.30 | ETA: 8.0m | Elapsed: 5.7m

2026-06-28 21:25:12,929 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.30 | ETA: 8.1m | Elapsed: 5.7m

2026-06-28 21:25:14,576 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.29 | ETA: 8.1m | Elapsed: 5.8m

2026-06-28 21:25:17,951 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.29 | ETA: 8.2m | Elapsed: 5.8m

2026-06-28 21:25:19,062 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.29 | ETA: 8.2m | Elapsed: 5.8m

2026-06-28 21:25:20,048 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.29 | ETA: 8.2m | Elapsed: 5.8m

2026-06-28 21:25:21,447 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.29 | ETA: 8.4m | Elapsed: 5.9m

2026-06-28 21:25:26,547 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:25:26,565 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:25:26,861 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.29 | ETA: 8.4m | Elapsed: 5.9m

2026-06-28 21:25:28,928 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.28 | ETA: 8.5m | Elapsed: 6.0m

2026-06-28 21:25:34,417 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:25:34,419 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:25:34,427 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.28 | ETA: 8.6m | Elapsed: 6.1m

2026-06-28 21:25:35,956 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.28 | ETA: 8.7m | Elapsed: 6.2m

2026-06-28 21:25:41,325 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:25:41,332 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:25:41,364 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.27 | ETA: 8.7m | Elapsed: 6.2m

2026-06-28 21:25:42,985 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.27 | ETA: 8.8m | Elapsed: 6.3m

2026-06-28 21:25:47,968 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:25:48,036 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:25:48,037 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.27 | ETA: 8.9m | Elapsed: 6.3m

2026-06-28 21:25:49,405 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.27 | ETA: 9.0m | Elapsed: 6.4m

2026-06-28 21:25:54,407 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:25:54,470 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:25:54,530 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.27 | ETA: 9.0m | Elapsed: 6.4m

2026-06-28 21:25:56,215 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.26 | ETA: 9.2m | Elapsed: 6.5m

2026-06-28 21:26:02,069 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:26:02,070 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()
2026-06-28 21:26:02,324 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.26 | ETA: 9.2m | Elapsed: 6.5m

2026-06-28 21:26:04,106 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.26 | ETA: 9.3m | Elapsed: 6.6m

2026-06-28 21:26:08,852 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:26:08,852 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
2026-06-28 21:26:08,853 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.26 | ETA: 9.4m | Elapsed: 6.6m

2026-06-28 21:26:10,358 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.25 | ETA: 9.4m | Elapsed: 6.7m

2026-06-28 21:26:12,165 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.25 | ETA: 9.5m | Elapsed: 6.7m

2026-06-28 21:26:14,474 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.
--- Logging error ---
Traceback (most recent call last):
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 240, in query
    response = self.generator.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/generation/default_generation.py", line 73, in generate
    response = self.provider.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 116, in generate
    key_state = self._get_next_available_key()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/providers/groq/groq_provider.py", line 101, in _get_next_available_key
    raise AllKeysExhaustedException(
providers.base.exceptions.AllKeysExhaustedException: All Groq API keys are currently rate limited.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 760, in write
    self._schedule_flush()
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 656, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/ipykernel/iostream.py", line 339, in schedule
    self._event_pipe.send(b"")
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/venv/lib/python3.11/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/_zmq.py", line 1152, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1194, in zmq.backend.cython._zmq.Socket.send
  File "zmq/backend/cython/_zmq.py", line 1339, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
Call stack:
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Users/adityanarayan/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/adityanarayan/aiml-talentsprint/rag-capstone-project/rag-foundry/rag/pipeline/rag_pipeline.py", line 294, in query
    logger.error(f"Query failed: {e}")
Message: 'Query failed: All Groq API keys are currently rate limited.'
Arguments: ()

Progress: 102/246 (41.5%) | QPS: 0.25 | ETA: 9.5m | Elapsed: 6.8m

2026-06-28 21:26:16,708 ERROR rag.pipeline.rag_pipeline: Query failed: All Groq API keys are currently rate limited.

Progress: 102/246 (41.5%) | QPS: 0.13 | ETA: 18.6m | Elapsed: 13.2m

In [11]:
for run in runs:
    print(run)

{'config_name': 'medcpt_semantic_hybrid_rerank_70b', 'config': RAGConfig(providers={'groq': ProviderConfig(type=<ProviderType.GROQ: 'groq'>, api_key_env='GROQ_API_KEY', params={'cooldown_seconds': 60})}, chunking=ChunkingConfig(type=<ChunkingType.SEMANTIC: 'semantic'>, config=SemanticChunkingConfig(embedding=EmbeddingConfig(type=<EmbeddingType.SENTENCE_TRANSFORMER: 'sentence_transformer'>, config=SentenceTransformerEmbeddingConfig(model_name='sentence-transformers/all-MiniLM-L6-v2', model=None, dimension=768)), max_words=100, similarity_threshold=0.8, overlap_sentences=1, similarity_window=5)), embedding=EmbeddingConfig(type=<EmbeddingType.MEDCPT: 'medcpt'>, config=MedCPTEmbeddingConfig(query_model_name='ncbi/MedCPT-Query-Encoder', article_model_name='ncbi/MedCPT-Article-Encoder', dimension=768)), vector_store=VectorStoreConfig(type=<VectorStoreType.FAISS: 'faiss'>, config=FaissVectorStoreConfig(dimension=768)), retrieval=RetrievalConfig(search=SearchPipelineConfig(searches=[SearchStrategyConfig(type=<SearchType.DENSE: 'dense'>, config=DenseSearchConfig(top_k=20)), SearchStrategyConfig(type=<SearchType.SPARSE: 'sparse'>, config=SparseSearchConfig(top_k=20))]), query_transform=None, fusion=FusionConfig(type=<FusionType.RRF: 'rrf'>, config=RRFFusionConfig(top_k=5, k=60)), rerank=RerankerConfig(type=<RerankerType.CROSS_ENCODER: 'cross_encoder'>, config=CrossEncoderRerankerConfig(model_name='BAAI/bge-reranker-v2-m3', top_k=5))), generation=GenerationConfig(strategy=<GenerationType.DEFAULT: 'default'>, provider='groq', config=DefaultGenerationConfig(model='llama-3.1-8b-instant', max_tokens=1024, temperature=0.7, system_prompt=None)), evaluation=EvaluationConfig(type=<EvaluationType.TRACE: 'trace'>, provider='groq', config=TRACeEvaluationConfig(model='llama-3.3-70b-versatile', max_tokens=2000, temperature=0.0)), mode=<Mode.TEST: 'test'>, name='medcpt_semantic_hybrid_rerank_70b', cache=CacheConfig(enabled=True, cache_dir='cache'), start_index=None, end_index=None, logging_config=LoggingConfig(enabled=True, level='INFO', show_progress=True)), 'total_written': 246, 'highest_continuous_index': 245, 'jsonl_path': PosixPath('temp/medcpt_semantic_hybrid_rerank_70b.jsonl')}
{'config_name': 'baai_semantic_hybrid_search_70b', 'config': RAGConfig(providers={'groq': ProviderConfig(type=<ProviderType.GROQ: 'groq'>, api_key_env='GROQ_API_KEY', params={'cooldown_seconds': 60})}, chunking=ChunkingConfig(type=<ChunkingType.SEMANTIC: 'semantic'>, config=SemanticChunkingConfig(embedding=EmbeddingConfig(type=<EmbeddingType.SENTENCE_TRANSFORMER: 'sentence_transformer'>, config=SentenceTransformerEmbeddingConfig(model_name='BAAI/bge-large-en-v1.5', model=None, dimension=768)), max_words=80, similarity_threshold=0.75, overlap_sentences=2, similarity_window=5)), embedding=EmbeddingConfig(type=<EmbeddingType.SENTENCE_TRANSFORMER: 'sentence_transformer'>, config=SentenceTransformerEmbeddingConfig(model_name='BAAI/bge-large-en-v1.5', model=None, dimension=1024)), vector_store=VectorStoreConfig(type=<VectorStoreType.FAISS: 'faiss'>, config=FaissVectorStoreConfig(dimension=1024)), retrieval=RetrievalConfig(search=SearchPipelineConfig(searches=[SearchStrategyConfig(type=<SearchType.DENSE: 'dense'>, config=DenseSearchConfig(top_k=30)), SearchStrategyConfig(type=<SearchType.SPARSE: 'sparse'>, config=SparseSearchConfig(top_k=30))]), query_transform=None, fusion=FusionConfig(type=<FusionType.RRF: 'rrf'>, config=RRFFusionConfig(top_k=5, k=30)), rerank=RerankerConfig(type=<RerankerType.CROSS_ENCODER: 'cross_encoder'>, config=CrossEncoderRerankerConfig(model_name='BAAI/bge-reranker-v2-m3', top_k=8))), generation=GenerationConfig(strategy=<GenerationType.DEFAULT: 'default'>, provider='groq', config=DefaultGenerationConfig(model='llama-3.1-8b-instant', max_tokens=1024, temperature=0.3, system_prompt=None)), evaluation=EvaluationConfig(type=<EvaluationType.TRACE: 'trace'>, provider='groq', config=TRACeEvaluationConfig(model='llama-3.3-70b-versatile', max_tokens=2000, temperature=0.0)), mode=<Mode.TEST: 'test'>, name='baai_semantic_hybrid_search_70b', cache=CacheConfig(enabled=True, cache_dir='cache'), start_index=None, end_index=None, logging_config=LoggingConfig(enabled=True, level='INFO', show_progress=True)), 'total_written': 246, 'highest_continuous_index': 239, 'jsonl_path': PosixPath('temp/baai_semantic_hybrid_search_70b.jsonl')}

## 8. Generate Reports

Generate detailed reports for each configuration including:
- Per-query table with all TRACe scores
- Aggregate statistics (mean, std, MAE)
- Comparison with ground truth

In [12]:
# Generate reports
print("Generating reports...")
reports = runner.generate_reports(runs)

print(f"\n✅ Reports generated!")
print(f"  Saved to: {experiment_config.report_dir}")

Generating reports...

✅ Reports generated!
  Saved to: reports

## 9. Display Reports

Display the generated reports with per-query and aggregate metrics.

In [13]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")
    
    # Display per-query results
    print("\nPer-Query Results:")
    display(report.display())

================================================================================
Configuration: medcpt_semantic_hybrid_rerank_70b
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `medcpt_semantic_hybrid_rerank_70b`

**name**: medcpt_semantic_hybrid_rerank_70b  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'semantic', 'config': {'embedding': {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'model': None, 'dimension': 768}}, 'max_words': 100, 'similarity_threshold': 0.8, 'overlap_sentences': 1, 'similarity_window': 5}}  •  **embedding**: {'type': 'medcpt', 'config': {'query_model_name': 'ncbi/MedCPT-Query-Encoder', 'article_model_name': 'ncbi/MedCPT-Article-Encoder', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': {'type': 'rrf', 'config': {'top_k': 5, 'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 5}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.1-8b-instant', 'max_tokens': 1024, 'temperature': 0.7, 'system_prompt': None}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'max_tokens': 2000, 'temperature': 0.0}}  •  **cache**: {'enabled': True, 'cache_dir': 'cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,When was the first case of COVID-19 identified?,"[{'text': 'Early information out of China, where COVID-19 first started, sho...","Unfortunately, the provided context does not contain information about when ...",0.2857,0.2692,0.0165,1.0000,0.0769,0.9231,1.0000,0.2857,0.7143,1.0,1.0,0.0
1,What is the structure of Hantaan virus?,"[{'text': 'The diameter of hantavirus particles is 80-US210 nm, and the stru...",The structure of Hantaan virus is not explicitly mentioned in the documents ...,0.8333,0.3000,0.5333,0.3333,0.3000,0.0333,0.4000,1.0000,-0.6000,0.0,1.0,-1.0
2,Which viruses may not cause prolonged inflammation due to strong induction o...,[{'text': 'IFNs are defined by their antiviral activities. They inhibit the ...,"Based on the given context, we can infer that viruses that cause strong indu...",0.6250,0.4118,0.2132,0.2500,0.1765,0.0735,0.4000,0.4286,-0.0286,0.0,0.0,0.0
3,How many antigens could be detected by Liew's multiplex ELISA test?,[{'text': 'Antibody arrays for simultaneous multiple antigen quantification ...,"The question does not mention ""Liew's multiplex ELISA test"" or provide any i...",0.3750,0.1250,0.2500,0.3750,0.0625,0.3125,1.0000,0.5000,0.5000,0.0,1.0,-1.0
4,What was the focus of the study?,"[{'text': 'study began.', 'index': 903, 'score': 0.0161, 'dense_score': 0.96...","Based on the provided context, it appears that the focus of the study is rel...",0.6000,0.2941,0.3059,0.6000,0.1765,0.4235,1.0000,0.6000,0.4000,0.0,1.0,-1.0
5,How many people did SARS-CoV infect?,[{'text': 'The virus that causes COVID-19 is infecting people and spreading ...,The answer to the question cannot be determined from the given context. The ...,0.2000,0.0667,0.1333,0.2000,0.0667,0.1333,1.0000,1.0000,0.0000,1.0,1.0,0.0
6,What is severe MARS noted for?,"[{'text': 'remains to be seen.', 'index': 3467, 'score': 0.0156, 'dense_scor...","There is not enough information in the provided context to determine what ""s...",0.0000,0.3636,-0.3636,0.0000,0.0455,-0.0455,0.0000,0.1250,-0.1250,1.0,1.0,0.0
7,What is an example of anti-viral defense in bats?,[{'text': 'Bats have a suite of antiviral defenses that keep the amount of v...,"According to Document 1, an example of antiviral defense in bats is the ""int...",1.0000,0.3500,0.6500,0.1111,0.1000,0.0111,0.1111,0.2857,-0.1746,1.0,1.0,0.0
8,What animal models exist for both the asymptomatic carriage of PUUV and SNV?,[{'text': 'Testing models of pathogenesis can be done more effectively when ...,"According to Document 1, the animal models that exist for both the asymptoma...",0.1667,0.1579,0.0088,0.1667,0.0526,0.1141,1.0000,0.3333,0.6667,0.0,1.0,-1.0
9,What could be novel candidates as potent inhibitors of papain like cysteine ...,"[{'text': 'In summary, the results of the present study have established tha...","According to the given context, 1-substituted pyridylimidazopyridine derivat...",0.8750,0.3889,0.4861,0.5000,0.2222,0.2778,0.5714,0.5714,-0.0000,1.0,1.0,0.0
10,What contributed to a large part of mammalian genomic sequence?,"[{'text': 'In 1977, Sanger and colleagues published a methodological paper o...","Based on the given context, it appears that the work of Sanger and colleague...",0.8750,0.0556,0.8194,0.2500,0.0556,0.1944,0.1429,1.0000,-0.8571,0.0,1.0,-1.0
11,What are exhibited in the two phases?,"[{'text': 'me two conclusions.', 'index': 3585, 'score': 0.0164, 'dense_scor...","According to the context, it seems that the two phases are referring to the ...",0.5000,0.1333,0.3667,1.0000,0.0667,0.9333,1.0000,0.5000,0.5000,0.0,1.0,-1.0
12,What does Clade A contain?,[{'text': 'Each clade had an APD of Ͼ7% from other clades and an APD of Ͻ7% ...,"Unfortunately, the provided context does not mention Clade A. It mentions se...",0.0000,1.0000,-1.0000,0.0000,0.0417,-0.0417,0.0000,0.0417,-0.0417,1.0,1.0,0.0
13,How was HFRS first brought to the attention of western medicine ?,[{'text': 'The initiation of careful observation and prompt but judicious su...,"Unfortunately, there is no information in the provided context about how HFR...",0.2000,0.1053,0.0947,0.2000,0.0526,0.1474,1.0000,0.5000,0.5000,1.0,1.0,0.0
14,In how many cases the symptoms at diagnosis were consistent with the case de...,[{'text': 'We found 323 persons 6-7%) who met the pneumonia case definition ...,"Based on the given context, we can determine that the case definition for ac...",0.8750,0.1765,0.6985,0.6250,0.1176,0.5074,0.7143,0.6667,0.0476,0.0,0.0,0.0
15,Which may be an occupational group with significantly higher incidence of se...,"[{'text': 'DCs, may be an occupational group with significantly higher incid...",DCs (Dromedary Camels) may be an occupational group with significantly highe...,0.4286,0.0588,0.3698,0.2857,0.0588,0.2269,0.6667,1.0000,-0.3333,1.0,1.0,0.0
16,Is there any evidence that MERS-CoV is a virus of pandemic concern?,[{'text': 'is no evidence that MERS-CoV is a virus of pandemic concern. None...,"Based on the provided context, there is no evidence that MERS-CoV is a virus...",1.0000,0.3810,0.6190,0.8333,0.0476,0.7857,0.8333,0.1250,0.7083,0.0,1.0,-1.0
17,What will the review focus on?,"[{'text': 'summarize the main findings.', 'index': 370, 'score': 0.0156, 'de...","Based on the given context, it appears that the documents are likely reports...",1.0000,0.7500,0.2500,1.0000,0.4375,0.5625,1.0000,0.5833,0.4167,0.0,1.0,-1.0
18,What is the Hepatitis C virus?,[{'text': 'Hepatitis C virus infection is an important global public health ...,The Hepatitis C virus (HCV) is not directly described in the given context. ...,1.0000,0.8421,0.1579,0.0000,0.4737,-0.4737,0.0000,0.5625,-0.5625,0.0,1.0,-1.0
19,What has increased hand washing?,[{'text': 'Handwashing after restroom use decreased from 72.6% in 2013 to 71...,"Based on the context provided, the following have increased hand washing:\n\...",0.5000,0.4737,0.0263,0.3750,0.1579,0.2171,0.7500,0.3333,0.4167,0.0,1.0,-1.0
20,What followup is needed to confirm the results of the current study?,"[{'text': 'basis of the present study.', 'index': 411, 'score': 0.0164, 'den...","To confirm the results of the current study, follow-up studies are needed. \...",0.6000,0.0909,0.5091,0.4000,0.0909,0.3091,0.6667,1.0000,-0.3333,0.0,1.0,-1.0
21,What was the read coverage for the E-30 genome in this study?,"[{'text': 'average read coverage was 260-fold for the E-30 genome.', 'index'...","According to Document 1, the average read coverage was 260-fold for the E-30...",0.1250,0.1176,0.0074,0.1250,0.0588,0.0662,1.0000,0.5000,0.5000,1.0,1.0,0.0
22,What has been the application of phage display technology?,[{'text': 'Phage display technology has facilitated the production of protei...,"Based on the context provided, the application of phage display technology i...",1.0000,0.2632,0.7368,1.0000,0.1579,0.8421,1.0000,0.6000,0.4000,0.0,1.0,-1.0
23,What are the attractive features of the PIV5 vector?,"[{'text': 'Similar to other RNA viruses, PIV5 has a number of features that ...","Based on the context provided, the attractive features of the PIV5 vector ar...",0.5000,0.4583,0.0417,0.3750,0.2083,0.1667,0.7500,0.4545,0.2955,0.0,1.0,-1.0
24,When was the Email published?,"[{'text': 'A part of the official diagram is shown in Fig. 1 .', 'index': 11...","Unfortunately, there is no information provided in any of the given document...",0.0000,0.2000,-0.2000,0.0000,0.2000,-0.2000,0.0000,1.0000,-1.0000,1.0,1.0,0.0
25,Which patients were excluded from the study?,"[{'text': 'Of the 200 enrolled in this study, 25 patients were excluded from...","Based on the provided context, particularly Document 2, we can determine tha...",0.5000,0.1538,0.3462,0.3333,0.1538,0.1795,0.6667,1.0000,-0.3333,0.0,0.0,0.0
26,What is Enfuvirtide?,"[{'text': 'Abstract: Enfuvirtide , is the first HIV fusion inhibitor approve...",Enfuvirtide is the first HIV fusion inhibitor approved for treatment of HIV/...,0.7143,0.2609,0.4534,0.1429,0.0435,0.0994,0.2000,0.1667,0.0333,1.0,1.0,0.0
27,What reduces the antimicrobial activities of alveolar macrophages?,"[{'text': 'In some cases, the reduced levels of protection in the absence of...","Based on the given context, it appears that M1 polarization of alveolar macr...",0.5714,0.2222,0.3492,0.1429,0.1111,0.0318,0.2500,0.5000,-0.2500,0.0,1.0,-1.0
28,How can the 2019-nCov spread?,"[{'text': 'It is currently unclear how 2019-nCoV is spread, but it is suspec...","Based on the provided context, it is suspected that the 2019-nCoV can spread...",0.4000,0.4167,-0.0167,0.4000,0.3333,0.0667,1.0000,0.8000,0.2000,1.0,1.0,0.0
29,What do ANDV-infected hamsters fitted with physiologic monitoring devices ex...,[{'text': 'abundantly in the microvascular endothelium. ANDV-infected hamste...,"According to Document 1, ANDV-infected hamsters fitted with physiologic moni...",0.1250,0.0714,0.0536,0.1250,0.0714,0.0536,1.0000,1.0000,0.0000,1.0,1.0,0.0
30,What is the relationship between aquaculture and spread of H5N1 like diseases?,"[{'text': 'The extent of aquaculture is a known risk factor , possibly becau...","According to the context, the relationship between aquaculture and the sprea...",0.7143,0.2500,0.4643,0.5714,0.2500,0.3214,0.8000,1.0000,-0.2000,0.0,1.0,-1.0
31,what will the investigation of external subdomain reveal?,"[{'text': 'summarize the main findings.', 'index': 370, 'score': 0.0156, 'de...",Since the provided context does not mention an investigation of external sub...,0.6667,0.2500,0.4167,0.6667,0.2500,0.4167,1.0000,1.0000,0.0000,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.5392,0.2956,0.3208,0.2213,0.3424
1,utilization_score,0.3871,0.1474,0.3079,0.1127,0.2872
2,completeness_score,0.6538,0.6082,0.3710,0.3080,0.3481
3,adherence_score,0.4062,0.9062,0.4911,0.2915,0.5000

None

================================================================================
Configuration: baai_semantic_hybrid_search_70b
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `baai_semantic_hybrid_search_70b`

**name**: baai_semantic_hybrid_search_70b  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'semantic', 'config': {'embedding': {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5', 'model': None, 'dimension': 768}}, 'max_words': 80, 'similarity_threshold': 0.75, 'overlap_sentences': 2, 'similarity_window': 5}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5', 'model': None, 'dimension': 1024}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 1024}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 30}}, {'type': 'sparse', 'config': {'top_k': 30}}]}, 'query_transform': None, 'fusion': {'type': 'rrf', 'config': {'top_k': 5, 'k': 30}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 8}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.1-8b-instant', 'max_tokens': 1024, 'temperature': 0.3, 'system_prompt': None}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'max_tokens': 2000, 'temperature': 0.0}}  •  **cache**: {'enabled': True, 'cache_dir': 'cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,How many antigens could be detected by Liew's multiplex ELISA test?,[{'text': 'Antibody arrays for simultaneous multiple antigen quantification ...,"According to Document 1 and Document 2, Liew validated one multiplex ELISA f...",0.2000,0.1250,0.0750,0.2000,0.0625,0.1375,1.0000,0.5000,0.5000,1.0,1.0,0.0
1,When was the first case of COVID-19 identified?,"[{'text': 'Abstract: In the WHO European Region, COVID-19 surveillance was i...",The answer to the question cannot be directly found in the given context. Ho...,0.3333,0.2692,0.0641,0.3333,0.0769,0.2564,1.0000,0.2857,0.7143,0.0,1.0,-1.0
2,What is the structure of Hantaan virus?,"[{'text': 'The diameter of hantavirus particles is 80-US210 nm, and the stru...",The structure of Hantaan virus is not explicitly stated in the question. How...,0.4545,0.3000,0.1545,0.4545,0.3000,0.1545,1.0000,1.0000,0.0000,0.0,1.0,-1.0
3,Which viruses may not cause prolonged inflammation due to strong induction o...,[{'text': 'This observation has been replicated in mouse models of infection...,"Based on the given context, it can be inferred that L (which is not explicit...",0.0667,0.4118,-0.3451,0.0667,0.1765,-0.1098,1.0000,0.4286,0.5714,0.0,0.0,0.0
4,What is severe MARS noted for?,[{'text': 'a case definition released by the KSA Ministry of Health in June ...,"The context does not mention ""MARS"" but rather ""MERS"" (Middle East Respirato...",0.3333,0.3636,-0.0303,0.1111,0.0455,0.0656,0.3333,0.1250,0.2083,0.0,1.0,-1.0
5,What was the focus of the study?,"[{'text': 'study began.', 'index': 849, 'score': 0.0323, 'dense_score': 0.80...","Based on the given context, it can be inferred that the focus of the study w...",0.5714,0.2941,0.2773,0.2857,0.1765,0.1092,0.5000,0.6000,-0.1000,0.0,1.0,-1.0
6,How many people did SARS-CoV infect?,[{'text': 'SARS-CoV caused 8098 reported cases and 774 deaths in 37 countrie...,"Based on the given context, the answer is not explicitly stated as a single ...",0.8182,0.0667,0.7515,0.4545,0.0667,0.3878,0.5556,1.0000,-0.4444,0.0,1.0,-1.0
7,What contributed to a large part of mammalian genomic sequence?,[{'text': 'Since it first became possible to compare the sequences of comple...,"The question seems incomplete, but based on the provided context, it appears...",1.0000,0.0556,0.9444,0.3846,0.0556,0.3290,0.3846,1.0000,-0.6154,0.0,1.0,-1.0
8,What animal models exist for both the asymptomatic carriage of PUUV and SNV?,[{'text': 'Testing models of pathogenesis can be done more effectively when ...,The animal models that exist for both the asymptomatic carriage of PUUV and ...,0.1538,0.1579,-0.0041,0.1538,0.0526,0.1012,1.0000,0.3333,0.6667,1.0,1.0,0.0
9,What are exhibited in the two phases?,[{'text': 'Examples of phase changes are when water solidifies at freezing p...,"Based on the context, it seems that the question is referring to the phases ...",0.8000,0.1333,0.6667,0.0000,0.0667,-0.0667,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
10,What could be novel candidates as potent inhibitors of papain like cysteine ...,"[{'text': 'In summary, the results of the present study have established tha...",1-substituted pyridylimidazopyridine derivatives.,1.0000,0.3889,0.6111,0.4444,0.2222,0.2222,0.4444,0.5714,-0.1270,1.0,1.0,0.0
11,What is the effect of chronic airway inflammatory disease in patients?,[{'text': 'Text: The prevalence of chronic airway inflammatory disease is in...,"According to the provided context, the effect of chronic airway inflammatory...",0.7500,0.6667,0.0833,0.2500,0.2222,0.0278,0.3333,0.3333,-0.0000,0.0,1.0,-1.0
12,What will the review focus on?,"[{'text': 'Each of the 21 Focus of Review topic areas were searched, and the...","Based on the given context, it appears that the review will focus on examini...",0.4286,0.7500,-0.3214,0.1429,0.4375,-0.2946,0.3333,0.5833,-0.2500,0.0,1.0,-1.0
13,What has this focus on mammalian defences and pathologies sidelined?,[{'text': 'Decades of basic immunology research have provided a near-complet...,This focus on mammalian defences and pathologies has sidelined examination o...,0.2143,0.4286,-0.2143,0.2143,0.4286,-0.2143,1.0000,1.0000,0.0000,1.0,1.0,0.0
14,What was the read coverage for the E-30 genome in this study?,"[{'text': 'average read coverage was 260-fold for the E-30 genome.', 'index'...","The read coverage for the E-30 genome in this study was 260-fold, as mention...",0.0833,0.1176,-0.0343,0.0833,0.0588,0.0245,1.0000,0.5000,0.5000,1.0,1.0,0.0
15,How does NLRP3 detect RNA viral infection?,[{'text': 'Influenza virus-induced NLRP3-mediated IL-1b and IL-18 production...,"Based on the provided context, there are multiple ways NLRP3 can detect RNA ...",0.8125,0.4286,0.3839,0.5000,0.3333,0.1667,0.6154,0.6667,-0.0513,0.0,1.0,-1.0
16,What is Denmark's estimated mean percentage [95% credible interval] of total...,"[{'text': 'Country % of total population infected', 'index': 3160, 'score': ...","Unfortunately, the information provided in the context does not directly giv...",0.6000,0.1429,0.4571,0.6000,0.1429,0.4571,1.0000,1.0000,0.0000,0.0,1.0,-1.0
17,How can Bacilius subtilis be used as an oral vaccine?,[{'text': 'PED virus spreads by fecal–oral contact and can be prevented by o...,Bacillus subtilis can be used as an oral vaccine by delivering heterologous ...,0.6250,0.5833,0.0417,0.2500,0.5417,-0.2917,0.4000,0.9286,-0.5286,0.0,1.0,-1.0
18,What is the advantage of AAV vector?,"[{'text': 'AAV vector systems have a number of engaging properties.', 'index...","Based on the provided context, the advantages of AAV vector systems include:...",0.9000,0.4167,0.4833,0.7000,0.2500,0.4500,0.7778,0.6000,0.1778,0.0,1.0,-1.0
19,What was the most common virus detected in community members in this sample?,"[{'text': 'Parainfluenza virus 4, respiratory syncytial virus B and enterovi...","Based on the given context, the most common virus detected in community memb...",0.5385,0.1538,0.3847,0.2308,0.0769,0.1539,0.4286,0.5000,-0.0714,0.0,1.0,-1.0
20,What conditions are caused by Staphylococcus aureus?,[{'text': 'Staphylococcus aureus colonizes persistently about 30% of the hum...,"According to the given context, Staphylococcus aureus causes a variety of cl...",0.6667,0.2381,0.4286,0.5000,0.2381,0.2619,0.7500,1.0000,-0.2500,0.0,1.0,-1.0
21,What strains were included in this study?,"[{'text': 'the strains sequenced for this study.', 'index': 2810, 'score': 0...","Unfortunately, the provided context does not explicitly mention the strains ...",0.3000,0.2222,0.0778,0.0000,0.1111,-0.1111,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
22,What was the most frequent coinfection?,[{'text': 'M. pneumoniae was the most frequent pathogen among co-infections ...,"Based on the given context, the most frequent coinfection is not explicitly ...",0.8889,0.1304,0.7585,0.5556,0.0435,0.5121,0.6250,0.3333,0.2917,0.0,1.0,-1.0
23,What is the conclusion of this report?,"[{'text': 'summarize the main findings.', 'index': 351, 'score': 0.0323, 'de...","Based on the context provided, it appears that the conclusions of the report...",0.6000,0.3750,0.2250,0.6000,0.1250,0.4750,1.0000,0.3333,0.6667,0.0,1.0,-1.0
24,What happens during the replication process?,[{'text': 'The differences in outcome could reflect the differences in repli...,"During the replication process, the following events occur:\n\n1. The neo-sy...",0.4167,0.4444,-0.0277,0.2500,0.5000,-0.2500,0.6000,1.0000,-0.4000,1.0,1.0,0.0
25,What does the study show?,"[{'text': 'study began.', 'index': 849, 'score': 0.0323, 'dense_score': 0.76...","Based on the context, it appears that the study has some unanticipated findi...",1.0000,0.6316,0.3684,0.5714,0.4737,0.0977,0.5714,0.7500,-0.1786,0.0,1.0,-1.0
26,What is the regularity of the virion major coat protein lattice useful for?,[{'text': 'Antibodies are generated against only three major sites on the vi...,The regularity of the virion major coat protein lattice is useful for the ge...,0.1333,0.3158,-0.1825,0.1333,0.1053,0.0280,1.0000,0.3333,0.6667,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.5440,0.3190,0.2936,0.1853,0.3110
1,utilization_score,0.3137,0.1996,0.1973,0.1546,0.2132
2,completeness_score,0.6538,0.6187,0.3141,0.2726,0.3326
3,adherence_score,0.2593,0.9630,0.4382,0.1889,0.7037

None

## 10. Compare Configurations

Generate a comparison report across all configurations to see which performs best.

In [14]:
# Generate comparison report
print("Generating comparison report...")
comparison = runner.compare()

print(f"\n✅ Comparison report generated!")
print(f"  Saved to: {experiment_config.report_dir}/comparison.csv")

Generating comparison report...

✅ Comparison report generated!
  Saved to: reports/comparison.csv

In [15]:
# Display comparison
print("\nConfiguration Comparison:")
display(comparison.to_dataframe())

Configuration Comparison:

,config_name,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,medcpt_semantic_hybrid_rerank_70b,relevance_score,0.5392,0.2956,0.3208,0.2213,0.3424
1,baai_semantic_hybrid_search_70b,relevance_score,0.5440,0.3190,0.2936,0.1853,0.3110
2,semantic_chunking_with_hybrid_search,relevance_score,0.7275,0.2887,0.3259,0.1684,0.4593
3,high_quality_large,relevance_score,0.6994,0.3405,0.2550,0.0713,0.3590
4,medcpt_embedding_with_semantic_chunking,relevance_score,0.7950,0.2887,0.3514,0.1684,0.5229
5,high_quality_small,relevance_score,0.3898,0.2345,0.3718,0.1242,0.3469

In [ ]:
from reporting.base import Report


report = Report.from_jsonl(
    "temp/covidqa_high_recall_hybrid_v2.jsonl",
    config_name="covidqa_high_recall_hybrid_v2",
)

report.display()

report.save_json("reports/covidqa_high_recall_hybrid_v2.json")

AttributeError: type object 'Report' has no attribute 'from_jsonl'

Progress: 102/246 (41.5%) | QPS: 0.13 | ETA: 19.2m | Elapsed: 13.6m

## 11. Summary

The ExperimentRunner provides a complete workflow for:

1. **Configuration-driven data loading** - Specify data source in YAML
2. **Automatic parsing** - Documents parsed using configured parser
3. **Multi-config evaluation** - Test multiple RAG configurations
4. **Parallel execution** - Speed up evaluation with parallel runs
5. **Comprehensive reporting** - Per-query and aggregate metrics
6. **Cross-config comparison** - Identify best performing config

### Key Benefits:

- **Reproducible** - Everything configured in YAML
- **Flexible** - Easy to change data source or parser
- **Scalable** - Parallel execution for faster evaluation
- **Comprehensive** - Detailed metrics and comparisons