# Experiment Runner with Automatic Data Loading

This notebook demonstrates the ExperimentRunner which:
1. **Loads experiment configuration from YAML** - including data loading config
2. **Automatically loads and parses data** - using configured loader and parser
3. **Runs multiple RAG configs** - either sequentially or in parallel
4. **Generates detailed reports** - per-query and aggregate metrics
5. **Compares results** - across different configurations

The experiment configuration in YAML specifies:
- Data source (HuggingFace dataset)
- Data parser (e.g., title_passage)
- RAG config directory
- Number of queries to evaluate
- Parallel execution settings

## 1. Setup & Dependencies

In [1]:
get_ipython().system('pip3 install datasets faiss-cpu sentence-transformers torch groq python-dotenv nltk pandas -q')

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

## 2. Imports

In [2]:
import sys
import os
from pathlib import Path
from dotenv import load_dotenv

# Change to project root directory
os.chdir(Path.cwd().parent if 'notebooks' in str(Path.cwd()) else Path.cwd())
project_root = Path.cwd()

# Add project root to Python path
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from experiment.experiment_config import ExperimentConfig
from experiment.experiment_runner import ExperimentRunner

load_dotenv(override=True)
print("Current directory:", Path.cwd())
print("HuggingFace token loaded:", bool(os.getenv("HF_TOKEN")))
print("Groq API key loaded:", bool(os.getenv("GROQ_API_KEY")))

/Users/adityanarayan/git/rag-foundry/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Current directory: /Users/adityanarayan/git/rag-foundry
HuggingFace token loaded: True
Groq API key loaded: True

## 3. Load Experiment Configuration

The experiment configuration file specifies:
- **data_loader**: How to load data (HuggingFace with dataset_name, subset, split)
- **data_parser**: How to parse documents (title_passage)
- **config_dir**: Directory containing RAG pipeline configs
- **num_queries**: Number of queries to evaluate
- **parallel**: Whether to run configs in parallel

In [3]:
EXPERIMENT_CONFIG_PATH = project_root / "experiment_configs/pubmedqa_experiment.yaml"

experiment_config = ExperimentConfig.load(EXPERIMENT_CONFIG_PATH)

print("Experiment Configuration:")
print(f"  Config Dir:  {experiment_config.config_dir}")
print(f"  Report Dir:  {experiment_config.report_dir}")
print(f"  Temp Dir:    {experiment_config.temp_dir}")
print(f"  Cache:       {experiment_config.cache}")
print(f"  Num Queries: {experiment_config.end_index}")
print(f"  Parallel:    {experiment_config.parallel}")
print(f"  Max Workers: {experiment_config.max_workers}")
print(f"\nData Loader:")
print(f"  Type: {experiment_config.data_loader['type']}")
print(f"  Config: {experiment_config.data_loader['config']}")
print(f"\nData Parser:")
print(f"  Type: {experiment_config.data_parser}")

Experiment Configuration:
  Config Dir:  rag-experiments/pubmedqa-experiment/config
  Report Dir:  rag-experiments/pubmedqa-experiment/reports
  Temp Dir:    rag-experiments/pubmedqa-experiment/temp
  Cache:       {'enabled': True, 'cache_dir': './cache'}
  Num Queries: 20
  Parallel:    False
  Max Workers: 1

Data Loader:
  Type: huggingface
  Config: {'dataset_name': 'galileo-ai/ragbench', 'subset': 'pubmedqa', 'split': 'test', 'limit': 2450}

Data Parser:
  Type: {'type': 'noop'}

## 4. Initialize Experiment Runner

The ExperimentRunner will:
- Create report directory if it doesn't exist
- Load RAG configs from the specified directory
- Load and parse data automatically based on YAML config

In [4]:
# Initialize experiment runner
runner = ExperimentRunner(experiment_config)
print("ExperimentRunner initialized")

ExperimentRunner initialized

import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")
    
    # Display per-query results
    print("\nPer-Query Results:")
    display(report.sections[0].per_query)
    
    # Display aggregate statistics
    print("\nAggregate Statistics:")
    display(report.sections[0].summary)

In [5]:
# Load data automatically based on YAML configuration
print("Loading data based on experiment configuration...")
documents, raw_data = runner.load_data()

print(f"\n✅ Data loaded successfully!")
print(f"  Documents: {len(documents)} parsed documents")
print(f"  Raw Data:  {len(raw_data)} samples")

# Inspect first sample
first_sample = raw_data[0]
print(f"\nFirst Sample:")
print(f"  Question: {first_sample['question'][:100]}...")
print(f"  Documents: {len(first_sample['documents'])}")

Loading data based on experiment configuration...
Loading HuggingFace dataset: galileo-ai/ragbench/pubmedqa (test)...
Loaded 2450 samples

✅ Data loaded successfully!
  Documents: 5932 parsed documents
  Raw Data:  2450 samples

First Sample:
  Question: Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellular Response to PEEK?...
  Documents: 5

## 6. Load RAG Pipeline Configs

Load all RAG pipeline configurations from the config directory specified in the experiment config.

In [6]:
# Load RAG pipeline configs
configs = runner.load_configs()

print(f"Loaded {len(configs)} RAG pipeline configurations:")
for cfg in configs:
    print(f"  - {cfg.name}")
    print(f"    Chunking: {cfg.chunking.type.value}")
    print(f"    Retrieval Pipeline: ")
    for search in cfg.retrieval.search.searches:
        print(f"      - {search.type.value}")
    print(f"    Reranker: {cfg.retrieval.rerank.type.value}")
    print(f"    Generation: {cfg.generation.config['model']}")

Loaded 8 RAG pipeline configurations:
  - pubmedqa_title_aware_v11_query_transform
    Chunking: sentence
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile
  - pubmedqa_title_aware_v12_improved_prompt
    Chunking: sentence
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile
  - pubmedqa_title_aware_v13_balanced
    Chunking: sentence
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile
  - pubmedqa_title_aware_v14_pubmedbert_stepback
    Chunking: sentence
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile
  - pubmedqa_title_aware_v15_biomedical_reranker
    Chunking: sentence
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile
  - pubmedqa_title_aware_v16_improved_retrieval
    Chunking: sentence
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile
  - pubmedqa_title_aware_v17_hybrid_transform
    Chunking: sentence
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile
  - pubmedqa_title_aware_v18_balanced
    Chunking: sentence
    Retrieval Pipeline:
      - dense
      - sparse
    Reranker: cross_encoder
    Generation: llama-3.3-70b-versatile

## 7. Run Experiments

Run all RAG configurations on the loaded data. Each config will:
1. Build a vector index from the documents
2. Run queries against the index
3. Generate responses
4. Evaluate using TRACe metrics

Results are returned as PipelineRunResult objects.

In [7]:
# Run experiments

print(f"Running {len(configs)} configurations from {experiment_config.start_index} to {experiment_config.end_index} queries...")
print(f"Parallel mode: {experiment_config.parallel}")

runs = runner.run(documents, raw_data)

print(f"\n✅ Experiments completed!")
print(f"  Ran {len(runs)} configurations")

for run in runs:
    print(f"  - {run['config'].name}: {run['total_written']} queries")

Running 8 configurations from 0 to 20 queries...
Parallel mode: False
Loading embedding model: BAAI/bge-large-en-v1.5

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 8027.91it/s]

Loading reranker model: BAAI/bge-reranker-v2-m3

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 5504.59it/s]

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #0: ****fyaJUsing key #0: ****fyaJ

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 2sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 2/20 (10.0%) | QPS: 0.66 | ETA: 27s | Elapsed: 3sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 3/20 (15.0%) | QPS: 0.75 | ETA: 23s | Elapsed: 4sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 4/20 (20.0%) | QPS: 0.80 | ETA: 20s | Elapsed: 5sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 5/20 (25.0%) | QPS: 0.83 | ETA: 18s | Elapsed: 6sUsing key #0: ****fyaJ
Progress: 5/20 (25.0%) | QPS: 0.71 | ETA: 21s | Elapsed: 7sUsing key #0: ****fyaJ
Progress: 6/20 (30.0%) | QPS: 0.75 | ETA: 19s | Elapsed: 8sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 7/20 (35.0%) | QPS: 0.77 | ETA: 17s | Elapsed: 9sUsing key #0: ****fyaJ
Progress: 8/20 (40.0%) | QPS: 0.80 | ETA: 15s | Elapsed: 10sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 9/20 (45.0%) | QPS: 0.81 | ETA: 14s | Elapsed: 11sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 11/20 (55.0%) | QPS: 0.91 | ETA: 10s | Elapsed: 12sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 12/20 (60.0%) | QPS: 0.85 | ETA: 9s | Elapsed: 14sUsing key #0: ****fyaJ
Progress: 12/20 (60.0%) | QPS: 0.80 | ETA: 10s | Elapsed: 15sUsing key #0: ****fyaJ
Progress: 13/20 (65.0%) | QPS: 0.81 | ETA: 9s | Elapsed: 16sUsing key #0: ****fyaJ
Progress: 13/20 (65.0%) | QPS: 0.72 | ETA: 10s | Elapsed: 18s================================================================================
429 on ****fyaJ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11445, Requested 752. Please try again in 985ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:14:33 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 1
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 972
  x-ratelimit-remaining-tokens: 555
  x-ratelimit-reset-requests: 40m19.2s
  x-ratelimit-reset-tokens: 57.225s
  x-request-id: req_01kyanc4fmf90ahnh2n2nw39hm
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204e7bc993b6ec5-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11445, Requested 752. Please try again in 985ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 1
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'fyaJ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 34, 708003), 'requests': 30, 'successes': 28, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 14/20 (70.0%) | QPS: 0.73 | ETA: 8s | Elapsed: 19sUsing key #1: ****Cf0x
Progress: 14/20 (70.0%) | QPS: 0.70 | ETA: 9s | Elapsed: 20sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 16/20 (80.0%) | QPS: 0.76 | ETA: 5s | Elapsed: 21sUsing key #1: ****Cf0x
Progress: 16/20 (80.0%) | QPS: 0.72 | ETA: 6s | Elapsed: 22sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 18/20 (90.0%) | QPS: 0.78 | ETA: 3s | Elapsed: 23sUsing key #1: ****Cf0x
Progress: 19/20 (95.0%) | QPS: 0.79 | ETA: 1s | Elapsed: 24sUsing key #1: ****Cf0x
Progress: 20/20 (100.0%) | QPS: 0.80 | ETA: 0s | Elapsed: 25s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 1/20 (5.0%) | QPS: 0.50 | ETA: 38s | Elapsed: 2sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 3/20 (15.0%) | QPS: 1.00 | ETA: 17s | Elapsed: 3sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 4/20 (20.0%) | QPS: 1.00 | ETA: 16s | Elapsed: 4sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 5/20 (25.0%) | QPS: 1.00 | ETA: 15s | Elapsed: 5sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 6/20 (30.0%) | QPS: 1.00 | ETA: 14s | Elapsed: 6sUsing key #1: ****Cf0x
Progress: 7/20 (35.0%) | QPS: 1.00 | ETA: 13s | Elapsed: 7sUsing key #1: ****Cf0x
Progress: 7/20 (35.0%) | QPS: 0.70 | ETA: 19s | Elapsed: 10sUsing key #1: ****Cf0x
================================================================================
429 on ****Cf0x
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11701, Requested 813. Please try again in 2.57s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:14:51 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 3
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 972
  x-ratelimit-remaining-tokens: 299
  x-ratelimit-reset-requests: 40m19.2s
  x-ratelimit-reset-tokens: 58.504s
  x-request-id: req_01kyancnmze2ts2agt5e1skc7g
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204e82a7b0d85e5-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11701, Requested 813. Please try again in 2.57s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 3
{'provider': 'groq', 'current_index': 1, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 34, 708003), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 54, 286956), 'requests': 30, 'successes': 28, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #2: ****zgga
Progress: 8/20 (40.0%) | QPS: 0.72 | ETA: 17s | Elapsed: 11sUsing key #2: ****zgga
Using key #2: ****zgga
Progress: 9/20 (45.0%) | QPS: 0.75 | ETA: 15s | Elapsed: 12sUsing key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Progress: 11/20 (55.0%) | QPS: 0.84 | ETA: 11s | Elapsed: 13sUsing key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Progress: 13/20 (65.0%) | QPS: 0.92 | ETA: 8s | Elapsed: 14sUsing key #2: ****zgga
Progress: 13/20 (65.0%) | QPS: 0.86 | ETA: 8s | Elapsed: 15sUsing key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Progress: 15/20 (75.0%) | QPS: 0.93 | ETA: 5s | Elapsed: 16sUsing key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Progress: 16/20 (80.0%) | QPS: 0.94 | ETA: 4s | Elapsed: 17sUsing key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Progress: 18/20 (90.0%) | QPS: 1.00 | ETA: 2s | Elapsed: 18sUsing key #2: ****zgga
Using key #2: ****zgga
Progress: 20/20 (100.0%) | QPS: 1.00 | ETA: 0s | Elapsed: 20s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #2: ****zgga
Using key #2: ****zgga
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #2: ****zgga
Using key #2: ****zgga
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 3sUsing key #2: ****zgga
Progress: 1/20 (5.0%) | QPS: 0.25 | ETA: 1.3m | Elapsed: 4sUsing key #2: ****zgga
Progress: 1/20 (5.0%) | QPS: 0.12 | ETA: 2.5m | Elapsed: 8sUsing key #2: ****zgga
================================================================================
429 on ****zgga
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11834, Requested 993. Please try again in 4.135s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:15:09 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 5
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 972
  x-ratelimit-remaining-tokens: 166
  x-ratelimit-reset-requests: 40m19.2s
  x-ratelimit-reset-tokens: 59.17s
  x-request-id: req_01kyand7p8fbev1ac3qkftf4fs
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204e89df9703a9f-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11834, Requested 993. Please try again in 4.135s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 5
{'provider': 'groq', 'current_index': 2, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 34, 708003), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 54, 286956), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 14, 758731), 'requests': 29, 'successes': 28, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #3: ****7dyb
Progress: 2/20 (10.0%) | QPS: 0.22 | ETA: 1.4m | Elapsed: 9sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 3/20 (15.0%) | QPS: 0.30 | ETA: 57s | Elapsed: 10sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 4/20 (20.0%) | QPS: 0.36 | ETA: 44s | Elapsed: 11sUsing key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Progress: 6/20 (30.0%) | QPS: 0.46 | ETA: 30s | Elapsed: 13sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 6/20 (30.0%) | QPS: 0.43 | ETA: 33s | Elapsed: 14sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 8/20 (40.0%) | QPS: 0.50 | ETA: 24s | Elapsed: 16sUsing key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Progress: 9/20 (45.0%) | QPS: 0.53 | ETA: 21s | Elapsed: 17sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 10/20 (50.0%) | QPS: 0.55 | ETA: 18s | Elapsed: 18sUsing key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Progress: 12/20 (60.0%) | QPS: 0.63 | ETA: 13s | Elapsed: 19sUsing key #3: ****7dyb
Progress: 12/20 (60.0%) | QPS: 0.60 | ETA: 13s | Elapsed: 20sUsing key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Progress: 14/20 (70.0%) | QPS: 0.66 | ETA: 9s | Elapsed: 21sUsing key #3: ****7dyb
Progress: 14/20 (70.0%) | QPS: 0.63 | ETA: 9s | Elapsed: 22sUsing key #3: ****7dyb
Progress: 14/20 (70.0%) | QPS: 0.58 | ETA: 10s | Elapsed: 24sUsing key #3: ****7dyb
Progress: 15/20 (75.0%) | QPS: 0.60 | ETA: 8s | Elapsed: 25sUsing key #3: ****7dyb
Progress: 15/20 (75.0%) | QPS: 0.55 | ETA: 9s | Elapsed: 27s================================================================================
429 on ****7dyb
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11403, Requested 720. Please try again in 615ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:15:28 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 1
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 974
  x-ratelimit-remaining-tokens: 597
  x-ratelimit-reset-requests: 37m26.4s
  x-ratelimit-reset-tokens: 57.015s
  x-request-id: req_01kyandssdf79t47815hwrq2d0
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204e911ca6a3a1a-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11403, Requested 720. Please try again in 615ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 1
{'provider': 'groq', 'current_index': 3, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 34, 708003), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 54, 286956), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 14, 758731), 'requests': 29, 'successes': 28, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 29, 292630), 'requests': 28, 'successes': 26, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #4: ****tmVo
Using key #4: ****tmVo
Progress: 16/20 (80.0%) | QPS: 0.57 | ETA: 7s | Elapsed: 28sUsing key #4: ****tmVo
Progress: 16/20 (80.0%) | QPS: 0.55 | ETA: 7s | Elapsed: 29sUsing key #4: ****tmVo
Using key #4: ****tmVo
Progress: 18/20 (90.0%) | QPS: 0.58 | ETA: 3s | Elapsed: 31sUsing key #4: ****tmVo
Using key #4: ****tmVo
Progress: 20/20 (100.0%) | QPS: 0.60 | ETA: 0s | Elapsed: 33s
Loading embedding model: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 57527.50it/s]
[transformers] BertModel LOAD REPORT from: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #4: ****tmVo
Using key #4: ****tmVo
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Progress: 1/20 (5.0%) | QPS: 0.50 | ETA: 38s | Elapsed: 2sUsing key #4: ****tmVo
Using key #4: ****tmVo
Progress: 2/20 (10.0%) | QPS: 0.66 | ETA: 27s | Elapsed: 3sUsing key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Progress: 4/20 (20.0%) | QPS: 0.99 | ETA: 16s | Elapsed: 4sUsing key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Progress: 6/20 (30.0%) | QPS: 1.19 | ETA: 12s | Elapsed: 5sUsing key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Progress: 8/20 (40.0%) | QPS: 1.32 | ETA: 9s | Elapsed: 6sUsing key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Progress: 10/20 (50.0%) | QPS: 1.42 | ETA: 7s | Elapsed: 7sUsing key #4: ****tmVo
Using key #4: ****tmVo
Progress: 11/20 (55.0%) | QPS: 1.37 | ETA: 7s | Elapsed: 8sUsing key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Progress: 13/20 (65.0%) | QPS: 1.44 | ETA: 5s | Elapsed: 9sUsing key #4: ****tmVo
Using key #4: ****tmVo
Progress: 14/20 (70.0%) | QPS: 1.39 | ETA: 4s | Elapsed: 10sUsing key #4: ****tmVo
Progress: 14/20 (70.0%) | QPS: 1.16 | ETA: 5s | Elapsed: 12sUsing key #4: ****tmVo
Progress: 15/20 (75.0%) | QPS: 1.07 | ETA: 5s | Elapsed: 14sUsing key #4: ****tmVo
Progress: 16/20 (80.0%) | QPS: 1.00 | ETA: 4s | Elapsed: 16sUsing key #4: ****tmVo
Progress: 16/20 (80.0%) | QPS: 0.84 | ETA: 5s | Elapsed: 19sUsing key #4: ****tmVo
Progress: 16/20 (80.0%) | QPS: 0.76 | ETA: 5s | Elapsed: 21sUsing key #4: ****tmVo
Progress: 17/20 (85.0%) | QPS: 0.74 | ETA: 4s | Elapsed: 23s================================================================================
429 on ****tmVo
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 2s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'requests', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:21:08 GMT
  content-type: application/json
  content-length: 375
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 2
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-remaining-requests: 960
  x-ratelimit-reset-requests: 57m36s
  x-request-id: req_01kyanr5y5ftcbnggqw9p5dd9a
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f15f8a0e47c4-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 2s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"requests","code":"rate_limit_exceeded"}}

Retry after: 2
{'provider': 'groq', 'current_index': 4, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 34, 708003), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 54, 286956), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 14, 758731), 'requests': 29, 'successes': 28, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 29, 292630), 'requests': 28, 'successes': 27, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 10, 408812), 'requests': 44, 'successes': 43, 'failures': 1, '429s': 1}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #5: ****Z8Yy
Progress: 17/20 (85.0%) | QPS: 0.70 | ETA: 4s | Elapsed: 24sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 20/20 (100.0%) | QPS: 0.77 | ETA: 0s | Elapsed: 26s
Loading reranker model: BAAI/bge-reranker-large

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 8141.71it/s]

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #5: ****Z8YyUsing key #5: ****Z8Yy

Using key #5: ****Z8Yy
Progress: 1/20 (5.0%) | QPS: 0.50 | ETA: 38s | Elapsed: 2sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 3/20 (15.0%) | QPS: 0.99 | ETA: 17s | Elapsed: 3sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 5/20 (25.0%) | QPS: 1.24 | ETA: 12s | Elapsed: 4sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 6/20 (30.0%) | QPS: 1.19 | ETA: 12s | Elapsed: 5sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 8/20 (40.0%) | QPS: 1.33 | ETA: 9s | Elapsed: 6sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 11/20 (55.0%) | QPS: 1.56 | ETA: 6s | Elapsed: 7sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 13/20 (65.0%) | QPS: 1.62 | ETA: 4s | Elapsed: 8sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 13/20 (65.0%) | QPS: 1.44 | ETA: 5s | Elapsed: 9sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 15/20 (75.0%) | QPS: 1.24 | ETA: 4s | Elapsed: 12sUsing key #5: ****Z8Yy
Progress: 15/20 (75.0%) | QPS: 1.07 | ETA: 5s | Elapsed: 14sUsing key #5: ****Z8Yy
Progress: 15/20 (75.0%) | QPS: 0.93 | ETA: 5s | Elapsed: 16sUsing key #5: ****Z8Yy
Using key #5: ****Z8Yy
Progress: 17/20 (85.0%) | QPS: 0.89 | ETA: 3s | Elapsed: 19sUsing key #5: ****Z8Yy
Progress: 17/20 (85.0%) | QPS: 0.81 | ETA: 4s | Elapsed: 21sUsing key #5: ****Z8Yy
Progress: 17/20 (85.0%) | QPS: 0.74 | ETA: 4s | Elapsed: 23s================================================================================
429 on ****Z8Yy
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 2s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'requests', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:21:43 GMT
  content-type: application/json
  content-length: 375
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 2
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-remaining-requests: 959
  x-ratelimit-reset-requests: 59m2.4s
  x-request-id: req_01kyans7vqe0ft4h0tbc0hcnrq
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f238ab1fff61-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 2s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"requests","code":"rate_limit_exceeded"}}

Retry after: 2
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 34, 708003), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 54, 286956), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 14, 758731), 'requests': 29, 'successes': 28, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 29, 292630), 'requests': 28, 'successes': 27, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 10, 408812), 'requests': 44, 'successes': 43, 'failures': 1, '429s': 1}, {'key_suffix': 'Z8Yy', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 45, 149249), 'requests': 42, 'successes': 40, 'failures': 1, '429s': 1}]}
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 18/20 (90.0%) | QPS: 0.75 | ETA: 3s | Elapsed: 24sUsing key #0: ****fyaJ
Progress: 20/20 (100.0%) | QPS: 0.77 | ETA: 0s | Elapsed: 26s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 3sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 2/20 (10.0%) | QPS: 0.40 | ETA: 45s | Elapsed: 5sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 4/20 (20.0%) | QPS: 0.57 | ETA: 28s | Elapsed: 7sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 5/20 (25.0%) | QPS: 0.62 | ETA: 24s | Elapsed: 8sUsing key #0: ****fyaJ
Progress: 6/20 (30.0%) | QPS: 0.66 | ETA: 21s | Elapsed: 9sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 6/20 (30.0%) | QPS: 0.60 | ETA: 23s | Elapsed: 10sUsing key #0: ****fyaJ
Progress: 7/20 (35.0%) | QPS: 0.63 | ETA: 21s | Elapsed: 11sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 8/20 (40.0%) | QPS: 0.66 | ETA: 18s | Elapsed: 12sUsing key #0: ****fyaJ
Using key #0: ****fyaJ
Progress: 9/20 (45.0%) | QPS: 0.69 | ETA: 16s | Elapsed: 13sUsing key #0: ****fyaJ
Progress: 9/20 (45.0%) | QPS: 0.56 | ETA: 20s | Elapsed: 16sUsing key #0: ****fyaJ
Progress: 10/20 (50.0%) | QPS: 0.55 | ETA: 18s | Elapsed: 18sUsing key #0: ****fyaJ
Progress: 10/20 (50.0%) | QPS: 0.52 | ETA: 19s | Elapsed: 19s================================================================================
429 on ****fyaJ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11528, Requested 899. Please try again in 2.135s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:22:04 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 3
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 950
  x-ratelimit-remaining-tokens: 472
  x-ratelimit-reset-requests: 1h12m0s
  x-ratelimit-reset-tokens: 57.64s
  x-request-id: req_01kyanswx1ewzsvpzmdm1w07zw
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f2bf59eb99af-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11528, Requested 899. Please try again in 2.135s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 3
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'fyaJ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 7, 694941), 'requests': 57, 'successes': 54, 'failures': 2, '429s': 2}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 44, 54, 286956), 'requests': 30, 'successes': 29, 'failures': 1, '429s': 1}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 14, 758731), 'requests': 29, 'successes': 28, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 29, 292630), 'requests': 28, 'successes': 27, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 10, 408812), 'requests': 44, 'successes': 43, 'failures': 1, '429s': 1}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 45, 149249), 'requests': 42, 'successes': 41, 'failures': 1, '429s': 1}]}
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 11/20 (55.0%) | QPS: 0.52 | ETA: 17s | Elapsed: 21sUsing key #1: ****Cf0x
Progress: 11/20 (55.0%) | QPS: 0.50 | ETA: 18s | Elapsed: 22sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 13/20 (65.0%) | QPS: 0.56 | ETA: 12s | Elapsed: 23sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 13/20 (65.0%) | QPS: 0.54 | ETA: 13s | Elapsed: 24sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 15/20 (75.0%) | QPS: 0.60 | ETA: 8s | Elapsed: 25sUsing key #1: ****Cf0x
Progress: 15/20 (75.0%) | QPS: 0.57 | ETA: 9s | Elapsed: 26sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 17/20 (85.0%) | QPS: 0.63 | ETA: 5s | Elapsed: 27sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 18/20 (90.0%) | QPS: 0.64 | ETA: 3s | Elapsed: 28sUsing key #1: ****Cf0x
Progress: 19/20 (95.0%) | QPS: 0.65 | ETA: 2s | Elapsed: 29sUsing key #1: ****Cf0x
Progress: 20/20 (100.0%) | QPS: 0.64 | ETA: 0s | Elapsed: 31s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 2sUsing key #1: ****Cf0x
Progress: 1/20 (5.0%) | QPS: 0.33 | ETA: 57s | Elapsed: 3sUsing key #1: ****Cf0x
Using key #1: ****Cf0x
Progress: 2/20 (10.0%) | QPS: 0.50 | ETA: 36s | Elapsed: 4sUsing key #1: ****Cf0x
Progress: 2/20 (10.0%) | QPS: 0.28 | ETA: 1.1m | Elapsed: 7sUsing key #1: ****Cf0x
Progress: 3/20 (15.0%) | QPS: 0.37 | ETA: 46s | Elapsed: 8s================================================================================
429 on ****Cf0x
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11672, Requested 908. Please try again in 2.9s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:22:24 GMT
  content-type: application/json
  content-length: 381
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 3
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 951
  x-ratelimit-remaining-tokens: 328
  x-ratelimit-reset-requests: 1h10m33.6s
  x-ratelimit-reset-tokens: 58.36s
  x-request-id: req_01kyantgnkfzea1cg4rv7dxwp7
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f33dca8bb8bf-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11672, Requested 908. Please try again in 2.9s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 3
{'provider': 'groq', 'current_index': 1, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 7, 694941), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'Cf0x', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 27, 936006), 'requests': 56, 'successes': 53, 'failures': 2, '429s': 2}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 14, 758731), 'requests': 29, 'successes': 28, 'failures': 1, '429s': 1}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 29, 292630), 'requests': 28, 'successes': 27, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 10, 408812), 'requests': 44, 'successes': 43, 'failures': 1, '429s': 1}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 45, 149249), 'requests': 42, 'successes': 41, 'failures': 1, '429s': 1}]}
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Progress: 5/20 (25.0%) | QPS: 0.55 | ETA: 27s | Elapsed: 9sUsing key #2: ****zgga
Using key #2: ****zgga
Progress: 6/20 (30.0%) | QPS: 0.60 | ETA: 23s | Elapsed: 10sUsing key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Progress: 7/20 (35.0%) | QPS: 0.63 | ETA: 21s | Elapsed: 11sUsing key #2: ****zgga
Progress: 8/20 (40.0%) | QPS: 0.66 | ETA: 18s | Elapsed: 12sUsing key #2: ****zgga
Using key #2: ****zgga
Progress: 8/20 (40.0%) | QPS: 0.61 | ETA: 20s | Elapsed: 13sUsing key #2: ****zgga
Using key #2: ****zgga
Progress: 10/20 (50.0%) | QPS: 0.71 | ETA: 14s | Elapsed: 14sUsing key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Progress: 11/20 (55.0%) | QPS: 0.73 | ETA: 12s | Elapsed: 15sUsing key #2: ****zgga
Using key #2: ****zgga
Progress: 12/20 (60.0%) | QPS: 0.75 | ETA: 11s | Elapsed: 16sUsing key #2: ****zgga
Progress: 12/20 (60.0%) | QPS: 0.63 | ETA: 13s | Elapsed: 19sUsing key #2: ****zgga
Progress: 13/20 (65.0%) | QPS: 0.62 | ETA: 11s | Elapsed: 21sUsing key #2: ****zgga
Progress: 13/20 (65.0%) | QPS: 0.56 | ETA: 12s | Elapsed: 23s================================================================================
429 on ****zgga
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11190, Requested 861. Please try again in 255ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:22:40 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 1
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 957
  x-ratelimit-remaining-tokens: 810
  x-ratelimit-reset-requests: 1h1m55.2s
  x-ratelimit-reset-tokens: 55.95s
  x-request-id: req_01kyanv083e3v9ha76khekce5j
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f3a18c1a17d7-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11190, Requested 861. Please try again in 255ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 1
{'provider': 'groq', 'current_index': 2, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 7, 694941), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 27, 936006), 'requests': 56, 'successes': 54, 'failures': 2, '429s': 2}, {'key_suffix': 'zgga', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 41, 890510), 'requests': 51, 'successes': 48, 'failures': 2, '429s': 2}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 45, 29, 292630), 'requests': 28, 'successes': 27, 'failures': 1, '429s': 1}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 10, 408812), 'requests': 44, 'successes': 43, 'failures': 1, '429s': 1}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 45, 149249), 'requests': 42, 'successes': 41, 'failures': 1, '429s': 1}]}
Using key #3: ****7dyb
Progress: 13/20 (65.0%) | QPS: 0.54 | ETA: 13s | Elapsed: 24sUsing key #3: ****7dyb
Progress: 14/20 (70.0%) | QPS: 0.56 | ETA: 11s | Elapsed: 25sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 15/20 (75.0%) | QPS: 0.57 | ETA: 9s | Elapsed: 26sUsing key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Progress: 16/20 (80.0%) | QPS: 0.59 | ETA: 7s | Elapsed: 27sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 18/20 (90.0%) | QPS: 0.62 | ETA: 3s | Elapsed: 29sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 20/20 (100.0%) | QPS: 0.66 | ETA: 0s | Elapsed: 30s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 2sUsing key #3: ****7dyb
Using key #3: ****7dyb
Progress: 2/20 (10.0%) | QPS: 0.50 | ETA: 36s | Elapsed: 4sUsing key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Progress: 4/20 (20.0%) | QPS: 0.80 | ETA: 20s | Elapsed: 5sUsing key #3: ****7dyb
Progress: 4/20 (20.0%) | QPS: 0.66 | ETA: 24s | Elapsed: 6sUsing key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Progress: 6/20 (30.0%) | QPS: 0.85 | ETA: 16s | Elapsed: 7sUsing key #3: ****7dyb
Progress: 6/20 (30.0%) | QPS: 0.60 | ETA: 23s | Elapsed: 10sUsing key #3: ****7dyb
Progress: 6/20 (30.0%) | QPS: 0.46 | ETA: 31s | Elapsed: 13sUsing key #3: ****7dyb
Progress: 7/20 (35.0%) | QPS: 0.46 | ETA: 28s | Elapsed: 15sUsing key #3: ****7dyb
Progress: 7/20 (35.0%) | QPS: 0.41 | ETA: 32s | Elapsed: 17s================================================================================
429 on ****7dyb
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11289, Requested 800. Please try again in 445ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:23:04 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 1
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 950
  x-ratelimit-remaining-tokens: 711
  x-ratelimit-reset-requests: 1h12m0s
  x-ratelimit-reset-tokens: 56.445s
  x-request-id: req_01kyanvqbge1783fpvdf2c5wcq
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f4356e324221-BOM
  alt-svc: h3=":443"; ma=86400

Body:

## 7b. Evaluate Existing JSONL Files

Run offline evaluation on already-generated JSONL files.
Uses experiment-level evaluation config — all configs are scored with the same judge model.

- `parallel_runs=True` — evaluate multiple configs simultaneously
- `parallel_config_run=True` — evaluate records within each config in parallel

In [8]:
# Discover all configs and build run dicts from existing JSONL files
configs = runner.load_configs()
runs = []
for cfg in configs:
    jsonl_path = experiment_config.temp_dir / f"{cfg.name}.jsonl"
    if jsonl_path.exists():
        runs.append({"config_name": cfg.name, "config": cfg, "jsonl_path": jsonl_path})
    else:
        print(f"  Skipping {cfg.name} — no JSONL found")

print(f"Found {len(runs)} configs with JSONL files")

# Evaluate all configs: parallel across configs + parallel within each config
eval_runs = runner.evaluate_runs(
    runs,
    parallel_runs=True,
    parallel_config_run=True,
)

# Use eval_runs for report generation downstream
runs = eval_runs
print(f"\n✅ Evaluation complete: {len(eval_runs)} configs")

Found 8 configs with JSONL files
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
================================================================================
429 on ****tmVo
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11499, Requested 1864. Please try again in 6.814999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:24:45 GMT
  content-type: application/json
  content-length: 390
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 7
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 929
  x-ratelimit-remaining-tokens: 501
  x-ratelimit-reset-requests: 1h42m14.4s
  x-ratelimit-reset-tokens: 57.495s
  x-request-id: req_01kyanyspse81seh0c3qv76281
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f6aaddc329ed-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11499, Requested 1864. Please try again in 6.814999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 7
{'provider': 'groq', 'current_index': 4, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 7, 694941), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 27, 936006), 'requests': 56, 'successes': 54, 'failures': 2, '429s': 2}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 41, 890510), 'requests': 51, 'successes': 49, 'failures': 2, '429s': 2}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 53, 5, 549539), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 54, 52, 262818), 'requests': 77, 'successes': 74, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 51, 45, 149249), 'requests': 42, 'successes': 41, 'failures': 1, '429s': 1}]}
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
Using key #5: ****Z8Yy
================================================================================
429 on ****Z8Yy
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11920, Requested 1328. Please try again in 6.239999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:24:55 GMT
  content-type: application/json
  content-length: 390
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 7
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 952
  x-ratelimit-remaining-tokens: 80
  x-ratelimit-reset-requests: 1h9m7.2s
  x-ratelimit-reset-tokens: 59.599s
  x-request-id: req_01kyanz44mebssfry5adekcy5g
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f6eda9f50029-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq0qh6m2e87rj92vbs1qjw6s` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11920, Requested 1328. Please try again in 6.239999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 7
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 7, 694941), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 27, 936006), 'requests': 56, 'successes': 54, 'failures': 2, '429s': 2}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 41, 890510), 'requests': 51, 'successes': 49, 'failures': 2, '429s': 2}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 53, 5, 549539), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 54, 52, 262818), 'requests': 77, 'successes': 75, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 2, 945310), 'requests': 52, 'successes': 49, 'failures': 2, '429s': 2}]}
Using key #0: ****fyaJ
Using key #0: ****fyaJ
[pubmedqa_title_aware_v11_query_transform] Evaluation complete → rag-experiments/pubmedqa-experiment/temp/pubmedqa_title_aware_v11_query_transform.jsonl
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
Using key #0: ****fyaJ
================================================================================
429 on ****fyaJ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10636, Requested 1473. Please try again in 545ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:25:06 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 1
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 941
  x-ratelimit-remaining-tokens: 1364
  x-ratelimit-reset-requests: 1h24m57.599s
  x-ratelimit-reset-tokens: 53.18s
  x-request-id: req_01kyanzevhf8bsvsx1hsj31jvn
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f7323c7ee40f-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7e089nf7yba8zdzhf2rn33` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10636, Requested 1473. Please try again in 545ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 1
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'fyaJ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 7, 918115), 'requests': 68, 'successes': 64, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 27, 936006), 'requests': 56, 'successes': 54, 'failures': 2, '429s': 2}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 41, 890510), 'requests': 51, 'successes': 49, 'failures': 2, '429s': 2}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 53, 5, 549539), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 54, 52, 262818), 'requests': 77, 'successes': 75, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 2, 945310), 'requests': 52, 'successes': 50, 'failures': 2, '429s': 2}]}
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
Using key #1: ****Cf0x
================================================================================
429 on ****Cf0x
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10453, Requested 1558. Please try again in 55ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:25:21 GMT
  content-type: application/json
  content-length: 382
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 1
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 943
  x-ratelimit-remaining-tokens: 1547
  x-ratelimit-reset-requests: 1h22m4.8s
  x-ratelimit-reset-tokens: 52.265s
  x-request-id: req_01kyanzx0ff9ar9vqv32na9kk0
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f78ccd6b3b15-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7ds2p1edqs3vmn5mx0t5bs` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10453, Requested 1558. Please try again in 55ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 1
{'provider': 'groq', 'current_index': 1, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 7, 918115), 'requests': 68, 'successes': 65, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 22, 413793), 'requests': 67, 'successes': 63, 'failures': 3, '429s': 3}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 52, 41, 890510), 'requests': 51, 'successes': 49, 'failures': 2, '429s': 2}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 53, 5, 549539), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 54, 52, 262818), 'requests': 77, 'successes': 75, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 2, 945310), 'requests': 52, 'successes': 50, 'failures': 2, '429s': 2}]}
Using key #2: ****zgga
Using key #2: ****zgga
[pubmedqa_title_aware_v12_improved_prompt] Evaluation complete → rag-experiments/pubmedqa-experiment/temp/pubmedqa_title_aware_v12_improved_prompt.jsonl
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
Using key #2: ****zgga
================================================================================
429 on ****zgga
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11807, Requested 1824. Please try again in 8.154999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:25:45 GMT
  content-type: application/json
  content-length: 390
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 9
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 946
  x-ratelimit-remaining-tokens: 193
  x-ratelimit-reset-requests: 1h17m45.6s
  x-ratelimit-reset-tokens: 59.035s
  x-request-id: req_01kyap0m9tef2agvq1knm0nrrb
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f821d8de40cf-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kw7dejm9f54bwcgcs3nzsarc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11807, Requested 1824. Please try again in 8.154999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 9
{'provider': 'groq', 'current_index': 2, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 7, 918115), 'requests': 68, 'successes': 65, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 22, 413793), 'requests': 67, 'successes': 64, 'failures': 3, '429s': 3}, {'key_suffix': 'zgga', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 54, 263350), 'requests': 63, 'successes': 59, 'failures': 3, '429s': 3}, {'key_suffix': '7dyb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 53, 5, 549539), 'requests': 57, 'successes': 55, 'failures': 2, '429s': 2}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 54, 52, 262818), 'requests': 77, 'successes': 75, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 2, 945310), 'requests': 52, 'successes': 50, 'failures': 2, '429s': 2}]}
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
Using key #3: ****7dyb
================================================================================
429 on ****7dyb
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11584, Requested 1851. Please try again in 7.175s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:26:05 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 8
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 940
  x-ratelimit-remaining-tokens: 416
  x-ratelimit-reset-requests: 1h26m24s
  x-ratelimit-reset-tokens: 57.92s
  x-request-id: req_01kyap17tqegnb3p8jgb722c2r
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f89edb554c81-BOM
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01ktgsjkxdezcv8vdda8vc9pyw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11584, Requested 1851. Please try again in 7.175s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 8
{'provider': 'groq', 'current_index': 3, 'keys': [{'key_suffix': 'fyaJ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 7, 918115), 'requests': 68, 'successes': 65, 'failures': 3, '429s': 3}, {'key_suffix': 'Cf0x', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 22, 413793), 'requests': 67, 'successes': 64, 'failures': 3, '429s': 3}, {'key_suffix': 'zgga', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 54, 263350), 'requests': 63, 'successes': 60, 'failures': 3, '429s': 3}, {'key_suffix': '7dyb', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 56, 13, 259947), 'requests': 68, 'successes': 64, 'failures': 3, '429s': 3}, {'key_suffix': 'tmVo', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 54, 52, 262818), 'requests': 77, 'successes': 75, 'failures': 2, '429s': 2}, {'key_suffix': 'Z8Yy', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 24, 23, 55, 2, 945310), 'requests': 52, 'successes': 50, 'failures': 2, '429s': 2}]}
Using key #4: ****tmVo
[pubmedqa_title_aware_v13_balanced] Evaluation complete → rag-experiments/pubmedqa-experiment/temp/pubmedqa_title_aware_v13_balanced.jsonl
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
Using key #4: ****tmVo
================================================================================
429 on ****tmVo
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq4kd2eeekas3zmfykg6fw6d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11689, Requested 1728. Please try again in 7.085s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Fri, 24 Jul 2026 18:26:27 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 8
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 916
  x-ratelimit-remaining-tokens: 311
  x-ratelimit-reset-requests: 2h0m57.6s
  x-ratelimit-reset-tokens: 58.445s
  x-request-id: req_01kyap1x6nefvvtgf3sckx20yn
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a204f9279fea3b45-BOM
  alt-svc: h3=":443"; ma=86400

Body:

## 8. Generate Reports

Generate detailed reports for each configuration including:
- Per-query table with all TRACe scores
- Aggregate statistics (mean, std, MAE)
- Comparison with ground truth

In [9]:
# Generate reports
print("Generating reports...")
reports = runner.generate_reports(runs)

print(f"\n✅ Reports generated!")
print(f"  Saved to: {experiment_config.report_dir}")

Generating reports...

✅ Reports generated!
  Saved to: rag-experiments/pubmedqa-experiment/reports

## 9. Display Reports

Display the generated reports with per-query and aggregate metrics.

In [10]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")
    
    # Display per-query results
    print("\nPer-Query Results:")
    display(report.display())

================================================================================
Configuration: pubmedqa_title_aware_v11_query_transform
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `pubmedqa_title_aware_v11_query_transform`

**name**: pubmedqa_title_aware_v11_query_transform  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 200, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5', 'dimension': 1024}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 1024}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 50, 'context_window': 1}}, {'type': 'sparse', 'config': {'top_k': 50}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'num_queries': 3, 'model': 'llama-3.3-70b-versatile', 'temperature': 0.3}}, 'fusion': {'type': 'rrf', 'config': {'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 7}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a biomedical question answering assistant.\nAnswer ONLY from the retrieved passages below.\nBe concise but complete — include all relevant details from the passages that address the question.\nDo NOT add information from your own knowledge.\nDo NOT hedge with phrases like "based on general knowledge" or "it is well-established".\nIf the passages do not contain enough information, say "The provided context does not contain sufficient information to answer this question."\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include all relevant details):\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellul...,"[{'text': '', 'title': '', 'content': 'Despite its widespread use in orthopa...","According to the passages, surface porosity and pore size do influence both ...",0.8235,0.6111,0.2124,0.3529,0.5000,-0.1471,0.4286,0.7273,-0.2987,0.0,1.0,-1.0
1,Does prosthetic covering of nitinol stents alter healing characteristics or ...,"[{'text': '', 'title': '', 'content': 'To evaluate placement of polyester (D...",The provided context does not contain sufficient information to answer this ...,0.1250,0.5000,-0.3750,0.1250,0.4000,-0.2750,1.0000,0.8000,0.2000,0.0,0.0,0.0
2,Is diabetes mellitus a negative prognostic factor for the treatment of advan...,"[{'text': '', 'title': '', 'content': 'It has been demonstrated that there a...",The provided context does not contain sufficient information to directly ans...,0.5455,0.2857,0.2598,0.1818,0.1429,0.0389,0.3333,0.5000,-0.1667,1.0,1.0,0.0
3,Do elderly persons need to be encouraged to drink more fluids?,"[{'text': '', 'title': '', 'content': 'A recently published and widely quote...",The provided context suggests that encouraging elderly persons to drink more...,0.4706,0.7692,-0.2986,0.4118,0.4615,-0.0497,0.8750,0.6000,0.2750,0.0,1.0,-1.0
4,Do the economic and social factors play an important role in relation to the...,"[{'text': '', 'title': '', 'content': 'To evaluate the behavior of contact l...",The provided context suggests that economic and social factors may play a ro...,0.5000,0.7000,-0.2000,0.4167,0.1000,0.3167,0.8333,0.1429,0.6904,0.0,1.0,-1.0
5,Are prostate biopsies mandatory in patients with prostate-specific antigen i...,"[{'text': '', 'title': '', 'content': 'Aim of this study was to evaluate if ...",The provided context does not contain sufficient information to directly ans...,0.3333,0.5000,-0.1667,0.1667,0.2500,-0.0833,0.5000,0.5000,0.0000,0.0,1.0,-1.0
6,Do working conditions explain the increased risks of disability pension amon...,"[{'text': '', 'title': '', 'content': 'Rates of disability pension are great...","According to Document 2, high physical strain at work and low job control bo...",0.4000,0.4615,-0.0615,0.2000,0.1538,0.0462,0.3333,0.3333,-0.0000,0.0,1.0,-1.0
7,Platelet aggregation according to body mass index in patients undergoing cor...,"[{'text': '', 'title': '', 'content': 'A 300 mg clopidogrel loading-dose (LD...","According to the passages, platelet aggregation (PA) was found to be signifi...",0.5625,0.3750,0.1875,0.1875,0.1875,0.0000,0.3333,0.5000,-0.1667,0.0,1.0,-1.0
8,Interleukin 27 polymorphisms in HCV RNA positive patients: is there an impac...,"[{'text': '', 'title': '', 'content': 'Interleukin 27 (IL-27) has pleiotropi...",The provided context does not contain sufficient information to directly ans...,0.5333,0.5333,-0.0000,0.4000,0.5333,-0.1333,0.7500,1.0000,-0.2500,0.0,1.0,-1.0
9,Can the Functional Movement Screen™ be used to capture changes in spine and ...,"[{'text': '', 'title': '', 'content': 'To examine whether objective measures...",The Functional Movement Screen (FMS) can be used to examine changes in spine...,0.6250,0.5714,0.0536,0.5000,0.4286,0.0714,0.8000,0.7500,0.0500,0.0,0.0,0.0
10,Is the time interval between surgery and radiotherapy important in operable ...,"[{'text': '', 'title': '', 'content': 'To evaluate the influence of prognost...",The provided context suggests that the time interval between surgery and rad...,0.4286,0.5385,-0.1099,0.4286,0.3077,0.1209,1.0000,0.5714,0.4286,0.0,1.0,-1.0
11,Comparison of creamatocrit and protein concentration in each mammary lobe of...,"[{'text': '', 'title': '', 'content': 'Seventeen mothers were enrolled in th...",The milk composition of each mammary lobe differs in the same breast. When c...,0.4286,0.2500,0.1786,0.2143,0.1667,0.0476,0.5000,0.6667,-0.1667,1.0,1.0,0.0
12,Do T1a breast cancers profit from adjuvant systemic therapy?,"[{'text': '', 'title': '', 'content': 'With the demonstration that adjuvant ...",The provided context does not contain sufficient information to directly ans...,0.6667,0.3077,0.3590,0.1667,0.3077,-0.1410,0.2500,0.7500,-0.5000,0.0,1.0,-1.0
13,Blood donation mobile applications: are donors ready?,"[{'text': '', 'title': '', 'content': 'A total of 982 ethnically diverse res...","According to the passages, blood donors appear to be ready for mobile applic...",0.6111,0.6154,-0.0043,0.3333,0.3077,0.0256,0.5455,0.5000,0.0455,0.0,1.0,-1.0
14,Increasing mixed chimerism is an important prognostic factor for unfavorable...,"[{'text': '', 'title': '', 'content': 'We recently reported that children wi...","According to Document 1, increasing mixed chimerism (MC) after allogeneic st...",0.4444,0.2500,0.1944,0.2222,0.2500,-0.0278,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
15,Can we target smoking groups more effectively?,"[{'text': '', 'title': '', 'content': 'Identifying ethnic differences in the...",Identifying ethnic differences in the age of smoking onset from nationally r...,1.0000,0.8571,0.1429,0.3158,0.8571,-0.5413,0.3158,1.0000,-0.6842,0.0,1.0,-1.0
16,Going public: do risk and choice explain differences in caesarean birth rate...,"[{'text': '', 'title': '', 'content': 'women who birthed in Queensland, Aust...","According to the passages, in Australia, women who birth in private faciliti...",0.8000,0.7000,0.1000,0.3000,0.6000,-0.3000,0.3750,0.8571,-0.4821,1.0,1.0,0.0
17,Are the statistical data from Benin's National Tuberculosis Programme reliable?,"[{'text': '', 'title': '', 'content': 'The National Tuberculosis Programme (...",The provided context does not contain sufficient information to answer this ...,0.0909,0.1667,-0.0758,0.0000,1.0000,-1.0000,0.0000,1.0000,-1.0000,1.0,1.0,0.0
18,Association of chronic diseases and impairments with disability in older adu...,"[{'text': '', 'title': '', 'content': 'To examine how the associations of ch...",The provided context does not contain sufficient information to answer this ...,0.7000,0.6667,0.0333,0.2000,0.3333,-0.1333,0.2857,0.5000,-0.2143,0.0,1.0,-1.0
19,Can metabolic disorders in aging men contribute to prostatic hyperplasia eli...,"[{'text': '', 'title': '', 'content': 'The aim of this study was to evaluate...",The provided context does not contain sufficient information to directly ans...,0.5455,0.1111,0.4344,0.1818,0.1111,0.0707,0.3333,1.0000,-0.6667,0.0,0.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.5317,0.4885,0.2109,0.2032,0.1724
1,utilization_score,0.2653,0.3699,0.1231,0.2343,0.1785
2,completeness_score,0.5146,0.6849,0.2670,0.2407,0.3393
3,adherence_score,0.2000,0.8500,0.4000,0.3571,0.6500

None

================================================================================
Configuration: pubmedqa_title_aware_v12_improved_prompt
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `pubmedqa_title_aware_v12_improved_prompt`

**name**: pubmedqa_title_aware_v12_improved_prompt  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 200, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5', 'dimension': 1024}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 1024}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 50, 'context_window': 1}}, {'type': 'sparse', 'config': {'top_k': 50}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'num_queries': 3, 'model': 'llama-3.3-70b-versatile', 'temperature': 0.3}}, 'fusion': {'type': 'rrf', 'config': {'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 7}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a biomedical question answering assistant.\nYour task is to answer questions ONLY using information from the retrieved passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use any external knowledge.\n2. If the passages contain the answer, provide it directly and completely.\n3. If the passages do NOT contain enough information to answer, respond with: "The passages do not contain sufficient information to answer this question."\n4. Do NOT hedge, qualify, or add phrases like "based on general knowledge" or "it is well-established."\n5. Do NOT say "The provided context does not contain..." - use the exact phrase above instead.\n6. Include all relevant details, statistics, and findings from the passages.\n7. Be concise but thorough - avoid unnecessary verbosity.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include all relevant details):\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellul...,"[{'text': '', 'title': '', 'content': 'Despite its widespread use in orthopa...","According to the passages, surface porosity and pore size do influence the m...",0.8235,0.6111,0.2124,0.6471,0.5000,0.1471,0.7857,0.7273,0.0584,1.0,1.0,0.0
1,Does prosthetic covering of nitinol stents alter healing characteristics or ...,"[{'text': '', 'title': '', 'content': 'To evaluate placement of polyester (D...",The passages do not contain sufficient information to answer this question.,0.1250,0.5000,-0.3750,0.0000,0.4000,-0.4000,0.0000,0.8000,-0.8000,1.0,0.0,1.0
2,Is diabetes mellitus a negative prognostic factor for the treatment of advan...,"[{'text': '', 'title': '', 'content': 'It has been demonstrated that there a...",The passages do not contain sufficient information to answer this question.,0.6364,0.2857,0.3507,0.0000,0.1429,-0.1429,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
3,Do elderly persons need to be encouraged to drink more fluids?,"[{'text': '', 'title': '', 'content': 'A recently published and widely quote...",The passages do not contain sufficient information to definitively answer wh...,0.5294,0.7692,-0.2398,0.4118,0.4615,-0.0497,0.7778,0.6000,0.1778,0.0,1.0,-1.0
4,Do the economic and social factors play an important role in relation to the...,"[{'text': '', 'title': '', 'content': 'To evaluate the behavior of contact l...",The passages suggest that economic and social factors may play a role in con...,0.6000,0.7000,-0.1000,0.4000,0.1000,0.3000,0.6667,0.1429,0.5238,0.0,1.0,-1.0
5,Are prostate biopsies mandatory in patients with prostate-specific antigen i...,"[{'text': '', 'title': '', 'content': 'Aim of this study was to evaluate if ...",The passages do not contain sufficient information to answer this question.,0.5000,0.5000,0.0000,0.0000,0.2500,-0.2500,0.0000,0.5000,-0.5000,1.0,1.0,0.0
6,Do working conditions explain the increased risks of disability pension amon...,"[{'text': '', 'title': '', 'content': 'Rates of disability pension are great...","According to Document 2, high physical strain at work and low job control bo...",0.6667,0.4615,0.2052,0.2000,0.1538,0.0462,0.3000,0.3333,-0.0333,0.0,1.0,-1.0
7,Platelet aggregation according to body mass index in patients undergoing cor...,"[{'text': '', 'title': '', 'content': 'A 300 mg clopidogrel loading-dose (LD...",The passages do not contain sufficient information to answer this question.,0.5455,0.3750,0.1705,0.0000,0.1875,-0.1875,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
8,Interleukin 27 polymorphisms in HCV RNA positive patients: is there an impac...,"[{'text': '', 'title': '', 'content': 'Interleukin 27 (IL-27) has pleiotropi...",The passages do not contain sufficient information to answer this question.,0.4444,0.5333,-0.0889,0.0000,0.5333,-0.5333,0.0000,1.0000,-1.0000,1.0,1.0,0.0
9,Can the Functional Movement Screen™ be used to capture changes in spine and ...,"[{'text': '', 'title': '', 'content': 'To examine whether objective measures...",The passages suggest that the Functional Movement Screen (FMS) can be used t...,0.5000,0.5714,-0.0714,0.5000,0.4286,0.0714,1.0000,0.7500,0.2500,0.0,0.0,0.0
10,Is the time interval between surgery and radiotherapy important in operable ...,"[{'text': '', 'title': '', 'content': 'To evaluate the influence of prognost...",The passages do not contain sufficient information to answer this question.,0.1000,0.5385,-0.4385,0.0000,0.3077,-0.3077,0.0000,0.5714,-0.5714,0.0,1.0,-1.0
11,Comparison of creamatocrit and protein concentration in each mammary lobe of...,"[{'text': '', 'title': '', 'content': 'Seventeen mothers were enrolled in th...",The milk composition of each mammary lobe differs in the same breast. When c...,0.4286,0.2500,0.1786,0.2143,0.1667,0.0476,0.5000,0.6667,-0.1667,1.0,1.0,0.0
12,Do T1a breast cancers profit from adjuvant systemic therapy?,"[{'text': '', 'title': '', 'content': 'Recent retrospective studies have sug...",The passages do not contain sufficient information to answer this question.,0.4615,0.3077,0.1538,0.0769,0.3077,-0.2308,0.1667,0.7500,-0.5833,1.0,1.0,0.0
13,Blood donation mobile applications: are donors ready?,"[{'text': '', 'title': '', 'content': 'A total of 982 ethnically diverse res...","According to the passages, 67.7% of respondents indicated that they were lik...",0.6875,0.6154,0.0721,0.3125,0.3077,0.0048,0.4545,0.5000,-0.0455,0.0,1.0,-1.0
14,Increasing mixed chimerism is an important prognostic factor for unfavorable...,"[{'text': '', 'title': '', 'content': 'We recently reported that children wi...","According to Document 1, increasing mixed chimerism (MC) after allogeneic st...",0.4444,0.2500,0.1944,0.2222,0.2500,-0.0278,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
15,Can we target smoking groups more effectively?,"[{'text': '', 'title': '', 'content': 'Identifying ethnic differences in the...","Yes, we can target smoking groups more effectively. Identifying ethnic diffe...",0.9000,0.8571,0.0429,0.8000,0.8571,-0.0571,0.8889,1.0000,-0.1111,0.0,1.0,-1.0
16,Going public: do risk and choice explain differences in caesarean birth rate...,"[{'text': '', 'title': '', 'content': 'women who birthed in Queensland, Aust...","According to the passages, women who birth in private facilities in Australi...",0.8000,0.7000,0.1000,0.7000,0.6000,0.1000,0.8750,0.8571,0.0179,0.0,1.0,-1.0
17,Are the statistical data from Benin's National Tuberculosis Programme reliable?,"[{'text': '', 'title': '', 'content': 'The National Tuberculosis Programme (...",The passages do not contain sufficient information to answer this question.,0.0909,0.1667,-0.0758,0.0000,1.0000,-1.0000,0.0000,1.0000,-1.0000,1.0,1.0,0.0
18,Association of chronic diseases and impairments with disability in older adu...,"[{'text': '', 'title': '', 'content': 'To examine how the associations of ch...",The passages do not contain sufficient information to answer this question.,0.1000,0.6667,-0.5667,0.0000,0.3333,-0.3333,0.0000,0.5000,-0.5000,1.0,1.0,0.0
19,Can metabolic disorders in aging men contribute to prostatic hyperplasia eli...,"[{'text': '', 'title': '', 'content': 'The aim of this study was to evaluate...",The passages do not contain sufficient information to answer this question.,0.1111,0.1111,-0.0000,0.0000,0.1111,-0.1111,0.0000,1.0000,-1.0000,1.0,0.0,1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.4747,0.4885,0.2478,0.2032,0.1818
1,utilization_score,0.2242,0.3699,0.2609,0.2343,0.2174
2,completeness_score,0.3458,0.6849,0.3644,0.2407,0.4420
3,adherence_score,0.4500,0.8500,0.4975,0.3571,0.6000

None

================================================================================
Configuration: pubmedqa_title_aware_v13_balanced
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `pubmedqa_title_aware_v13_balanced`

**name**: pubmedqa_title_aware_v13_balanced  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 200, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-large-en-v1.5', 'dimension': 1024}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 1024}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 75, 'context_window': 2}}, {'type': 'sparse', 'config': {'top_k': 75}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'num_queries': 5, 'model': 'llama-3.3-70b-versatile', 'temperature': 0.5}}, 'fusion': {'type': 'rrf', 'config': {'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 10}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 600, 'system_prompt': 'You are a biomedical question answering assistant.\nYour task is to answer questions using information from the retrieved passages.\n\nINSTRUCTIONS:\n1. Answer ONLY from the passages provided. Do not use external knowledge.\n2. Include all relevant details, findings, and statistics from the passages.\n3. Be concise but thorough — aim for 100-150 words unless more detail is essential.\n4. Do NOT add phrases like "based on general knowledge" or "it is well-established."\n5. Do NOT hedge or qualify your answer unnecessarily.\n6. If the passages do not contain enough information, say: "The passages do not provide sufficient information to answer this question."\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include all relevant details and findings):\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellul...,"[{'text': '', 'title': '', 'content': 'Despite its widespread use in orthopa...","According to the passages, surface porosity and pore size do influence the m...",0.8235,0.6111,0.2124,0.2941,0.5000,-0.2059,0.3571,0.7273,-0.3702,1.0,1.0,0.0
1,Does prosthetic covering of nitinol stents alter healing characteristics or ...,"[{'text': '', 'title': '', 'content': 'To evaluate placement of polyester (D...",The passages suggest that prosthetic covering of nitinol stents may alter he...,0.5000,0.5000,0.0000,0.3333,0.4000,-0.0667,0.6667,0.8000,-0.1333,0.0,0.0,0.0
2,Is diabetes mellitus a negative prognostic factor for the treatment of advan...,"[{'text': '', 'title': '', 'content': 'It has been demonstrated that there a...",The passages do not provide sufficient information to answer this question. ...,0.7273,0.2857,0.4416,0.5455,0.1429,0.4026,0.6250,0.5000,0.1250,0.0,1.0,-1.0
3,Do elderly persons need to be encouraged to drink more fluids?,"[{'text': '', 'title': '', 'content': 'The fluid recommendation for adults a...",The passages suggest that elderly persons may need to be encouraged to drink...,0.3333,0.7692,-0.4359,0.1333,0.4615,-0.3282,0.4000,0.6000,-0.2000,0.0,1.0,-1.0
4,Do the economic and social factors play an important role in relation to the...,"[{'text': '', 'title': '', 'content': 'To evaluate the behavior of contact l...",The passages suggest that economic and social factors may play a role in con...,0.4667,0.7000,-0.2333,0.2000,0.1000,0.1000,0.4286,0.1429,0.2857,0.0,1.0,-1.0
5,Are prostate biopsies mandatory in patients with prostate-specific antigen i...,"[{'text': '', 'title': '', 'content': 'Aim of this study was to evaluate if ...",The passages do not provide sufficient information to answer this question d...,0.5000,0.5000,0.0000,0.5000,0.2500,0.2500,1.0000,0.5000,0.5000,0.0,1.0,-1.0
6,Do working conditions explain the increased risks of disability pension amon...,"[{'text': '', 'title': '', 'content': 'Rates of disability pension are great...","According to Document 2, high physical strain at work and low job control bo...",0.4000,0.4615,-0.0615,0.2000,0.1538,0.0462,0.5000,0.3333,0.1667,0.0,1.0,-1.0
7,Platelet aggregation according to body mass index in patients undergoing cor...,"[{'text': '', 'title': '', 'content': 'A 300 mg clopidogrel loading-dose (LD...",The passages do not provide sufficient information to answer this question. ...,0.4375,0.3750,0.0625,0.1875,0.1875,0.0000,0.2857,0.5000,-0.2143,0.0,1.0,-1.0
8,Interleukin 27 polymorphisms in HCV RNA positive patients: is there an impac...,"[{'text': '', 'title': '', 'content': 'Interleukin 27 (IL-27) has pleiotropi...",The passages do not provide sufficient information to directly answer the qu...,0.5333,0.5333,-0.0000,0.4667,0.5333,-0.0666,0.8750,1.0000,-0.1250,0.0,1.0,-1.0
9,Can the Functional Movement Screen™ be used to capture changes in spine and ...,"[{'text': '', 'title': '', 'content': 'To examine whether objective measures...",The passages suggest that the Functional Movement Screen (FMS) can be used t...,0.6250,0.5714,0.0536,0.3750,0.4286,-0.0536,0.6000,0.7500,-0.1500,0.0,0.0,0.0
10,Is the time interval between surgery and radiotherapy important in operable ...,"[{'text': '', 'title': '', 'content': 'To evaluate the influence of prognost...",The passages suggest that the time interval between surgery and radiotherapy...,0.6364,0.5385,0.0979,0.0909,0.3077,-0.2168,0.1429,0.5714,-0.4285,0.0,1.0,-1.0
11,Comparison of creamatocrit and protein concentration in each mammary lobe of...,"[{'text': '', 'title': '', 'content': 'Seventeen mothers were enrolled in th...",The milk composition of each mammary lobe differs in the same breast. A stud...,0.6429,0.2500,0.3929,0.2143,0.1667,0.0476,0.3333,0.6667,-0.3334,1.0,1.0,0.0
12,Do T1a breast cancers profit from adjuvant systemic therapy?,"[{'text': '', 'title': '', 'content': 'Recent retrospective studies have sug...",The passages do not provide sufficient information to directly answer whethe...,0.5000,0.3077,0.1923,0.4000,0.3077,0.0923,0.8000,0.7500,0.0500,0.0,1.0,-1.0
13,Blood donation mobile applications: are donors ready?,"[{'text': '', 'title': '', 'content': 'A total of 982 ethnically diverse res...","According to the passages, 67.7% of surveyed respondents indicated that they...",0.7333,0.6154,0.1179,0.3333,0.3077,0.0256,0.4545,0.5000,-0.0455,1.0,1.0,0.0
14,Increasing mixed chimerism is an important prognostic factor for unfavorable...,"[{'text': '', 'title': '', 'content': 'We recently reported that children wi...","According to Document 1, increasing mixed chimerism (MC) after allogeneic st...",0.4444,0.2500,0.1944,0.2222,0.2500,-0.0278,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
15,Can we target smoking groups more effectively?,"[{'text': '', 'title': '', 'content': 'Identifying ethnic differences in the...","Yes, targeting smoking groups more effectively is possible. Identifying ethn...",1.0000,0.8571,0.1429,0.5000,0.8571,-0.3571,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
16,Going public: do risk and choice explain differences in caesarean birth rate...,"[{'text': '', 'title': '', 'content': 'women who birthed in Queensland, Aust...","In Australia, women who birth in private facilities are more likely to have ...",0.6154,0.7000,-0.0846,0.3846,0.6000,-0.2154,0.6250,0.8571,-0.2321,0.0,1.0,-1.0
17,Are the statistical data from Benin's National Tuberculosis Programme reliable?,"[{'text': '', 'title': '', 'content': 'The National Tuberculosis Programme (...",The passages do not provide sufficient information to answer this question. ...,0.0909,0.1667,-0.0758,0.0909,1.0000,-0.9091,1.0000,1.0000,0.0000,1.0,1.0,0.0
18,Association of chronic diseases and impairments with disability in older adu...,"[{'text': '', 'title': '', 'content': 'To examine how the associations of ch...",The passages do not provide sufficient information to answer this question. ...,0.7857,0.6667,0.1190,0.3571,0.3333,0.0238,0.4545,0.5000,-0.0455,0.0,1.0,-1.0
19,Can metabolic disorders in aging men contribute to prostatic hyperplasia eli...,"[{'text': '', 'title': '', 'content': 'The aim of this study was to evaluate...",The passages do not provide direct evidence that metabolic disorders in agin...,1.0000,0.1111,0.8889,0.1111,0.1111,-0.0000,0.1111,1.0000,-0.8889,0.0,0.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.5898,0.4885,0.2137,0.2032,0.1904
1,utilization_score,0.2970,0.3699,0.1402,0.2343,0.1718
2,completeness_score,0.5330,0.6849,0.2419,0.2407,0.2647
3,adherence_score,0.2000,0.8500,0.4000,0.3571,0.6500

None

================================================================================
Configuration: pubmedqa_title_aware_v14_pubmedbert_stepback
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `pubmedqa_title_aware_v14_pubmedbert_stepback`

**name**: pubmedqa_title_aware_v14_pubmedbert_stepback  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 200, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 75, 'context_window': 2}}, {'type': 'sparse', 'config': {'top_k': 75}}]}, 'query_transform': {'type': 'step_back', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.3}}, 'fusion': {'type': 'weighted_sum', 'config': {'dense_weight': 0.7, 'sparse_weight': 0.3}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 15}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 600, 'system_prompt': 'You are a biomedical question answering assistant.\nYour task is to answer questions using ONLY information from the retrieved passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use external knowledge.\n2. Include all relevant details, findings, and statistics from the passages.\n3. Be concise but thorough — aim for 100-150 words unless more detail is essential.\n4. Do NOT add phrases like "based on general knowledge" or "it is well-established."\n5. Do NOT hedge or qualify your answer unnecessarily.\n6. If the passages do not contain enough information, respond with: "The passages do not provide sufficient information to answer this question."\n7. Do NOT say "The passages do not contain..." or similar variations — use the exact phrase above.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include all relevant details and findings):\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellul...,"[{'text': '', 'title': '', 'content': 'Despite its widespread use in orthopa...","According to the passages, introducing porosity to PEEK can encourage bone i...",0.5000,0.6111,-0.1111,0.4167,0.5000,-0.0833,0.8333,0.7273,0.1060,0.0,1.0,-1.0
1,Does prosthetic covering of nitinol stents alter healing characteristics or ...,"[{'text': '', 'title': '', 'content': 'To evaluate placement of polyester (D...",The passages do not provide sufficient information to answer this question.,0.0833,0.5000,-0.4167,0.0000,0.4000,-0.4000,0.0000,0.8000,-0.8000,1.0,0.0,1.0
2,Is diabetes mellitus a negative prognostic factor for the treatment of advan...,"[{'text': '', 'title': '', 'content': 'It has been demonstrated that there a...",The passages do not provide sufficient information to answer this question.,0.3571,0.2857,0.0714,0.0000,0.1429,-0.1429,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
3,Do elderly persons need to be encouraged to drink more fluids?,"[{'text': '', 'title': '', 'content': 'A recently published and widely quote...",The passages do not provide sufficient information to answer this question.,0.3333,0.7692,-0.4359,0.0000,0.4615,-0.4615,0.0000,0.6000,-0.6000,0.0,1.0,-1.0
4,Do the economic and social factors play an important role in relation to the...,"[{'text': '', 'title': '', 'content': 'To evaluate the behavior of contact l...",The passages do not provide sufficient information to answer this question.,0.1000,0.7000,-0.6000,0.0000,0.1000,-0.1000,0.0000,0.1429,-0.1429,0.0,1.0,-1.0
5,Are prostate biopsies mandatory in patients with prostate-specific antigen i...,"[{'text': '', 'title': '', 'content': 'Aim of this study was to evaluate if ...",The passages do not provide sufficient information to answer this question.,0.4000,0.5000,-0.1000,0.0000,0.2500,-0.2500,0.0000,0.5000,-0.5000,1.0,1.0,0.0
6,Do working conditions explain the increased risks of disability pension amon...,"[{'text': '', 'title': '', 'content': 'Rates of disability pension are great...","According to Document 2, high physical strain at work and low job control bo...",0.5455,0.4615,0.0840,0.1818,0.1538,0.0280,0.3333,0.3333,-0.0000,0.0,1.0,-1.0
7,Platelet aggregation according to body mass index in patients undergoing cor...,"[{'text': '', 'title': '', 'content': 'A 300 mg clopidogrel loading-dose (LD...",The passages do not provide sufficient information to answer this question.,0.6000,0.3750,0.2250,0.0000,0.1875,-0.1875,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
8,Interleukin 27 polymorphisms in HCV RNA positive patients: is there an impac...,"[{'text': '', 'title': '', 'content': 'Interleukin 27 (IL-27) has pleiotropi...",The passages do not provide sufficient information to answer this question.,0.3846,0.5333,-0.1487,0.0769,0.5333,-0.4564,0.2000,1.0000,-0.8000,1.0,1.0,0.0
9,Can the Functional Movement Screen™ be used to capture changes in spine and ...,"[{'text': '', 'title': '', 'content': 'To examine whether objective measures...",The passages do not provide sufficient information to answer this question.,0.4286,0.5714,-0.1428,0.0000,0.4286,-0.4286,0.0000,0.7500,-0.7500,0.0,0.0,0.0
10,Is the time interval between surgery and radiotherapy important in operable ...,"[{'text': '', 'title': '', 'content': 'To evaluate the influence of prognost...",The passages suggest that the time interval between surgery and radiotherapy...,0.1667,0.5385,-0.3718,0.1667,0.3077,-0.1410,1.0000,0.5714,0.4286,0.0,1.0,-1.0
11,Comparison of creamatocrit and protein concentration in each mammary lobe of...,"[{'text': '', 'title': '', 'content': 'Seventeen mothers were enrolled in th...",The milk composition of each mammary lobe differs in the same breast. A grea...,0.4167,0.2500,0.1667,0.2500,0.1667,0.0833,0.6000,0.6667,-0.0667,1.0,1.0,0.0
12,Do T1a breast cancers profit from adjuvant systemic therapy?,"[{'text': '', 'title': '', 'content': 'With the demonstration that adjuvant ...",The passages do not provide sufficient information to answer this question.,0.3077,0.3077,0.0000,0.0000,0.3077,-0.3077,0.0000,0.7500,-0.7500,1.0,1.0,0.0
13,Blood donation mobile applications: are donors ready?,"[{'text': '', 'title': '', 'content': 'E-mail invitations were sent to blood...",The passages do not provide sufficient information to answer this question.,0.1250,0.6154,-0.4904,0.0000,0.3077,-0.3077,0.0000,0.5000,-0.5000,1.0,1.0,0.0
14,Increasing mixed chimerism is an important prognostic factor for unfavorable...,"[{'text': '', 'title': '', 'content': 'We recently reported that children wi...","According to Document 1, increasing mixed chimerism (MC) after allogeneic st...",0.3750,0.2500,0.1250,0.2500,0.2500,0.0000,0.6667,1.0000,-0.3333,1.0,1.0,0.0
15,Can we target smoking groups more effectively?,"[{'text': '', 'title': '', 'content': 'Identifying ethnic differences in the...",The passages suggest that targeting smoking groups more effectively is possi...,0.8333,0.8571,-0.0238,0.6667,0.8571,-0.1904,0.8000,1.0000,-0.2000,0.0,1.0,-1.0
16,Going public: do risk and choice explain differences in caesarean birth rate...,"[{'text': '', 'title': '', 'content': 'women who birthed in Queensland, Aust...","According to the passages, women who birth in private facilities in Australi...",0.4545,0.7000,-0.2455,0.3636,0.6000,-0.2364,0.8000,0.8571,-0.0571,0.0,1.0,-1.0
17,Are the statistical data from Benin's National Tuberculosis Programme reliable?,"[{'text': '', 'title': '', 'content': 'We gathered normative guidance and re...",The passages do not provide sufficient information to answer this question.,0.1333,0.1667,-0.0334,0.0000,1.0000,-1.0000,0.0000,1.0000,-1.0000,1.0,1.0,0.0
18,Association of chronic diseases and impairments with disability in older adu...,"[{'text': '', 'title': '', 'content': 'To examine how the associations of ch...",The passages do not provide sufficient information to answer this question.,0.2857,0.6667,-0.3810,0.0000,0.3333,-0.3333,0.0000,0.5000,-0.5000,1.0,1.0,0.0
19,Can metabolic disorders in aging men contribute to prostatic hyperplasia eli...,"[{'text': '', 'title': '', 'content': 'The aim of this study was to evaluate...",The passages do not provide sufficient information to answer this question.,0.1111,0.1111,-0.0000,0.0000,0.1111,-0.1111,0.0000,1.0000,-1.0000,1.0,0.0,1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3471,0.4885,0.1885,0.2032,0.2087
1,utilization_score,0.1186,0.3699,0.1818,0.2343,0.2625
2,completeness_score,0.2617,0.6849,0.3578,0.2407,0.4767
3,adherence_score,0.5000,0.8500,0.5000,0.3571,0.5500

None

================================================================================
Configuration: pubmedqa_title_aware_v15_biomedical_reranker
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `pubmedqa_title_aware_v15_biomedical_reranker`

**name**: pubmedqa_title_aware_v15_biomedical_reranker  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 200, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 75, 'context_window': 2, 'min_similarity': 0.5}}, {'type': 'sparse', 'config': {'top_k': 75}}]}, 'query_transform': {'type': 'step_back', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.3}}, 'fusion': {'type': 'weighted_sum', 'config': {'dense_weight': 0.7, 'sparse_weight': 0.3}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-large', 'top_k': 15}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 600, 'system_prompt': 'You are a biomedical question answering assistant.\nYour task is to answer questions using ONLY information from the retrieved passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use external knowledge.\n2. Include all relevant details, findings, and statistics from the passages.\n3. Be concise but thorough — aim for 100-150 words unless more detail is essential.\n4. Do NOT add phrases like "based on general knowledge" or "it is well-established."\n5. Do NOT hedge or qualify your answer unnecessarily.\n6. If the passages do not contain enough information, respond with: "The passages do not provide sufficient information to answer this question."\n7. Do NOT say "The passages do not contain..." or similar variations — use the exact phrase above.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include all relevant details and findings):\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellul...,"[{'text': '', 'title': '', 'content': '(1) Can surface porous PEEK (PEEK-SP)...",The passages suggest that surface porosity and pore size may influence the m...,0.5833,0.6111,-0.0278,0.5000,0.5000,0.0000,0.8571,0.7273,0.1298,0.0,1.0,-1.0
1,Does prosthetic covering of nitinol stents alter healing characteristics or ...,"[{'text': '', 'title': '', 'content': 'To evaluate placement of polyester (D...",The passages do not provide sufficient information to answer this question.,0.0833,0.5000,-0.4167,0.0000,0.4000,-0.4000,0.0000,0.8000,-0.8000,1.0,0.0,1.0
2,Is diabetes mellitus a negative prognostic factor for the treatment of advan...,"[{'text': '', 'title': '', 'content': 'It has been demonstrated that there a...",The passages do not provide sufficient information to answer this question.,0.5385,0.2857,0.2528,0.1538,0.1429,0.0109,0.2857,0.5000,-0.2143,1.0,1.0,0.0
3,Do elderly persons need to be encouraged to drink more fluids?,"[{'text': '', 'title': '', 'content': 'A recently published and widely quote...",The passages do not provide sufficient information to answer this question.,0.2857,0.7692,-0.4835,0.0000,0.4615,-0.4615,0.0000,0.6000,-0.6000,0.0,1.0,-1.0
4,Do the economic and social factors play an important role in relation to the...,"[{'text': '', 'title': '', 'content': 'To evaluate the behavior of contact l...",The passages do not provide sufficient information to answer this question.,0.1000,0.7000,-0.6000,0.0000,0.1000,-0.1000,0.0000,0.1429,-0.1429,1.0,1.0,0.0
5,Are prostate biopsies mandatory in patients with prostate-specific antigen i...,"[{'text': '', 'title': '', 'content': 'Aim of this study was to evaluate if ...",The passages do not provide sufficient information to answer this question.,0.3750,0.5000,-0.1250,0.0000,0.2500,-0.2500,0.0000,0.5000,-0.5000,1.0,1.0,0.0
6,Do working conditions explain the increased risks of disability pension amon...,"[{'text': '', 'title': '', 'content': 'Rates of disability pension are great...","According to Document 2, high physical strain at work and low job control bo...",0.5455,0.4615,0.0840,0.2727,0.1538,0.1189,0.5000,0.3333,0.1667,0.0,1.0,-1.0
7,Platelet aggregation according to body mass index in patients undergoing cor...,"[{'text': '', 'title': '', 'content': 'A 300 mg clopidogrel loading-dose (LD...",The passages do not provide sufficient information to answer this question.,0.6000,0.3750,0.2250,0.0000,0.1875,-0.1875,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
8,Interleukin 27 polymorphisms in HCV RNA positive patients: is there an impac...,"[{'text': '', 'title': '', 'content': 'Interleukin 27 (IL-27) has pleiotropi...",The passages do not provide sufficient information to answer this question.,0.3846,0.5333,-0.1487,0.0769,0.5333,-0.4564,0.2000,1.0000,-0.8000,1.0,1.0,0.0
9,Can the Functional Movement Screen™ be used to capture changes in spine and ...,"[{'text': '', 'title': '', 'content': 'To examine whether objective measures...",The passages do not provide sufficient information to answer this question.,0.1250,0.5714,-0.4464,0.0000,0.4286,-0.4286,0.0000,0.7500,-0.7500,1.0,0.0,1.0
10,Is the time interval between surgery and radiotherapy important in operable ...,"[{'text': '', 'title': '', 'content': 'To evaluate the influence of prognost...",The passages do not provide sufficient information to answer this question.,0.2000,0.5385,-0.3385,0.0000,0.3077,-0.3077,0.0000,0.5714,-0.5714,1.0,1.0,0.0
11,Comparison of creamatocrit and protein concentration in each mammary lobe of...,"[{'text': '', 'title': '', 'content': 'Seventeen mothers were enrolled in th...",The milk composition of each mammary lobe differs in the same breast. A grea...,0.4167,0.2500,0.1667,0.4167,0.1667,0.2500,1.0000,0.6667,0.3333,0.0,1.0,-1.0
12,Do T1a breast cancers profit from adjuvant systemic therapy?,"[{'text': '', 'title': '', 'content': 'With the demonstration that adjuvant ...",The passages do not provide sufficient information to answer this question.,0.3077,0.3077,0.0000,0.0000,0.3077,-0.3077,0.0000,0.7500,-0.7500,1.0,1.0,0.0
13,Blood donation mobile applications: are donors ready?,"[{'text': '', 'title': '', 'content': 'E-mail invitations were sent to blood...",The passages do not provide sufficient information to answer this question.,0.1250,0.6154,-0.4904,0.1250,0.3077,-0.1827,1.0000,0.5000,0.5000,1.0,1.0,0.0
14,Increasing mixed chimerism is an important prognostic factor for unfavorable...,"[{'text': '', 'title': '', 'content': 'We recently reported that children wi...",Children with acute leukemias who show increasing mixed chimerism (MC) after...,0.2500,0.2500,0.0000,0.2500,0.2500,0.0000,1.0000,1.0000,0.0000,1.0,1.0,0.0
15,Can we target smoking groups more effectively?,"[{'text': '', 'title': '', 'content': 'Identifying ethnic differences in the...",The passages suggest that targeting smoking groups more effectively is possi...,1.0000,0.8571,0.1429,1.0000,0.8571,0.1429,1.0000,1.0000,0.0000,0.0,1.0,-1.0
16,Going public: do risk and choice explain differences in caesarean birth rate...,"[{'text': '', 'title': '', 'content': 'women who birth in private facilities...","In Australia, women who give birth in private facilities are more likely to ...",0.4545,0.7000,-0.2455,0.2727,0.6000,-0.3273,0.6000,0.8571,-0.2571,0.0,1.0,-1.0
17,Are the statistical data from Benin's National Tuberculosis Programme reliable?,"[{'text': '', 'title': '', 'content': 'To explore the utility of using natio...",The passages do not provide sufficient information to answer this question.,0.0000,0.1667,-0.1667,0.0000,1.0000,-1.0000,0.0000,1.0000,-1.0000,1.0,1.0,0.0
18,Association of chronic diseases and impairments with disability in older adu...,"[{'text': '', 'title': '', 'content': 'To examine how the associations of ch...",The passages do not provide sufficient information to answer this question.,0.2857,0.6667,-0.3810,0.0000,0.3333,-0.3333,0.0000,0.5000,-0.5000,1.0,1.0,0.0
19,Can metabolic disorders in aging men contribute to prostatic hyperplasia eli...,"[{'text': '', 'title': '', 'content': 'The aim of this study was to evaluate...",The passages do not provide sufficient information to answer this question.,0.2222,0.1111,0.1111,0.0000,0.1111,-0.1111,0.0000,1.0000,-1.0000,1.0,0.0,1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3441,0.4885,0.2287,0.2032,0.2426
1,utilization_score,0.1534,0.3699,0.2459,0.2343,0.2688
2,completeness_score,0.3221,0.6849,0.4118,0.2407,0.4758
3,adherence_score,0.6500,0.8500,0.4770,0.3571,0.5000

None

================================================================================
Configuration: pubmedqa_title_aware_v16_improved_retrieval
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `pubmedqa_title_aware_v16_improved_retrieval`

**name**: pubmedqa_title_aware_v16_improved_retrieval  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 200, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 100, 'context_window': 2, 'min_similarity': 0.4}}, {'type': 'sparse', 'config': {'top_k': 100}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'num_queries': 5, 'model': 'llama-3.3-70b-versatile', 'temperature': 0.5}}, 'fusion': {'type': 'weighted_sum', 'config': {'dense_weight': 0.7, 'sparse_weight': 0.3}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 25}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 800, 'system_prompt': 'You are a biomedical question answering assistant.\nYour task is to answer questions using ONLY information from the retrieved passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use external knowledge.\n2. Include ALL relevant details, findings, statistics, and information from the passages.\n3. Be thorough and comprehensive — aim for 200-300 words to cover all relevant aspects.\n4. Do NOT add phrases like "based on general knowledge" or "it is well-established."\n5. Do NOT hedge or qualify your answer unnecessarily.\n6. If the passages do not contain enough information, respond with: "The passages do not provide sufficient information to answer this question."\n7. Do NOT say "The passages do not contain..." or similar variations — use the exact phrase above.\n8. Use multiple passages to build a comprehensive answer that addresses all aspects of the question.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include ALL relevant details, findings, and information):\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellul...,"[{'text': '', 'title': '', 'content': 'Despite its widespread use in orthopa...","According to the passages, surface porosity and pore size do influence the m...",0.7368,0.6111,0.1257,0.5789,0.5000,0.0789,0.7857,0.7273,0.0584,0.0,1.0,-1.0
1,Does prosthetic covering of nitinol stents alter healing characteristics or ...,"[{'text': '', 'title': '', 'content': 'To evaluate placement of polyester (D...",The passages provide information on the evaluation of prosthetic coverings o...,0.6667,0.5000,0.1667,0.5000,0.4000,0.1000,0.7500,0.8000,-0.0500,0.0,0.0,0.0
2,Is diabetes mellitus a negative prognostic factor for the treatment of advan...,"[{'text': '', 'title': '', 'content': 'It has been demonstrated that there a...",The passages do not provide sufficient information to answer this question.,0.5385,0.2857,0.2528,0.0000,0.1429,-0.1429,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
3,Do elderly persons need to be encouraged to drink more fluids?,"[{'text': '', 'title': '', 'content': 'Dehydration in older adults contribut...",The passages do not provide sufficient information to answer this question.,0.3000,0.7692,-0.4692,0.0000,0.4615,-0.4615,0.0000,0.6000,-0.6000,1.0,1.0,0.0
4,Do the economic and social factors play an important role in relation to the...,"[{'text': '', 'title': '', 'content': 'To evaluate the behavior of contact l...",The passages suggest that economic and social factors may play a role in hea...,0.8889,0.7000,0.1889,0.8889,0.1000,0.7889,1.0000,0.1429,0.8571,0.0,1.0,-1.0
5,Are prostate biopsies mandatory in patients with prostate-specific antigen i...,"[{'text': '', 'title': '', 'content': 'The objective of this study was to ev...",The passages do not provide sufficient information to answer this question.,0.5000,0.5000,0.0000,0.0000,0.2500,-0.2500,0.0000,0.5000,-0.5000,1.0,1.0,0.0
6,Do working conditions explain the increased risks of disability pension amon...,"[{'text': '', 'title': '', 'content': 'Rates of disability pension are great...","According to the passages, working conditions do contribute to explaining th...",0.6364,0.4615,0.1749,0.3636,0.1538,0.2098,0.5714,0.3333,0.2381,0.0,1.0,-1.0
7,Platelet aggregation according to body mass index in patients undergoing cor...,"[{'text': '', 'title': '', 'content': 'A 300 mg clopidogrel loading-dose (LD...",The passages suggest that the relationship between body mass index (BMI) and...,0.4000,0.3750,0.0250,0.3333,0.1875,0.1458,0.8333,0.5000,0.3333,0.0,1.0,-1.0
8,Interleukin 27 polymorphisms in HCV RNA positive patients: is there an impac...,"[{'text': '', 'title': '', 'content': 'Interleukin 27 (IL-27) has pleiotropi...",The passages provide some information about the relationship between interle...,0.5000,0.5333,-0.0333,0.5833,0.5333,0.0500,0.8333,1.0000,-0.1667,0.0,1.0,-1.0
9,Can the Functional Movement Screen™ be used to capture changes in spine and ...,"[{'text': '', 'title': '', 'content': 'To examine whether objective measures...",The Functional Movement Screen (FMS) was used to examine changes in spine an...,0.8571,0.5714,0.2857,0.7143,0.4286,0.2857,0.8333,0.7500,0.0833,0.0,0.0,0.0
10,Is the time interval between surgery and radiotherapy important in operable ...,"[{'text': '', 'title': '', 'content': 'To evaluate the influence of prognost...",The passages suggest that the time interval between surgery and radiotherapy...,0.1111,0.5385,-0.4274,0.5556,0.3077,0.2479,1.0000,0.5714,0.4286,0.0,1.0,-1.0
11,Comparison of creamatocrit and protein concentration in each mammary lobe of...,"[{'text': '', 'title': '', 'content': 'Seventeen mothers were enrolled in th...",The passages indicate that the milk composition of each mammary lobe can dif...,0.4286,0.2500,0.1786,0.3571,0.1667,0.1904,0.8333,0.6667,0.1666,0.0,1.0,-1.0
12,Do T1a breast cancers profit from adjuvant systemic therapy?,"[{'text': '', 'title': '', 'content': 'With the demonstration that adjuvant ...",The passages provide information on the treatment and prognosis of breast ca...,0.4444,0.3077,0.1367,0.4444,0.3077,0.1367,1.0000,0.7500,0.2500,0.0,1.0,-1.0
13,Blood donation mobile applications: are donors ready?,"[{'text': '', 'title': '', 'content': 'E-mail invitations were sent to blood...",The passages provide some information related to blood donation mobile appli...,0.1818,0.6154,-0.4336,0.3636,0.3077,0.0559,1.0000,0.5000,0.5000,0.0,1.0,-1.0
14,Increasing mixed chimerism is an important prognostic factor for unfavorable...,"[{'text': '', 'title': '', 'content': 'We recently reported that children wi...","According to the passages, increasing mixed chimerism (MC) is indeed an impo...",0.5556,0.2500,0.3056,0.2222,0.2500,-0.0278,0.4000,1.0000,-0.6000,0.0,1.0,-1.0
15,Can we target smoking groups more effectively?,"[{'text': '', 'title': '', 'content': 'Identifying ethnic differences in the...","Targeting smoking groups more effectively is a possibility, as identifying e...",0.5556,0.8571,-0.3015,0.5556,0.8571,-0.3015,0.8000,1.0000,-0.2000,0.0,1.0,-1.0
16,Going public: do risk and choice explain differences in caesarean birth rate...,"[{'text': '', 'title': '', 'content': 'women who birthed in Queensland, Aust...","In Australia, women who birth in private facilities are more likely to have ...",0.4545,0.7000,-0.2455,0.4545,0.6000,-0.1455,1.0000,0.8571,0.1429,0.0,1.0,-1.0
17,Are the statistical data from Benin's National Tuberculosis Programme reliable?,"[{'text': '', 'title': '', 'content': 'National tuberculosis (TB) programmes...",The passages do not provide sufficient information to answer this question.,0.2500,0.1667,0.0833,0.0000,1.0000,-1.0000,0.0000,1.0000,-1.0000,1.0,1.0,0.0
18,Association of chronic diseases and impairments with disability in older adu...,"[{'text': '', 'title': '', 'content': 'To examine how the associations of ch...",The association of chronic diseases and impairments with disability in older...,0.5000,0.6667,-0.1667,0.6250,0.3333,0.2917,0.7500,0.5000,0.2500,0.0,1.0,-1.0
19,Can metabolic disorders in aging men contribute to prostatic hyperplasia eli...,"[{'text': '', 'title': '', 'content': 'The aim of this study was to evaluate...",The passages provide some information related to the question. According to ...,0.1250,0.1111,0.0139,1.0000,0.1111,0.8889,1.0000,1.0000,0.0000,0.0,0.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.4815,0.4885,0.2119,0.2032,0.2007
1,utilization_score,0.4270,0.3699,0.2778,0.2343,0.2900
2,completeness_score,0.6695,0.6849,0.3662,0.2407,0.3462
3,adherence_score,0.1500,0.8500,0.3571,0.3571,0.7000

None

================================================================================
Configuration: pubmedqa_title_aware_v17_hybrid_transform
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `pubmedqa_title_aware_v17_hybrid_transform`

**name**: pubmedqa_title_aware_v17_hybrid_transform  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 200, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 100, 'context_window': 2, 'min_similarity': 0.45}}, {'type': 'sparse', 'config': {'top_k': 100}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'num_queries': 5, 'model': 'llama-3.3-70b-versatile', 'temperature': 0.3}}, 'fusion': {'type': 'weighted_sum', 'config': {'dense_weight': 0.7, 'sparse_weight': 0.3}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 25}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 750, 'system_prompt': 'You are a biomedical question answering assistant.\nYour task is to answer questions using ONLY information from the retrieved passages.\n\nCRITICAL RULES (MUST FOLLOW ALL):\n1. Answer ONLY from the passages provided. Do not use external knowledge.\n2. Include ALL relevant details, findings, statistics, and information from the passages.\n3. Be thorough and comprehensive — aim for 175-250 words to cover all relevant aspects.\n4. Do NOT add phrases like "based on general knowledge", "it is well-established", "it is known that", or "research shows".\n5. Do NOT hedge or qualify your answer with "may", "might", "could", "possibly", "suggests", "indicates" unless explicitly stated in passages.\n6. If the passages do not contain enough information, respond with: "The passages do not provide sufficient information to answer this question."\n7. Do NOT say "The passages do not contain..." or similar variations — use the exact phrase above.\n8. Use multiple passages to build a comprehensive answer that addresses all aspects of the question.\n9. Every claim must be directly traceable to the passages provided.\n10. Do NOT add interpretations, conclusions, or inferences not explicitly stated in the passages.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include ALL relevant details, findings, and information):\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellul...,"[{'text': '', 'title': '', 'content': 'Despite its widespread use in orthopa...",Surface porosity and pore size do influence the mechanical properties and ce...,0.8235,0.6111,0.2124,0.7059,0.5000,0.2059,0.8571,0.7273,0.1298,0.0,1.0,-1.0
1,Does prosthetic covering of nitinol stents alter healing characteristics or ...,"[{'text': '', 'title': '', 'content': 'To evaluate placement of polyester (D...",The passages provide information on the evaluation of prosthetic coverings o...,0.2727,0.5000,-0.2273,0.2727,0.4000,-0.1273,0.6667,0.8000,-0.1333,0.0,0.0,0.0
2,Is diabetes mellitus a negative prognostic factor for the treatment of advan...,"[{'text': '', 'title': '', 'content': 'It has been demonstrated that there a...",The passages do not provide sufficient information to answer this question.,0.5833,0.2857,0.2976,0.1667,0.1429,0.0238,0.2857,0.5000,-0.2143,1.0,1.0,0.0
3,Do elderly persons need to be encouraged to drink more fluids?,"[{'text': '', 'title': '', 'content': 'Dehydration in older adults contribut...",The passages do not provide sufficient information to answer this question.,0.2500,0.7692,-0.5192,0.0000,0.4615,-0.4615,0.0000,0.6000,-0.6000,1.0,1.0,0.0
4,Do the economic and social factors play an important role in relation to the...,"[{'text': '', 'title': '', 'content': 'To evaluate the behavior of contact l...",The passages do not provide sufficient information to answer this question.,0.3333,0.7000,-0.3667,0.0000,0.1000,-0.1000,0.0000,0.1429,-0.1429,1.0,1.0,0.0
5,Are prostate biopsies mandatory in patients with prostate-specific antigen i...,"[{'text': '', 'title': '', 'content': 'Aim of this study was to evaluate if ...",The passages do not provide sufficient information to answer this question.,0.5556,0.5000,0.0556,0.0000,0.2500,-0.2500,0.0000,0.5000,-0.5000,0.0,1.0,-1.0
6,Do working conditions explain the increased risks of disability pension amon...,"[{'text': '', 'title': '', 'content': 'Rates of disability pension are great...","According to the passages, working conditions do contribute to explaining th...",0.7857,0.4615,0.3242,0.2857,0.1538,0.1319,0.3636,0.3333,0.0303,0.0,1.0,-1.0
7,Platelet aggregation according to body mass index in patients undergoing cor...,"[{'text': '', 'title': '', 'content': 'A 300 mg clopidogrel loading-dose (LD...",The passages do not provide sufficient information to answer this question.,0.6667,0.3750,0.2917,0.0000,0.1875,-0.1875,0.0000,0.5000,-0.5000,1.0,1.0,0.0
8,Interleukin 27 polymorphisms in HCV RNA positive patients: is there an impac...,"[{'text': '', 'title': '', 'content': 'Interleukin 27 (IL-27) has pleiotropi...",The passages provide some information about the relationship between Interle...,0.5000,0.5333,-0.0333,0.7000,0.5333,0.1667,0.6000,1.0000,-0.4000,0.0,1.0,-1.0
9,Can the Functional Movement Screen™ be used to capture changes in spine and ...,"[{'text': '', 'title': '', 'content': 'To examine whether objective measures...",The Functional Movement Screen (FMS) was used to examine changes in spine an...,0.8571,0.5714,0.2857,0.7143,0.4286,0.2857,0.8333,0.7500,0.0833,0.0,0.0,0.0
10,Is the time interval between surgery and radiotherapy important in operable ...,"[{'text': '', 'title': '', 'content': 'To evaluate the influence of prognost...",The passages do not provide sufficient information to answer this question.,0.1250,0.5385,-0.4135,0.0000,0.3077,-0.3077,0.0000,0.5714,-0.5714,1.0,1.0,0.0
11,Comparison of creamatocrit and protein concentration in each mammary lobe of...,"[{'text': '', 'title': '', 'content': 'Seventeen mothers were enrolled in th...",The passages provide information on the study of milk composition in differe...,0.5455,0.2500,0.2955,0.5455,0.1667,0.3788,1.0000,0.6667,0.3333,0.0,1.0,-1.0
12,Do T1a breast cancers profit from adjuvant systemic therapy?,"[{'text': '', 'title': '', 'content': 'With the demonstration that adjuvant ...",The passages do not provide sufficient information to answer this question.,0.4000,0.3077,0.0923,0.0000,0.3077,-0.3077,0.0000,0.7500,-0.7500,1.0,1.0,0.0
13,Blood donation mobile applications: are donors ready?,"[{'text': '', 'title': '', 'content': 'E-mail invitations were sent to blood...",E-mail invitations were sent to blood donors in a large metropolitan area to...,0.4444,0.6154,-0.1710,0.4444,0.3077,0.1367,1.0000,0.5000,0.5000,0.0,1.0,-1.0
14,Increasing mixed chimerism is an important prognostic factor for unfavorable...,"[{'text': '', 'title': '', 'content': 'We recently reported that children wi...","According to Document 1, increasing mixed chimerism (MC) after allogeneic st...",0.4444,0.2500,0.1944,0.2222,0.2500,-0.0278,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
15,Can we target smoking groups more effectively?,"[{'text': '', 'title': '', 'content': 'To compare smoking-cessation interest...",The passages provide information on smoking cessation and potential strategi...,0.5714,0.8571,-0.2857,0.4286,0.8571,-0.4285,0.7500,1.0000,-0.2500,0.0,1.0,-1.0
16,Going public: do risk and choice explain differences in caesarean birth rate...,"[{'text': '', 'title': '', 'content': 'women who birthed in Queensland, Aust...","According to the passages, women who birth in private facilities in Australi...",0.4167,0.7000,-0.2833,0.3333,0.6000,-0.2667,0.8000,0.8571,-0.0571,0.0,1.0,-1.0
17,Are the statistical data from Benin's National Tuberculosis Programme reliable?,"[{'text': '', 'title': '', 'content': 'National tuberculosis (TB) programmes...",The passages do not provide sufficient information to answer this question.,0.3333,0.1667,0.1666,0.0000,1.0000,-1.0000,0.0000,1.0000,-1.0000,1.0,1.0,0.0
18,Association of chronic diseases and impairments with disability in older adu...,"[{'text': '', 'title': '', 'content': 'To examine how the associations of ch...",The passages do not provide sufficient information to answer this question.,0.2000,0.6667,-0.4667,0.0000,0.3333,-0.3333,0.0000,0.5000,-0.5000,1.0,1.0,0.0
19,Can metabolic disorders in aging men contribute to prostatic hyperplasia eli...,"[{'text': '', 'title': '', 'content': 'The aim of this study was to evaluate...",The passages do not provide sufficient information to answer this question.,0.1111,0.1111,-0.0000,0.0000,0.1111,-0.1111,0.0000,1.0000,-1.0000,1.0,0.0,1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.4610,0.4885,0.2125,0.2032,0.2491
1,utilization_score,0.2410,0.3699,0.2608,0.2343,0.2619
2,completeness_score,0.3828,0.6849,0.3853,0.2407,0.4098
3,adherence_score,0.4500,0.8500,0.4975,0.3571,0.5000

None

================================================================================
Configuration: pubmedqa_title_aware_v18_balanced
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `pubmedqa_title_aware_v18_balanced`

**name**: pubmedqa_title_aware_v18_balanced  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 200, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 90, 'context_window': 2, 'min_similarity': 0.45}}, {'type': 'sparse', 'config': {'top_k': 90}}]}, 'query_transform': {'type': 'multi_query', 'provider': 'groq', 'config': {'num_queries': 5, 'model': 'llama-3.3-70b-versatile', 'temperature': 0.4}}, 'fusion': {'type': 'weighted_sum', 'config': {'dense_weight': 0.7, 'sparse_weight': 0.3}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 22}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 750, 'system_prompt': 'You are a biomedical question answering assistant.\nYour task is to answer questions using ONLY information from the retrieved passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use external knowledge.\n2. Include ALL relevant details, findings, statistics, and information from the passages.\n3. Be thorough and comprehensive — aim for 175-250 words to cover all relevant aspects.\n4. Do NOT add phrases like "based on general knowledge" or "it is well-established."\n5. Do NOT hedge or qualify your answer unnecessarily.\n6. If the passages do not contain enough information, respond with: "The passages do not provide sufficient information to answer this question."\n7. Do NOT say "The passages do not contain..." or similar variations — use the exact phrase above.\n8. Use multiple passages to build a comprehensive answer that addresses all aspects of the question.\n9. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include ALL relevant details, findings, and information):\n'}}  •  **evaluation**: None  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,Do Surface Porosity and Pore Size Influence Mechanical Properties and Cellul...,"[{'text': '', 'title': '', 'content': 'Despite its widespread use in orthopa...","According to the passages, surface porosity and pore size do influence the m...",0.8235,0.6111,0.2124,0.4118,0.5000,-0.0882,0.5000,0.7273,-0.2273,0.0,1.0,-1.0
1,Does prosthetic covering of nitinol stents alter healing characteristics or ...,"[{'text': '', 'title': '', 'content': 'To evaluate placement of polyester (D...",The passages provide information on the evaluation of prosthetic coverings o...,0.5556,0.5000,0.0556,0.3333,0.4000,-0.0667,0.6000,0.8000,-0.2000,0.0,0.0,0.0
2,Is diabetes mellitus a negative prognostic factor for the treatment of advan...,"[{'text': '', 'title': '', 'content': 'It has been demonstrated that there a...",The passages do not provide sufficient information to answer this question.,0.3636,0.2857,0.0779,0.0909,0.1429,-0.0520,0.2500,0.5000,-0.2500,1.0,1.0,0.0
3,Do elderly persons need to be encouraged to drink more fluids?,"[{'text': '', 'title': '', 'content': 'Dehydration in older adults contribut...",The passages do not provide sufficient information to answer this question.,0.3333,0.7692,-0.4359,0.0000,0.4615,-0.4615,0.0000,0.6000,-0.6000,1.0,1.0,0.0
4,Do the economic and social factors play an important role in relation to the...,"[{'text': '', 'title': '', 'content': 'To evaluate the behavior of contact l...",The passages do not provide sufficient information to answer this question.,0.0909,0.7000,-0.6091,0.0000,0.1000,-0.1000,0.0000,0.1429,-0.1429,1.0,1.0,0.0
5,Are prostate biopsies mandatory in patients with prostate-specific antigen i...,"[{'text': '', 'title': '', 'content': 'Aim of this study was to evaluate if ...",The passages suggest that prostate biopsies may not be mandatory in patients...,0.6667,0.5000,0.1667,0.4444,0.2500,0.1944,0.6667,0.5000,0.1667,0.0,1.0,-1.0
6,Do working conditions explain the increased risks of disability pension amon...,"[{'text': '', 'title': '', 'content': 'Rates of disability pension are great...","According to the passages, working conditions do contribute to explaining th...",0.5000,0.4615,0.0385,0.2857,0.1538,0.1319,0.5714,0.3333,0.2381,0.0,1.0,-1.0
7,Platelet aggregation according to body mass index in patients undergoing cor...,"[{'text': '', 'title': '', 'content': 'A 300 mg clopidogrel loading-dose (LD...",The passages suggest that the relationship between body mass index (BMI) and...,0.7143,0.3750,0.3393,1.0000,0.1875,0.8125,1.0000,0.5000,0.5000,0.0,1.0,-1.0
8,Interleukin 27 polymorphisms in HCV RNA positive patients: is there an impac...,"[{'text': '', 'title': '', 'content': 'Interleukin 27 (IL-27) has pleiotropi...",The passages provide some information about the relationship between interle...,0.7000,0.5333,0.1667,0.6000,0.5333,0.0667,0.8571,1.0000,-0.1429,0.0,1.0,-1.0
9,Can the Functional Movement Screen™ be used to capture changes in spine and ...,"[{'text': '', 'title': '', 'content': 'To examine whether objective measures...",The Functional Movement Screen (FMS) can be used to capture changes in spine...,0.8571,0.5714,0.2857,0.7143,0.4286,0.2857,0.8333,0.7500,0.0833,0.0,0.0,0.0
10,Is the time interval between surgery and radiotherapy important in operable ...,"[{'text': '', 'title': '', 'content': 'To evaluate the influence of prognost...",The passages provide some information related to the question. According to ...,0.3333,0.5385,-0.2052,0.1667,0.3077,-0.1410,0.5000,0.5714,-0.0714,0.0,1.0,-1.0
11,Comparison of creamatocrit and protein concentration in each mammary lobe of...,"[{'text': '', 'title': '', 'content': 'Seventeen mothers were enrolled in th...",The passages provide information on a study that measured creamatocrit (CrCt...,0.4286,0.2500,0.1786,0.4286,0.1667,0.2619,1.0000,0.6667,0.3333,0.0,1.0,-1.0
12,Do T1a breast cancers profit from adjuvant systemic therapy?,"[{'text': '', 'title': '', 'content': 'With the demonstration that adjuvant ...",The passages do not provide sufficient information to answer this question.,0.4444,0.3077,0.1367,0.0000,0.3077,-0.3077,0.0000,0.7500,-0.7500,1.0,1.0,0.0
13,Blood donation mobile applications: are donors ready?,"[{'text': '', 'title': '', 'content': 'E-mail invitations were sent to blood...",The passages suggest that blood donors may be ready for a blood donation mob...,0.2727,0.6154,-0.3427,0.9091,0.3077,0.6014,1.0000,0.5000,0.5000,0.0,1.0,-1.0
14,Increasing mixed chimerism is an important prognostic factor for unfavorable...,"[{'text': '', 'title': '', 'content': 'We recently reported that children wi...","According to the passages, increasing mixed chimerism (MC) is indeed an impo...",0.6667,0.2500,0.4167,0.4444,0.2500,0.1944,0.6667,1.0000,-0.3333,0.0,1.0,-1.0
15,Can we target smoking groups more effectively?,"[{'text': '', 'title': '', 'content': 'Identifying ethnic differences in the...",Targeting smoking groups more effectively is a crucial aspect of combating s...,0.8333,0.8571,-0.0238,0.6667,0.8571,-0.1904,0.8000,1.0000,-0.2000,0.0,1.0,-1.0
16,Going public: do risk and choice explain differences in caesarean birth rate...,"[{'text': '', 'title': '', 'content': 'women who birthed in Queensland, Aust...","According to the passages, women who birth in private facilities in Australi...",0.4167,0.7000,-0.2833,0.4167,0.6000,-0.1833,1.0000,0.8571,0.1429,0.0,1.0,-1.0
17,Are the statistical data from Benin's National Tuberculosis Programme reliable?,"[{'text': '', 'title': '', 'content': 'National tuberculosis (TB) programmes...",The passages do not provide sufficient information to answer this question.,0.3333,0.1667,0.1666,0.0000,1.0000,-1.0000,0.0000,1.0000,-1.0000,1.0,1.0,0.0
18,Association of chronic diseases and impairments with disability in older adu...,"[{'text': '', 'title': '', 'content': 'To examine how the associations of ch...",The association of chronic diseases and impairments with disability in older...,0.5000,0.6667,-0.1667,0.5000,0.3333,0.1667,0.7500,0.5000,0.2500,0.0,1.0,-1.0
19,Can metabolic disorders in aging men contribute to prostatic hyperplasia eli...,"[{'text': '', 'title': '', 'content': 'The aim of this study was to evaluate...",The passages do not provide sufficient information to answer this question.,0.1250,0.1111,0.0139,0.0000,0.1111,-0.1111,0.0000,1.0000,-1.0000,1.0,0.0,1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.4980,0.4885,0.2196,0.2032,0.2161
1,utilization_score,0.3706,0.3699,0.2995,0.2343,0.2709
2,completeness_score,0.5498,0.6849,0.3691,0.2407,0.3566
3,adherence_score,0.3000,0.8500,0.4583,0.3571,0.6500

None

## 10. Compare Configurations

Generate a comparison report across all configurations to see which performs best.

In [11]:
# Generate comparison report
print("Generating comparison report...")
comparison = runner.compare()

print(f"\n✅ Comparison report generated!")
print(f"  Saved to: {experiment_config.report_dir}/comparison.csv")

Generating comparison report...

✅ Comparison report generated!
  Saved to: rag-experiments/pubmedqa-experiment/reports/comparison.csv

In [12]:
# Display comparison
print("\nConfiguration Comparison:")
display(comparison.to_dataframe())

Configuration Comparison:

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,pubmedqa_title_aware_v11_query_transform,0.5317,0.1724,0.2653,0.1785,0.5146,0.3393,0.20,0.65
1,pubmedqa_title_aware_v14_pubmedbert_stepback,0.3471,0.2087,0.1186,0.2625,0.2617,0.4767,0.50,0.55
2,pubmedqa_title_aware_v15_biomedical_reranker,0.3441,0.2426,0.1534,0.2688,0.3221,0.4758,0.65,0.50
3,pubmedqa_title_aware_v16_improved_retrieval,0.4815,0.2007,0.4270,0.2900,0.6695,0.3462,0.15,0.70
4,pubmedqa_title_aware_v18_balanced,0.4980,0.2161,0.3706,0.2709,0.5498,0.3566,0.30,0.65
5,pubmedqa_title_aware_v13_balanced,0.5898,0.1904,0.2970,0.1718,0.5330,0.2647,0.20,0.65
6,pubmedqa_title_aware_v12_improved_prompt,0.4747,0.1818,0.2242,0.2174,0.3458,0.4420,0.45,0.60
7,pubmedqa_title_aware_v17_hybrid_transform,0.4610,0.2491,0.2410,0.2619,0.3828,0.4098,0.45,0.50

## 11. Summary

The ExperimentRunner provides a complete workflow for:

1. **Configuration-driven data loading** - Specify data source in YAML
2. **Automatic parsing** - Documents parsed using configured parser
3. **Multi-config evaluation** - Test multiple RAG configurations
4. **Parallel execution** - Speed up evaluation with parallel runs
5. **Comprehensive reporting** - Per-query and aggregate metrics
6. **Cross-config comparison** - Identify best performing config

### Key Benefits:

- **Reproducible** - Everything configured in YAML
- **Flexible** - Easy to change data source or parser
- **Scalable** - Parallel execution for faster evaluation
- **Comprehensive** - Detailed metrics and comparisons